### ISSUE TITLE
Get Element value of checkbox or Radio

### ISSUE THREAD

**Issue by andy194** [jzaefferer/jquery-validation#1084]
Hi, we've been trying to work with unobtrusive validation but hit a problem.  When validating a checkbox the code attempts to get the value of the check state, however because it looks for all fields with a 'name' in a checked state, but also pulls back hidden fields with the same name and then tries to get the val from an array, it fails...
(Line 564 jquery.validate.js, v1.12)
```js
elementValue: function( element ) {
			var val,
				$element = $(element),
				type = $element.attr("type");

			if ( type === "radio" || type === "checkbox" ) {
--->				return $("input[name='" + $element.attr("name") + "']:checked").val();
			}

			val = $element.val();
			if ( typeof val === "string" ) {
				return val.replace(/\r/g, "");
			}
			return val;
		}
```

It effectively needs to do the same as the code in 'validationTargetFor' (Line 772) and ignore hidden elements with the same name:-
```js
// if radio/checkbox, validate first element in group instead
	element = this.findByName( element.name ).not(this.settings.ignore)[0];
```
Cheers,

Andy.

**Comment by jzaefferer** [comment]
Should be fixed by #1064
