### ISSUE TITLE
Incorrect charset on Microsoft’s Ajax CDN

### ISSUE THREAD

**Issue by Krinkle** [jzaefferer/jquery-validation#1207]
This file contains character encoding artifacts due to the server not sending the appropriate `charset=utf-8` in the headers.

http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.js

````
 * Copyright (c) 2014 JÃ¶rn Zaefferer
```

What it is sending:
```
Content-Type: application/x-javascript
```

What it should be sending:
```
Content-Type: application/x-javascript; charset=utf-8
```
Or:
```
Content-Type: text/javascript; charset=utf-8
```

**Comment by staabm** [comment]
We already link both cdns in the docs. Closing.
