### ISSUE TITLE
How to reset validator object

### ISSUE THREAD

**Issue by eskandari** [jzaefferer/jquery-validation#1268]
I'm currently working on a mobile project and using jQuery validation plugin to do client-side validation.
I'm also using jQuery Mobile, with the single-page template (I have pages in separate files, but when changing pages 
JQM reads the file and injects the new page content to the DOM). 

In this project, Im forcing JQM to remove the previous page in order to have the DOM smaller.

// remove page to prevent caching
$('div').on('pageshow', function (event, ui) {
    $(ui.prevPage).remove();
});

The first page is the login screen with a simple form for username and password. Everything goes well in the first shot: 
The validation plugin complains if the submit button is pressed and some fields are empty.
If all fields are OK and submit is pressed, I make an ajax call to a web service, save data in the DB and the next page is displayed.

In the next screen, the validation plugin just does not work properly. It does not validate, and when the submit is pressed, the form is submitted even when the required input textboxes are empty and there are no errors in the console.
Is there something I'm missing? How could I "restart" the plugin? Maybe it still thinks the previous call didn't finish?

I'm debugging the non-minified plugin js file, and it looks like the problem is the initialization it does in the validate call. 
In the first call, which completes successfully, the plugin creates a validator wich binds to the form, and it caches the validator. 
In the second call, I'd need it to bind a new validator to the new form, and instead it is returning me the old validator (binded to the old form).

So, this plugin binds to a form when validate is called and keeps binded to it as long as the form is in the DOM. 
Also it caches the validator, so subsequent calls to validate over the same form return the very same validator.

My question is, how I would be able to prevent validator object to be cached or how I would be able to reset this object on the second jquery mobile page?

Thanks in advance.

**Comment by eskandari** [comment]
I am not sure, How i could follow up on this?

**Comment by jzaefferer** [comment]
Sounds like #1392 could address your issue.
