### ISSUE TITLE
Step attribute is not supported

### ISSUE THREAD

**Issue by pierrocknroll** [jzaefferer/jquery-validation#1295]
Hello and thanks for your great tool,

The "step" attribute in an input type "number" is not correctly supported.

Exemple
```
<input type="number" step="0.01">
```
Without your plugin, in chrome 38, while submitting the form, the browser show an error for the value 15.511 (no error for 15.51)

With your plugin, no error is thrown.

Is it normal that your plugin completely avoid browser's validations ?

Thanks

**Comment by jzaefferer** [comment]
See #1405

**Comment by rprimora** [comment]
I am new to GitHub so I wanna ask a stupid question. I have added jQuery.Validation by jzaefferer to my project via GitHub in VS2015 and I am still getting the error for step. Is there anything special I should do to make it work?

**Comment by staabm** [comment]
@rprimora please create a separate issue and provide information with information on how to reproduce your issue. thanks.
