### ISSUE TITLE
Handling ASP.NET MVC Input Arrays Exception (function: idOrName)

### ISSUE THREAD

**Issue by audacity76** [jzaefferer/jquery-validation#1337]
Hi,

I'm getting errors using jquery validation in an asp.net mvc 5 project. I also use jquery validation obtrusive but I believe the error sits inside jquery validation.

MVC 5 generates input elements for arrays like that:

```html
<input name="[0].somefieldname" type="text" value="10" data-val="true" data-val-number="the error message" data-field="somefieldname">
<input name="[1].somefieldname" type="text" value="21" data-val="true" data-val-number="the error message" data-field="somefieldname">
<input name="[2].somefieldname" type="text" value="4" data-val="true" data-val-number="the error message" data-field="somefieldname">
```

The problem is that jquery validation looks for the name in a jquery selector which causes following exception:

JavaScript runtime error: Syntax error, unrecognized expression: label[for='[0].somefieldname'], label[for='[0].somefieldname'] *, #[0].somefieldname-error

Proposal:

change function idOrName from

idOrName: function( element ) {
		    return this.groups[element.name] || (this.checkable(element) ? element.name : element.id || element.name); 
		},

to

idOrName: function( element ) {
		    return this.groups[element.name] || (this.checkable(element) ? element.name : element.id || element.name).replace("[", "\\[").replace("]", "\\]"); 
		},

**Comment by PiRXlv** [comment]
There is a small problem with your proposed fix - you have to use double slashes when replacing, like this:
    return this.groups[element.name]
        || (this.checkable(element)
            ? element.name
            : element.id || element.name)
        .replace("[", "\\[")
        .replace("]", "\\]");

**Comment by jzaefferer** [comment]
I can't reproduce this problem. I've opend `demo/index.html', removed the `id` attribute on the first input and set its `name` attribute to `name="[0].somefieldname"`. I also tried setting `errorElement: "span"` for the form, but that doesn't make a difference either, it still works fine.

Please make sure you're testing with the latest release, currently 1.13.1. If you're still having issues, please [provide a testpage that shows the issue](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by PiRXlv** [comment]
Checked. Reproducable with 1.13.0, works fine with 1.13.1.

**Comment by jzaefferer** [comment]
Well, if it works with 1.13.1, there's nothing to do here :-)

**Comment by audacity76** [comment]
Yes, I can confirm. Works with 1.13.1. Well done!

On Tue, Jan 20, 2015 at 4:36 PM, Jörn Zaefferer <notifications@github.com>
wrote:

> Well, if it works with 1.13.1, there's nothing to do here :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jzaefferer/jquery-validation/issues/1337#issuecomment-70672785>
> .
>



-- 
www.svenjohannsen.net

**Comment by PiRXlv** [comment]
Yup, just leaving mark for history – wasn’t working with 1.13.0, works with 1.13.1 :)
