### ISSUE TITLE
Optimize testsuite runtime

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/jquery-validation#1343]
Currently the testsuite takes too long to finish. There are several test that take more than 50ms. A bunch of those can probably be faster simply by reducing timeouts, like this: https://github.com/jquery/qunit/commit/97c916c4e68aae56b13c2e8a4f75d61879075cc0.

@staabm is this something you could look into?

**Comment by staabm** [comment]
@jzaefferer see PR 1496
