### ISSUE TITLE
Localization doesn't working properly

### ISSUE THREAD

**Issue by ottomen** [jzaefferer/jquery-validation#1362]
Hi! Thanks for the useful plugin.
I'm trying to use multilingual error messages, but my error state is only required field, but not the "name" or "emai" messages.
 I'm using "$.extend($.validator.messages, {required: "Це поле необхідно заповнити.",
});name:"Введіть ваше ім'я."...});" But the only state is "required: "Це поле необхідно заповнити.".

**Comment by jzaefferer** [comment]
Thanks for the report, but this doesn't indicate an issue with the validation plugin. To get help, I recommend to put together a test page using [jsfiddle](http://jsfiddle.net) or [jsbin](http://jsbin.com). Also a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) is going to be more helpful.
