### ISSUE TITLE
How to validate the selected elements only?

### ISSUE THREAD

**Issue by pzheng64** [jzaefferer/jquery-validation#1364]
Is there any way to validate the elements having a specific selector in a form?
For example,

I'd like to validate the items having class "submit-opt" in a form.  I could find "ignore" option in jQuery Validation plug-in documentation, but not sure how to do reversely.

I tried to use $form.find(".submit-opt").valid(), but there happened a JS error
*Uncaught TypeError: Cannot read property 'nodeName' of undefined*

Thanks.

**Comment by jzaefferer** [comment]
`ignore: ":not(.submit-opt)" should do the trick. Otherwise, a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) should help.
