### ISSUE TITLE
Email validation not working with: aa@bb

### ISSUE THREAD

**Issue by samwebtech** [jzaefferer/jquery-validation#1367]
If you enter aa@bb the validation passes. 
This happens on demo as well: http://jqueryvalidation.org/files/demo/

I updated the email regex in my local validate.js to:
^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?){1,}$

At the end it was *  before $ but I changed to {1,}. That started displaying appropriate message.

**Comment by staabm** [comment]
See readme

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them.
