### ISSUE TITLE
Documentation issue...

### ISSUE THREAD

**Issue by sparky672** [jzaefferer/jquery-validation#1369]
On this page...

http://jqueryvalidation.org/reference/#link-validating-multiple-forms-on-one-page

The word **"link"** appears just in front of every sub-heading.  I believe this to be a mistake because the other pages in the documentation contain a *hidden* link that only appears upon hover.

**Comment by jzaefferer** [comment]
Thanks for the report! Fixed it.

**Comment by sparky672** [comment]
Thank-you but the issue still appears.

<a href="http://s2.postimg.org/r4i90a6a1/j_QV_links.jpg">screenshot</a>

It also popped up on the "Documentation" page...

<a href="http://jqueryvalidation.org/documentation/">jqueryvalidation.org/documentation</a>

**Comment by jzaefferer** [comment]
Right, I didn't actually deploy the change before, only tested locally. Fixed!

**Comment by sparky672** [comment]
Sorry!  Thanks!
