### ISSUE TITLE
Problems with jQuery UI buttons in Webkit browsers due to event.target being SPAN instead of BUTTON

### ISSUE THREAD

**Issue by snobo** [jzaefferer/jquery-validation#1370]
jQuery UI pimps &lt;BUTTON&gt; tag, inserting &lt;SPAN&gt; inside when creating a Button widget. In Firefox and IE, when user clicks on a button (both plain and widget), target.event is always BUTTON itself. In Webkit, however, in case of the widget, target.event is SPAN. Hence, validateDelegate() misbehaves in this case and doesn't run the :submit handler. As the result, formnovalidate attribute and class="cancel" are ignored, and in the submitHandler() function, this.submitButton is not set.

Demo, detailed description and possible solution are here:
http://jsfiddle.net/snobo/Lv0h0yxk/7/

**Comment by jzaefferer** [comment]
Thanks you for the report. Could you submit a PR that replaces `validateDelegate` with `on`, as you suggest in your fiddle? Its currently not being used to support jQuery 1.6.x (`on` was added in 1.7), but by now I'm fine with dropping that.

**Comment by Korri** [comment]
Created a pull request, used a more general way then `on`

**Comment by Westie** [comment]
As a FYI, #1392 ended up changing validateDelegate to $.fn.on

**Comment by Korri** [comment]
Looks great, either solutions works, as long as we don't keep the current implementation :)

**Comment by jzaefferer** [comment]
See #1423 and #1490
