### ISSUE TITLE
IE8 sent form without any validation

### ISSUE THREAD

**Issue by alex-spin** [jzaefferer/jquery-validation#1371]
IE8 sent form without any validation every time, bug with condition(line 43, jQuery Validation Plugin 1.11.1):
if ( $(event.target).attr("formnovalidate") !== undefined ) {
	validator.cancelSubmit = true;
}
 and I fixed that:
 if ( $(event.target).attr("formnovalidate")){
	validator.cancelSubmit = true;
}

Please apply this fix in new version of plugin. Thanks

**Comment by jzaefferer** [comment]
I've seen this kind of report before, and its usually caused by testing in compatibility modes, which this plugin doesn't support. Please make sure you test in real browsers.

**Comment by sandmanman** [comment]
FUCK IE
