### ISSUE TITLE
param & value for min & max rules should be type cast when rules are specified through data attributes

### ISSUE THREAD

**Issue by zhenrong** [jzaefferer/jquery-validation#1378]
When rules are specified through data attributes such as data-rule-min="77.50", before param and value can be compared they should be typecast, such as through parseFloat. Currently, both value and param are strings. As a result, string comparison is performed instead.

Currently, the type of both value and param are string as tested in:

    // http://jqueryvalidation.org/min-method/
	min: function( value, element, param ) {
		console.log( typeof value, typeof param ); // console ouput: string string
		return this.optional( element ) || value >= param;
	},

This is reproduced in this jsfiddle: http://jsfiddle.net/1rxvgL4v/13/

If you entered 123 into the amount field which is (obviously) larger than 77.50, the error message appears.

If you entered 8 which is less than 77.50, the error message disappears.

**Comment by jzaefferer** [comment]
See #1391
