### ISSUE TITLE
Broken Email Validation

### ISSUE THREAD

**Issue by technologystorm** [jzaefferer/jquery-validation#1387]
Using version 1.13.1 or 1.13.0 , when validating an email address such as john_smith@yahoocom (having an underscore in the name, and missing the "period" in the domain name), the script believes this to be properly format email address. I thought this might be related to the "underscore" but johnsmith@yahoocom also passes as valid.

**Comment by wozzo** [comment]
It's using the definition of an email from [url]https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address[/url] so this is most likely the desired effect.

**Comment by technologystorm** [comment]
If this is what your referring to:
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
I'm not an expert in regular expressions, but this looks like a "period" is required in the second half of the address. This would indicate the script is not calculating correctly.

**Comment by wozzo** [comment]
The final group containing the period has a ? at the end making the preceding group optional
(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?

**Comment by technologystorm** [comment]
Wozzo, OK I agree and your correct...but from the original source doesn't it say:
This requirement is a willful violation of RFC 5322, which defines a syntax for e-mail addresses that is simultaneously too strict (before the "@" character), too vague (after the "@" character), and too lax (allowing comments, whitespace characters, and quoted strings in manners unfamiliar to most users) to be of practical use here.
Why would something of "non-practical use" be used for this? Wouldn't common sense tell us, as a minimal change to the rule, that the email should end in a period and then at least 2 characters or more to complete the TLD?
On the flip side I see tons of websites discussing this issue as there is no "right way" to do it, so with that said I leave this to the discretion of the developers, but also challenge them to make improvements instead of looking at the RFC 5322 standard which is clearly not useful.

**Comment by wozzo** [comment]
I agree that it's not what you'd expect for an email, but it is technically valid.
I think the simplest solution for what you're looking for is to use something like the addValidation() method http://jqueryvalidation.org/jQuery.validator.addMethod/

I've modified the example at the bottom to achieve this here http://jsfiddle.net/ff32dxm1/

**Comment by staabm** [comment]
Right. As described we use a pattern which is part of the w3c spec.

See also the readme note:
> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

**Comment by technologystorm** [comment]
Wozzo...thanks for the quick fix. Lets hope moving forward the W3c updates their method soon. Cheers!
