### ISSUE TITLE
Remote Validation JSON Response

### ISSUE THREAD

**Issue by turquoiseowl** [jzaefferer/jquery-validation#1401]
The 'success' callback function that is called after a successful remote validation request starts off with the following:

```
function(response) {
    var valid = response === true || response === "true" ...
}
```

Given that the request is for a JSON object, I'm struggling to see how ```response``` can be anything other than an object. The upshot of which is that ```valid``` cannot be set to ```true```.

In practice, jQuery is indeed failing to parse a response containing just the text "true" into a json object, and so is 'erroring' the request.

I'm sure I'm missing something. Can anyone help me out?

Thank you.

jQuery 1.8
Chrome v40

P.S. A further issue is that should the remote validation request fail with an error, there is no error handler function registered and so ```validator.stopRequest( element, valid );``` ain't called. I think this means that the element is then forever pending validation.

**Comment by jzaefferer** [comment]
Parsing "true" as JSON works fine:
```js
JSON.parse("true") // true
jQuery.parseJSON("true") // true
```
The missing error handler is indeed an issue.

**Comment by turquoiseowl** [comment]
Indeed, that is true! My mistake. The problem I was getting was not as stated with success response, but with the failure response.

Rather than fail with just the string "false", I was sending back an arbitary string like "Sorry, wrong answer":

```
var message = response || validator.defaultMessage( element, "remote" );
```

and that is what is not parsing into JSON (although, it has worked in the passed!)

Perhaps something is jQuery or Chrome v40's JSON parser is more strict than before.

Thanks for your reply.
