### ISSUE TITLE
Email validation bug

### ISSUE THREAD

**Issue by IOZ** [jzaefferer/jquery-validation#1410]
Hi Jörn,

Email validation rule works incorrect, 
for e.g try to validate emails below:
user@gmail
user@gmail.c

Please, fix it.

Cheers,
Igor.

**Comment by staabm** [comment]
we use a pattern which is part of the w3c spec.

See the readme note:
> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

**Comment by IOZ** [comment]
Solution for those, who want to use correct validation:

1. add additional method to $.validator

```javascript
$.validator.addMethod("validateEmail", function(value, element) {
				var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
				return this.optional(element) || re.test(value);
			}, globalLibrary.EMAIL);
```
2. validate filed

```javascript
$("#your-form-id").validate({
				rules: {
					"email" : {
						required: true,
						validateEmail: true
					}
			  	}
			});
```
