### ISSUE TITLE
ShowErrors do not stop submit

### ISSUE THREAD

**Issue by enghelewa** [jzaefferer/jquery-validation#1412]
Hi,
I am using this plugin alongside with jquery validation
https://github.com/Bluefieldscom/intl-tel-input
the plugin has its own validation to validate phone number according to selected country and I use `showErrors` to only show an error similar to other fields messages `required integer date etc`. The problem is the message show on but the form still valid and proceed to submit.
My question is "Is there any way to invalidate the form after calling showErrors?"
Note that my input field has no rules related to jquery validation
`<input class="form-control" id="Tel" name="Tel" type="text" placeholder="02 223 4567">`

thanks in advance :)

**Comment by staabm** [comment]
You could add a custom validator func which works on the api of your external plugin, see http://jqueryvalidation.org/jQuery.validator.addMethod

**Comment by enghelewa** [comment]
@staabm 
You saved my day superman .. Thank you :+1:
