### ISSUE TITLE
Bug with dateITA and daylight saving time in New Zealand

### ISSUE THREAD

**Issue by jeredmasters** [jzaefferer/jquery-validation#1414]
I've found another issue relating to date validation.
v1.13.1 - 10/14/2014
This relates to bug #264, where I've also posted this information.

### Problem
We had some customers in New Zealand complaining they couldn't submit the form.
This was reproducible by changing the system timezone on my OSX. 

### Cause
While New Zealand is in daylight savings time their time zone is GMT+13:00.
When javascript processes the "getUTCDate()" it applies -13:00 time change.

The validation function sets the time to 12 noon while parsing, then the -13 hour shift takes the date to 23:00 the previous day.
Then the if statement "xdata.getUTCDate() === gg" fails and says the date is invalid.

### Solution
Our solution was to change the date parser in 
src/additional/dateITA.js:29

```
xdata = new Date(aaaa, mm - 1, gg, 12, 0, 0, 0);
```
to
```
xdata = new Date(Date.UTC(aaaa, mm - 1, gg, 12, 0, 0, 0));
```

I've tested this with several different timezones and it seems to work well.

(Note: I didn't actually change the jquery.validate js, I duplicated the validation method into another js file, gave it a new name, and modified it there)

**Comment by jzaefferer** [comment]
Could you send a pull request for that change? If possible, including unit tests?

**Comment by jeredmasters** [comment]
https://github.com/jzaefferer/jquery-validation/pull/1416

**Comment by tractorcow** [comment]
I can also confirm this bug; Working from NZ the unit tests fail. :)
