### ISSUE TITLE
updated - messages_de + new dateGER

### ISSUE THREAD

**Issue by ltdeta** [jzaefferer/jquery-validation#1419]
***for my own usage some improvements for the german `messages_de.js`***
+ dateISO
+ maxlength
+ minlength    
Download: [messages_de.js](http://www.file-upload.net/download-10353777/messages_de.js.html)

***new method `dateGER` for german date (based on [jQuery validation additional method german date](http://snipplr.com/view/58062/))***
Download: [dateGER.js](http://www.file-upload.net/download-10353736/dateGER.js.html)

***some additional translations for***
+ maxWords
+ minWords 
+ rangeWords
+ alphanumeric
+ bic
+ iban
+ dateGER
+ time
+ integer
+ lettersonly
+ notEqualTo
+ nowhitespace  
Download: [messages_de-upd.js](http://www.file-upload.net/download-10353730/messages_de-upd.js.html)

**Comment by jzaefferer** [comment]
Please provide these as a pull request. Thank you.
