### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by arfmach** [jzaefferer/jquery-validation#1421]
It is accepting "." (dot) at the beginning of local-part, at the end of local-part, duplicated (like "any..address@example.com" or "anyaddress@example..com") and numbers on TLD (like "abc@1234.567" instead of accepting only these http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

**Comment by staabm** [comment]
See readme

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them.
