### ISSUE TITLE
Type inconsistency in argument min/max rules

### ISSUE THREAD

**Issue by szymanskilukasz** [jzaefferer/jquery-validation#1425]
According to documentation min/max methods takes a value argument as "Number" type: http://jqueryvalidation.org/min-method/

So why inputs with type="date" are allowed to validate with these methods, example from test/index.html

    <input type="date" id="rangeDateInvalidGreater" name="rangeDateInvalidGreater" min="2012-11-21" max="2013-01-21" value="2013-02-21">

It occurs that compared value is actually "string" type not "Number", or am I missing something.

Thanks for answer, and great plugin ;)

**Comment by jzaefferer** [comment]
Comparing dates as numbers leads to bad results, so that "inconsistency" is on purpose. I don't have an example at hand though. In this case, the documentation is a bit misleading and needs an update.

**Comment by szymanskilukasz** [comment]
@jzaefferer Thanks for answer, now its clear. I'll try to update documentation on free time. Cheers.
