### ISSUE TITLE
URL Regex

### ISSUE THREAD

**Issue by chrispcb** [jzaefferer/jquery-validation#1426]
Maybe update url method.
Look here : https://mathiasbynens.be/demo/url-regex

Diego Perini version seems to be the best.

**Comment by jzaefferer** [comment]
Thanks a lot for pointing that out! I've replaced the existing regex with Diego's.

**Comment by crash-dive** [comment]
This change now means that all IP addresses in the private address spaces are considered invalid which I do not think is correct, so all cat A, B and C addresses no longer validate.

For example http://192.168.0.59 is not considered a valid URL by this regex. We store the private URL certain networking equipment in our application which cannot be that odd so I am not sure this is the best regex to use.

**Comment by dtanders** [comment]
It also invalidates local addresses that don't have enough dots in them like http://internal-server/some.file

Really the only valid way to test a URL is to try to request it, IMO.

**Comment by DawoudIO** [comment]
Guys I'm having issues with URLs = `http://127.0.0.1/` or `http://192.168.33.10/` anyway to override the private IPs

**Comment by Arkni** [comment]
@DawoudIO the used regex is from here: https://gist.github.com/dperini/729294
From the comments of the regex:
```js
// the regular expression composed & commented
// could be easily tweaked for RFC compliance,
// it was expressly modified to fit & satisfy
// these test for an URL shortener:
//
//   http://mathiasbynens.be/demo/url-regex
//
// Notes on possible differences from a standard/generic validation:
//
// - utf-8 char class take in consideration the full Unicode range
// - TLDs have been made mandatory so single names like "localhost" fails
// - protocols have been restricted to ftp, http and https only as requested
//
// Changes:
//
// - IP address dotted notation validation, range: 1.0.0.0 - 223.255.255.255
//   first and last IP address of each class is considered invalid
//   (since they are broadcast/network addresses)
//
// - Added exclusion of private, reserved and/or local networks ranges
//
// - Made starting path slash optional (http://example.com?foo=bar)
//
// - Allow a dot (.) at the end of hostnames (http://example.com.)
```
