### ISSUE TITLE
1.13.1 readonly fields will not validate

### ISSUE THREAD

**Issue by Jrizzi1** [jzaefferer/jquery-validation#1432]
I see that  issue https://github.com/jzaefferer/jquery-validation/issues/1383 , and that this should have been fixed, but in the download on the jquery validation website, readonly is still ignored and will not trigger validation

**Comment by dmnrmr** [comment]
Problem still exists.

**Comment by tsjoberg** [comment]
Looks like its been committed but not released yet

**Comment by jzaefferer** [comment]
Will be fixed in next release.
