### ISSUE TITLE
Mirror documentation on Github

### ISSUE THREAD

**Issue by pljspahn** [jzaefferer/jquery-validation#1434]
Seems like it would be a benefit to have the documentation mirrored here as the project's website is currently not responding.

**Comment by staabm** [comment]
Its on github, see https://github.com/jzaefferer/validation-content

**Comment by pljspahn** [comment]
Setting up a new server and installing wordpress and all that just to read the docs? Super!

**Comment by jzaefferer** [comment]
The site is working fine for me ( also http://www.downforeveryoneorjustme.com/http://jqueryvalidation.org/ ), and I didn't get any alerts from Pingdom, which monitors the site and reports 100% uptime for the last 7 days (haven't checked before that).

Please try again, maybe it was just a temporary problem on your end?
