### ISSUE TITLE
Using unminified version (and minifying with Gulp) throws an error

### ISSUE THREAD

**Issue by bertoost** [jzaefferer/jquery-validation#1447]
I am always using un-minified versions of any JS plugins. Because I do want to apply my own minifier like Gulp. But an error occur when I use the un-minified validate version.
This is how my minify config looks like;

```
'path/to/my/js/folder/jquery/jquery.js'
,'path/to/my/js/folder/jquery/jquery.migrate.js'
,'path/to/my/js/folder/jquery/plugins/jquery.validate.js'
,'path/to/my/js/folder/jquery/plugins/jquery.validate-addtional-methods.js'
// ...
// some other jquery plugins
// ...
,'path/to/my/js/folder/bootstrap/bootstrap.js'
// ...
// some others here
// ...
,'path/to/my/js/folder/custom.js'
```

And after I minified it, I am getting an error about this line, the first of the un-minified validate plugin file.

```
(function( factory ) {
```

Throws this error: Uncaught TypeError: object is not a function

In the minified file, it looks like this part is being rewritten to this;

```
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):a(jQuery)}(function(a){
```

This works.

The un-minified files are also working when I just use all the files as single ```<script>``` tags inside my HTML templates. Then there is no error. So probably there is an issue with that, when it's being concatted and minified to one file.

Do you have an explanation for it? Thanks in advance.

**Comment by jzaefferer** [comment]
No idea. Please use the forum or Stackoverflow to get help.

**Comment by nonom** [comment]
I have the same problem. Nowadays, the most part of projects are built with grunt/gulp, so I'm stopping using that plugin since the author not interested.

**Comment by staabm** [comment]
Why do you un-minify files instead of minifying the plain source?
