### ISSUE TITLE
dateITA (from additional-methods) will incorrectly validate false in some region/time.

### ISSUE THREAD

**Issue by mcshaz** [jzaefferer/jquery-validation#1463]
the dateITA function contains the line:
if ( ( xdata.getUTCFullYear() === aaaa ) && ( xdata.getUTCMonth () === mm - 1 ) && ( xdata.getUTCDate() === gg ) ) {

I would recommend changing these all to the local time variant - i.e.
if ( ( xdata.getFullYear() === aaaa ) && ( xdata.getMonth () === mm - 1 ) && ( xdata.getDate() === gg ) ) {

alternatively, the line:
xdata = new Date(aaaa, mm - 1, gg, 12, 0, 0, 0);
could be altered to :
xdata = new Date(Date.UTC(aaaa, mm - 1, gg, 12, 0, 0, 0));

looking at how firefox creates a new date:
var a = new Date(2013,0,3,12,0,0,0); 
console.log(a.getUTCDate()); 
console.log(a.getDate()); 
console.log(a);
returns: 
2
3
Date {Fri Jan 03 2014 00:00:00 GMT+1300 (New Zealand Daylight Time)}

note that GMT +1300 is a valid timezone (http://en.wikipedia.org/wiki/UTC%2B13:00)

i.e., because of the timezone and time of day, the date entered (3) has a UTC date of 2, hence the test will incorrectly fail anywhere with a GMT zone -12, +12.75, +13 or +14 (see http://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png). Some countries on daylight saving (such as New Zealand) will reliably fail on dates over the daylight saving period.

a fiddle is here:
http://jsfiddle.net/rhuwkode/27/
however, it will only emulate the incorrect behavior if the settings are to a country which has UTC of -12, +13 or 14 on at least some dates of the year (the more populated countries are listed on the fiddle).

**Comment by jzaefferer** [comment]
Should be fixed by #1416
