### ISSUE TITLE
valid() and element() incorrectly return true for remote method

### ISSUE THREAD

**Issue by NotionCommotion** [jzaefferer/jquery-validation#1465]
The first time `valid()` and `element()` is executed (for example, in the click event on testit), they both incorrectly return true even if the remote method indicates that it shouldn't pass validation.  Note that the error message in fact is still displayed.

    <!DOCTYPE html>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <title>Testing</title>  
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js" type="text/javascript"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.js" type="text/javascript"></script>
            <script type="text/javascript"> 
                $(function(){
                    var validator=$("#myForm").validate({
                        rules: {
                            bla: {
                                minlength:2,
                                maxlength:4,
                                required:true,
                                remote: "validate.php"
                            }
                        },
                        messages: {
                            bla: {
                                remote:"error message"
                            }
                        }
                    });
    
                    $('#testit').click(function(){
                        $('#bla').val('test');
                        console.log($('#bla').valid());
                        console.log(validator.element('#bla'));
                    })
                });
            </script>
        </head>
    
        <body>
            <form id="myForm" method="post">
                <input name="bla" id="bla" value="" readonly>
            </form>
            <button id="testit">testit</button>
        </body> 
    </html>

**Comment by NotionCommotion** [comment]
Looks like this has already been identified at https://github.com/jzaefferer/jquery-validation/issues/1045.  Any idea whether it will ever be addressed?

**Comment by jzaefferer** [comment]
Closing in favor of #1045
