### ISSUE TITLE
rules() doesn't remove a remote method

### ISSUE THREAD

**Issue by NotionCommotion** [jzaefferer/jquery-validation#1466]
http://jqueryvalidation.org/rules/ describes how to add and remove a rule from jQuery validator.

As demonstrated at http://jsfiddle.net/h0apn1a1/1/, it removes the "remote" rule from the object, but doesn't prevent the remote rule from being executed.

    var validator = $("#myForm").validate({
         rules: {
             myelement: {
                 minlength: 2,
                 maxlength: 4,
                 required: true,
                 remote: {
                     url: "/echo/html/",
                     type: "POST",
                     data: {
                         html: 0,
                         delay: .5
                     }
                 }
             }
         },
         messages: {
             myelement: {
                 remote: "error message"
             }
         }
     });

     $('#testit').click(function () {
         console.log($('#myelement').rules());
         $('#myelement').rules('remove', 'remote');
         console.log($('#myelement').rules());
         console.log($('#myelement').valid(), validator.element('#myelement'));
     })

**Comment by jzaefferer** [comment]
Can you look into a fix for this and send a pull request? Otherwise its very unlikely to get addressed.

**Comment by Arkni** [comment]
@NotionCommotion 

It's not a problem with the plugin, it's a problem with your code that tries to remove a method from an element and forgot that the plugin will validate your element `on focus out` if that element is filled out and is not optional.

What I mean is, after filling the element with a value (a valid or invalid one), you will click your button after, so the element will lose the focus which result in calling the `onfocusout` method of the plugin, which in its turn will validate your element, thus, the method you tried to remove will be called even before removing it.
