### ISSUE TITLE
is there a way to not trigger showing errors when using $(".element").valid() method?

### ISSUE THREAD

**Issue by hippich** [jzaefferer/jquery-validation#1469]
I tried to follow code and looks like it always shows errors whenever .valid() is called. I want to call .valid() on keyup() event, but do proper validation on onblur event, so overriding showErrors option doesn't work.

**Comment by lancevo** [comment]
I'm looking to do something similar, what I simply want is `onfocusin` to display a helper message.

**Comment by staabm** [comment]
What do sou expect .valid() should do onkeyup and what should it do onblur()? Why calling it twice?

**Comment by hippich** [comment]
In my particular case, I add a keyup listener to the field to update
something else on the screen, but only if the value is valid. But since
user still types it, I don't want to show error just yet. And on onblur
I want to show standard jquery-validation error message next to the
field. Hope this make sense.

**Comment by lancevo** [comment]
I used onfocusout, and validate the element with this.element()
There's an example on the page below

http://lancevo.github.io/2015/01/29/jquery_valiation_addMethod.html

**Comment by hippich** [comment]
But it looks like if I use $("input").valid(), it still would set error
on the field, wouldn't it?

**Comment by jzaefferer** [comment]
If someone implements this feature and sends a pull request, I can review and merge it, otherwise it is unlikely to ever get implemented. Sorry folks.
