### ISSUE TITLE
Is this a good fit for Drupal 8?

### ISSUE THREAD

**Issue by mgifford** [jzaefferer/jquery-validation#1471]
I'm not a JS person, but have been struggling with HTML5's required fields & how to address accessibility issues & usability issues that come with it.  Seems the best approach is to override it with JS validation.

So, since Drupal's already using jQuery, how hard would it be to integrate into Drupal 8 Core?  

The thread for validation is here:
https://www.drupal.org/node/1797438

I'd love some feedback on this.

**Comment by jzaefferer** [comment]
Looking at your comment on the drupal issue itself, I think you can be pretty confident about using this plugin based on the usage references you already found. I'm happy to answer more specific questions about the plugin. I can't make estimates for the integration itself, since that requires knowledge of Drupal which I don't have.

**Comment by mgifford** [comment]
Ok, so I take it I should be attempting to install this by going to the vendor directory in Drupal 8:
    cd drupal8/core/assets/vendor/jquery

And then just running:
    $ bower install jquery-validation

That sets up a bower_components directory, but doesn't change anything else, so I'm thinking I'm doing something wrong here.

**Comment by jzaefferer** [comment]
I can't help you with that, it depends very much on Drupal.

**Comment by mgifford** [comment]
Ok, so let's say I've just got jQuery set up on a small site I'm using.  How do I go about installing jquery-validation?  If off the root directory I've already got a jquery directory, how do I add the jquery-validation plugin?  

It's really not clear to me what bower is doing or how to install this.

**Comment by jzaefferer** [comment]
That's not much of an issue with this plugin, but a rather generic JavaScript issue. I'm sure you can find answers about bower elsewhere, or on StackOverflow to your particular question.
