### ISSUE TITLE
Using with bootstrap-datetimepicker has error  can also submit form？

### ISSUE THREAD

**Issue by jast90** [jzaefferer/jquery-validation#1472]
Using with bootstrap-datetimepicker has error  can also submit form？

**Comment by jzaefferer** [comment]
Thanks for the report, but this doesn't indicate an issue with the validation plugin. To get help, I recommend to put together a test page using [jsfiddle](http://jsfiddle.net) or [jsbin](http://jsbin.com). Also a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) is going to be more helpful.
