### ISSUE TITLE
Error "This field is required" is not shown on the first field if you are using "equalTo" for the second field (safari iOS8)

### ISSUE THREAD

**Issue by yukozlovskiy** [jzaefferer/jquery-validation#1473]
http://jsfiddle.net/BSdc8/44/

You can reproduce this bug only on safari iPhone/iPad(iOS8)

Steps to reproduce:
1. Select 'Confirm New Password' option 
2. Enter valid values in 'Confirm new password' 
3. Leave filed 'New Password' blank 
4. Tap 'Submit' button

Result: 
Message 'This field is required.' does not appear to 'New Password' field after submit.

**Comment by jzaefferer** [comment]
Can you look into the cause of this issue and try to submit a pull request? Otherwise this is very unlikey to get addressed. Sorry.
