### ISSUE TITLE
How to prevent hiding specific error?

### ISSUE THREAD

**Issue by 8Sarit** [jzaefferer/jquery-validation#1476]
I make a server validation in my project using ajax.
If the validation of the element is wrong I put an error class to those elements.
My problem is that the t
his.toHide = this.toHide.not( this.toShow );
this.hideErrors();
cause those error to disappear.
How can I prevent hiding specific errors?

**Comment by jzaefferer** [comment]
Thanks for the report, but this doesn't indicate an issue with the validation plugin. To get help, I recommend to put together a test page using [jsfiddle](http://jsfiddle.net) or [jsbin](http://jsbin.com). Also a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) is going to be more helpful.
