### ISSUE TITLE
How do you validate checkbox input on change?

### ISSUE THREAD

**Issue by alexbooker** [jzaefferer/jquery-validation#1477]
Hello. I am in a spot of bother and am hoping someone here can help. 

Here is my predicament: 

When the user enters a valid input into a text input and then subsequently enters an invalid input, a validation error is shown:

![](http://i.imgur.com/OzgOuZk.png)

This is the behaviour I expect and all is well up until now. 

*However*, when you check a required checkbox input and then subsequently uncheck the same input, no validation error is shown.

I made a JSFiddle to better demonstrate the problem: http://jsfiddle.net/hkqu29eg/

One solution I found is to hook into the `change` event using jQuery like this:

```javascript
$("#terms").on("change", function () {
  $(this).valid();
});
```
It does not feel right to have to do this for checkboxes but not text fields. Am I missing something? I hope there is a native solution.

Thank you :smile: and keep up the good work!

**Comment by jzaefferer** [comment]
If you could look into the cause for this issue and send a pull request, I can review and merge it. Otherwise this is very unlikely to get addressed. Sorry.

**Comment by alexbooker** [comment]
All good m8

**Comment by alexbooker** [comment]
I am not likely to pursue this but at least now there is some documentation surrounding the "problem".
