### ISSUE TITLE
Documentation issue: no  'remote' demo

### ISSUE THREAD

**Issue by funderburkjim** [jzaefferer/jquery-validation#1479]
I came across your plugin in the 'javascript-jquery missing manual' book.  When discussing the 'remote' method,  the text gave a link to a working demo.  However, this link resolved to the jquery-validation home page.  When I search the jquery-validation documentation for 'remote', I again found two 'demo links' that also resolve only to the jquery-validation home page.

It would be helpful to have links updated.  Specifically,  it would be useful to see a working example of the php server program.

**Comment by jzaefferer** [comment]
I've fixed the links, but currently can't deploy the changes. You can find the two demos here:

- http://jqueryvalidation.org/files/demo/milk/
- http://jqueryvalidation.org/files/demo/marketo/
