### ISSUE TITLE
Jquery Validation Additional Pattern method stops validation of other fields when it fails

### ISSUE THREAD

**Issue by fourthmeal70** [jzaefferer/jquery-validation#1480]
When using the Pattern method from the additional methods and it fails the validation, it stops the list of errors from being generated and shows only the single error. 

To reproduce:
http://jsfiddle.net/07jm89wp/4/
In the jsfiddle provided, clicking submit on an empty form generates a list of all errors at the top of the form. Clear the form and enter '123' in the first or last name fields so that it fails the pattern validation, only a single error is shown at the top of the form. 

Expected Result:
When entering '123' in the first or last name fields and the pattern validation fails, I should see a list of all errors with the appropriate error message at the top of the form.

**Comment by jzaefferer** [comment]
This is normal behaviour of the plugin - it only shows you errors for validated fields, and submit validates everything.
