### ISSUE TITLE
Request: add prebuilt jquery.validate.js to npm repository

### ISSUE THREAD

**Issue by sbussard** [jzaefferer/jquery-validation#1481]
As a gulp user who is hoping to use `npm` without `bower` (as an increasing number of people are doing), I would like to continue using this awesome jQuery plugin to validate my forms so that I don't have to rewrite a bunch of code or add extra steps to my build process. 

Criteria:
- A usable version of jquery.validate.js exists and is ready to use directly from the npm module without having to do an additional build step

It would be super awesome to have this change implemented. Let me know if I can help! Thanks!

**Comment by sbussard** [comment]
Added this to package.json instead `"jquery-validation": "git+ssh://git@github.com:jzaefferer/jquery-validation.git#1.13.1"`

**Comment by jzaefferer** [comment]
1.13.1 is published on npm, why would you need to install from GitHub?

**Comment by sbussard** [comment]
The one I'm getting from npm doesn't have the `dist` folder.

`package.json` (valid):

    "dependencies": {
      …
      "jquery-validation": "1.13.1"
    }

![screen shot 2015-05-13 at 2 34 34 pm](https://cloud.githubusercontent.com/assets/345018/7619323/8579cb14-f97d-11e4-8ca2-931421a18606.png)

**Comment by jzaefferer** [comment]
You're right, 89b507a1c127373759c395a0ba50abc5508ce100 fixes that, didn't yet make it into a release.
