### ISSUE TITLE
method errorsFor doesn't work for custom errorElement

### ISSUE THREAD

**Issue by phazei** [jzaefferer/jquery-validation#1485]
Sometimes there's a grouping of checkboxes or radio buttons where the automatic placement of error messages doesn't quite place it properly.
In that case I've always been able to manually place the label:

    <label id="element_id-error" class="error" for="element_id"></label>

And when showLabel is called, it will check to see if a error has already been placed with errorsFor, then will just add the errorsClass and message to the existing element.

Unfortunately when errorElement is used, then the errorsFor doesn't properly use it.  It currently is hard coded to search for:

    selector = "label[for='" + name + "'], label[for='" + name + "'] *";

If that were switched to:

    errorId = name.replace( /(\[|\])/g, "\\$1") + "-error",
    selector = this.settings.errorElement + "#" + errorId + ", " + this.settings.errorElement + "#" + errorId + " *";

It would properly handle the errorElement.

**Comment by kmd1970** [comment]
It appears your issue/solution is similar to mine. :+1:  see option 2. in https://github.com/jzaefferer/jquery-validation/issues/1494. I hope they fix this.

**Comment by phazei** [comment]
Does seem so, though it's important to escape [ and ] with \\ in case the name is like user[name]

**Comment by jzaefferer** [comment]
@kmd1970 @paladox would be great if one of you could put together a pull request for this, including the suggested fix and a unit test. For the replace you should use the pattern used elsewhere in the code already:

```js
.replace( /(:|\.|\[|\]|\$)/g, "\\$1")
```

**Comment by kmd1970** [comment]
Unfortunately I have never written a pull request before.

**Comment by jzaefferer** [comment]
Might be a good opportunity to learn! GitHub has some good articles: https://help.github.com/articles/using-pull-requests/

**Comment by phazei** [comment]
I could do the pull request, though I'm not sure what you're using for your unit tests. Not quite sure where to put that.

**Comment by jzaefferer** [comment]
The unit tests are written using QUnit, all relevant files are in the `test` folder. In this case, you could add something to https://github.com/jzaefferer/jquery-validation/blob/master/test/error-placement.js

**Comment by jzaefferer** [comment]
I'm unable to reproduce this issue. Please provide a [testpage that shows the issue](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md#reporting-an-issue). I can then reopen this.
