### ISSUE TITLE
About a proplem fo Demo

### ISSUE THREAD

**Issue by Maocily** [jzaefferer/jquery-validation#1487]
I am poor in Englinsh.But I try my best to description the proplem of Demo.
I had download this plus. this plus is easy to do form validate.but i had found a proplem!
 the index.html in Demo File Folder ,the second form in this index page can not to work! 
because the Jquery depend url had borken, In the lib file folder has not the jquery.js file! I had fixed the current url and the form  return to normal.
我的英文很差劲，但是，我会尽我最大的能力去阐述关于Demo的问题，我已经下载这个插件，这个插件做表单验证真的很简单。但是我发现了一个问题。 在demo 文件夹里面的index.html 第二个表单不能工作了。因为 依赖的Jquery 链接错了。在lib文件夹里面没有jquery.js这个文件，我修改这个正确的链接然后那个表单就能恢复正常了。

**Comment by jzaefferer** [comment]
Thanks for the report, but this doesn't indicate an issue with the validation plugin. To get help, I recommend to put together a test page using [jsfiddle](http://jsfiddle.net) or [jsbin](http://jsbin.com). Also a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) is going to be more helpful.
