### ISSUE TITLE
Email Validation is not working

### ISSUE THREAD

**Issue by tamaghna91** [jzaefferer/jquery-validation#1488]
Regular expression given in validate.min.js is not working while it seems to be 

/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

**Comment by Chandra0505** [comment]
E-mail proper is not working properly in my form.
The problem is that it is considering this email `sdfdsf@dsf`   as valid while it does not contain any dot( . ) or letter after it. Please check.

Thanks

**Comment by staabm** [comment]
Please read my comment above
