### ISSUE TITLE
Rule 'remote' complete response data basically unusable

### ISSUE THREAD

**Issue by rain01** [jzaefferer/jquery-validation#1491]
The issue is that right now only valid response for remote is true and false.
That leaves [remote 'complete' function](http://stackoverflow.com/a/16214487/1537657) almost useless. 
For example if I want to do this, it fails:
```javascript
$('#my_form').validate({
    onkeyup: false,
    rules: {
        username: {
            remote: {
                url: '/validate/',
                complete: function(resp, status){
                    if (status == 'success') {
                        var data = $.parseJSON(resp.responseText);
                        if (typeof data === 'object' && 'avatar' in data)  {
                            $('#avatar').attr('src', data['avatar']);
                        }
                        else {
                            $('#avatar').attr('src', 'default.png');
                        }
                    }
                }
            }
        }
    },
    messages: {
        username: {
            remote: 'This user does not exist.'
        }
    }
});
```
It fails because I can only send true or false from server.

I would love to see it more useful if I could send more data from server for the 'complete' function to use.
For example sending JSON from server:
```javascript
{
    valid: true,
    whatever_else_I_want: 'here is my data'
}
```
Where valid acts the way it acts right now validating if form is valid or not and with rest of the data you can do what ever you want in the 'complete' function making it much more useful.

PS: I could not find any documentation about remote 'complete' function so I posted stackoverflow link.

**Comment by jzaefferer** [comment]
Have you tried using the `dataFilter` option from [$.ajax](http://api.jquery.com/jQuery.ajax/)?

> A function to be used to handle the raw response data of XMLHttpRequest. This is a pre-filtering function to sanitize the response. You should return the sanitized data. The function accepts two arguments: The raw data returned from the server and the 'dataType' parameter.

**Comment by rain01** [comment]
I have but I couldn't figure it out how to use it for the life of me. I returned the response but couldn't figure out where it was sent since it never got to complete... complete still gave the same response.

**Comment by jzaefferer** [comment]
Can you share what you came up with?

**Comment by rain01** [comment]
I tried all kinds of different stuff but since it didn't work I deleted it. I'll add how I thought it should work.

```
username: {
    remote: {
        url: '/validate/',
        dataFilter: function(data, type) {
            // data = 'does not matter what I give from server'
            return true; // sending to complete
        },
        complete: function(resp, status) {
            // resp.responseText = 'does not matter what I give from server'... but I expect TRUE (from dataFilter)
            console.log(resp.responseText);
        }
    }
}
```

**Comment by jzaefferer** [comment]
I just tried the using `dataFilter` with `complete`. My server returned `{ "status": true }` and `{ "status": false }`, my remote method looked like this:

```js
remote: {
	url: "emails.action",
	dataFilter: function( data ) {
		return JSON.parse( data ).status;
	},
	complete: function( xhr ) {
		console.log( xhr.responseText )
	}
}
```

This would log the original response in the complete handler (unless cancelled, then it only gets `undefined`. And the validation plugin correctly shows the validity of the field.

For you that means you have to parse the data twice, once to produce the boolean for the validation plugin, once for whatever you need to accomplish in the complete handler.

**Comment by staabm** [comment]
It seems this question was resolved with the last comment.

**Comment by dmolesUC** [comment]
The `dataFilter` solution sort of works but seems a bit hacky — [per the docs](https://api.jquery.com/jquery.ajax/), it's supposed to be “a pre-filtering function to sanitize the response”, not a general transformation.

It also doesn't have access to the validation context or to the request (at least, not in any way obvious to this jQuery novice), so if for instance you want to compare the field value against some returned data structure, you have to extract the (possibly stale) form value again, as in this example of repurposing an existing autocomplete endpoint to find out whether a value exists:

```js
downloadForm().validate({
  rules: {
    collection_name: {
      required: true,
      remote: {
        url: findCollectionUrl,   // autocomplete endpoint, returns an array of possible matches
        data: {
          authenticity_token: $('input[name="authenticity_token"]').val(),
        },
        dataFilter: function (data) {
          try {
            let collectionName = $("#collection_name").val() // hope it's the same value we sent
            let collections = JSON.parse(data)
            let valid = collections.includes(collectionName) // check for an exact match
            return JSON.stringify(valid)
          } catch (e) {
            console.log(e)
            return "false"
          }
        }
      }
    }
  },
  messages: {
    collection_name: {
      remote: 'The collection "${1}" does not exist.'
    }
  }
})
```
