### ISSUE TITLE
Have documentation page in daux.io instead of wordpress

### ISSUE THREAD

**Issue by rain01** [jzaefferer/jquery-validation#1492]
It is just a suggestion but it would be so much easier to create and read the documentation if it was ran on [daux.io](http://daux.io/index) documentation generator.

Think about it. daux.io is actually built for docs and wordpress is built for... pretty much everything these days... and you know the old saying: "If it's good for everything, it's good for nothing".

Thank you for an amazing plugin.

**Comment by jzaefferer** [comment]
It sounds like a good idea, but converting all the existing documentation from the current format to daux.io isn't something I have the time to do. If someone (you?) would want to help with that it would be quite different.

**Comment by rain01** [comment]
I can start it... I don't know if I can do the whole thing at once though. Should I create a new repo or will you create one?

**Comment by jzaefferer** [comment]
A demo in your own repo would be good. Integrate some of the documentation overview and one or two of the API pages and deploy it on gh-pages (if possible). That should help a lot to figure out the remaining effort.

**Comment by jzaefferer** [comment]
PS: Your GitHub avatar is disgusting and completely inappropriate for this site.

**Comment by rain01** [comment]
> A demo in your own repo would be good. Integrate some of the documentation overview and one or two of the API pages and deploy it on gh-pages (if possible). That should help a lot to figure out the remaining effort.

I set up daux on my machine but haven't copied any documentation yet. I'll try to do it tonight.
Can't deploy it in gh-pages, it still needs php.

> PS: Your GitHub avatar is disgusting and completely inappropriate for this site.

I'm sorry you feel that way. I will change it right away.

**Comment by jzaefferer** [comment]
> I set up daux on my machine but haven't copied any documentation yet. I'll try to do it tonight.
Can't deploy it in gh-pages, it still needs php.

Okay, let me know how it goes.

**Comment by rain01** [comment]
I worked on it a little but I'm leaving for the long weekend and won't be able to work on it again until next week.
[jqueryvalidation-daux](https://github.com/web-seed/jqueryvalidation-daux)

**Comment by jzaefferer** [comment]
Nice. I just tried it locally. I can load the homepage, though not any other pages. I guess its failing to run the `.htaccess` rules? Have to find out again how to allow that file to run...

**Comment by staabm** [comment]
> Have to find out again how to allow that file to run...

you have to define `AllowOverride` in the `VirtualHost` or via a `Directory` config

**Comment by jzaefferer** [comment]
I do have `AllowOverride: All` for that virtual host. Looking at `/var/log/apache2/error_log`, there seems to be an issue with bad redirects:

```
[Fri Jul 10 11:31:25 2015] [error] [client ::1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://localhost:82/jqueryvalidation-daux/Documentation
```

Is this working for you?

**Comment by jedateach** [comment]
+1 I'm all for the docs being off wordpress and on something else.

https://readthedocs.org/ github pages are other alternatives.

**Comment by jzaefferer** [comment]
@jedateach thanks for the input. If you want to help, you could try what @rain01 has put together, maybe you can get it running. If not, help us figure out what's broken.

**Comment by staabm** [comment]
Content already is on github and everyone can contribute
