### ISSUE TITLE
Duplicate error messages when using bootstrap popovers on inputs and non label errorElements.

### ISSUE THREAD

**Issue by kmd1970** [jzaefferer/jquery-validation#1494]
I am using jquery validate with bootstrap 3 popovers. Any input with a popover defined produces multiple duplicate error messages after validation (when the input loses focus). 

I found out that both jquery validate and bootstrap 3 popovers are using the `aria-describedby` attribute. However, the popover code is overwriting the value written by jquery validate into that attribute.

Using `errorElement:'label'` or omitting this line works because on line 825 of jquery.validate.js, `label` is hard-coded as a default error element selector.

I found two ways to fix this issue:

1. Replace all `aria-describedby` attributes with another attribute name like `data-describedby`. 
or
2. Add the following code after line 825 in jquery.validate.js. 

```javascript
if ( this.settings.errorElement != 'label' ) { 
  selector = selector + ", #" + name.replace( /\s+/g, ", #" ) + '-error'; 
 }
```
Seems to me that any other JS code using `aria-describedby` on an input will have the same conflict.

**Comment by jzaefferer** [comment]
This sounds like a bug in bootstrap popover, it shouldn't overwrite the existing `aria-describedby` attribute.
