### ISSUE TITLE
Fields with all spaces still considered empty

### ISSUE THREAD

**Issue by gnomehub** [jzaefferer/jquery-validation#1498]
I'm having issues with validation considering fields with only spaces to be empty regardless. I setup an example with a maxlength attribute of 3. It works in most cases, but if you put in 4 spaces it doesn't seem to catch that.

http://jsfiddle.net/59k21h0p/

Looking at this blog post: http://lagod.id.au/blog/?p=514 it seems to indicate that the optional method is designed to say if the field is empty or not.

Looking at what it returns:
return !$.validator.methods.required.call( this, val, element ) && "dependency-mismatch";

caused me to look at the required method which returns "return $.trim( value ).length > 0;"

Is there a reason it's returning trim instead of just "return value.length > 0;"? Taking out the trim call causes it to treat spaces as being non-empty and fixes my validation issues.

**Comment by gnomehub** [comment]
Looking at this blog post: http://lagod.id.au/blog/?p=514 it seems to indicate that the optional method is designed to say if the field is empty or not.

Looking at what it returns:
return !$.validator.methods.required.call( this, val, element ) && "dependency-mismatch";

caused me to look at the required method which returns "return $.trim( value ).length > 0;"

Is there a reason it's returning trim instead of just "return value.length > 0;"? Taking out the trim call causes it to treat spaces as being non-empty and fixes my validation issues.

**Comment by jzaefferer** [comment]
I think originally the idea here was to not allow fields to pass the required rule when they're effectively still empty. Originally the `$.trim` call was applied for (almost) all rules, which caused various issues as well. I guess its time to just retire it completely.

**Comment by usb248** [comment]
I find it a pity to remove $.trim. For example, if i set required rule, i enter one space and the input is consider valid... 
I found this plugin really good and successful, but now I 'll have to find something else ...

**Comment by jzaefferer** [comment]
@usb248 if that is enough to make you look for an alternative, you weren't particularly committed in the first place, eh? Also, every alternative will have small details that don't exactly match your expectations, so good luck with that.
