### ISSUE TITLE
number validation does not support scientific notation

### ISSUE THREAD

**Issue by samyarbid** [jzaefferer/jquery-validation#1502]
Using the number validation method decimals using the scientific notation are rejected. For example, submitting "3.402823e+38" is invalid.

Currently the regex for a "number" is:

    /^(?:-?\d+|-?\d{1,3}(?:,\d{3})+)?(?:\.\d+)?$/

Consider using the following:

    /^(?:-?\d+|-?\d{1,3}(?:,\d{3})+)?(?:\.\d+)?(?:[Ee]\+\d+)?$/

**Comment by jzaefferer** [comment]
I recommend you write a custom validation method to capture that extended regex. The number method as-is is pretty simple and I'd like to keep it that way.

**Comment by staabm** [comment]
Agree with @jzaefferer most apps even won't want that scientific notations.

In those use-cases where you really want users to input such numbers, create a custom validator for it.
