### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: label[for='days[]'], label[for='days[]'] *, #days[]-error

### ISSUE THREAD

**Issue by albert28** [jzaefferer/jquery-validation#1504]
Hi :D, the first time I validate if, at least, there is one checkbox selected, the form validator works ok. Nonetheless, the second time I keep getting this error no matter if the checkbox is selected or not.
 
Uncaught Error: Syntax error, unrecognized expression: label[for='days[]'], label[for='days[]'] *, #days[]-error

Here's my HTML:
```html
<div class="checkbox-list">
 <input type="checkbox" class="days" name="days[]" />Mon
 <input type="checkbox" class="days" name="days[]" />Tue
 <input type="checkbox" class="days" name="days[]" />Wed
</div>
```

Here's my Javascript inside form.validate
```javascript
'days[]': {
 atLeastOneChecked: true
}
```
And here's my Javascript inside jQuery.validator.addMethod
```javascript
jQuery.validator.addMethod("atLeastOneChecked",function(value, element, params) {
 var selectedDays=($('.days:checked').size());
 if (selectedDays>0) return true;
 else return false;
}, "Please, select one day at least");
```

**Comment by jzaefferer** [comment]
I can't reproduce this. Can you test with the code in master in this git repository? At [testpage that shows the issue](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md#reporting-an-issue) would also help. I can then reopen if it persists.

**Comment by albert28** [comment]
Thank you, but I already solved the problem. :)

**Comment by vierkantemeter** [comment]
Hi Albert28, I'm having the exact same problem. Do you remember how you fixed this?

**Comment by albert28** [comment]
Hi, vierkantemeter.  Notice I changed "days[]" to simply "days" in HTML and Javascript.

```html
<div class="checkbox-list">
 <input type="checkbox" class="days" name="days" />Mon
 <input type="checkbox" class="days" name="days" />Tue
 <input type="checkbox" class="days" name="days" />Wed
</div>
```

```javascript
jQuery.validator.addMethod("atLeastOneChecked",function(value, element, params) {
   var selectedDays=($('.days:checked').size());
   return (selectedDays >0);
}, "Please, select one day at least");
```

```javascript
rules: { 
   days: { //this references input[name=days]!
      atLeastOneChecked: true
   }
}
```

**Comment by vierkantemeter** [comment]
Thank  you Albert!
- Michèlle

**Comment by staabm** [comment]
Fixed with https://github.com/jzaefferer/jquery-validation/commit/c604e510b7fcb4a8140541450ccb03d86f177e3c
