### ISSUE TITLE
Customizable date format support

### ISSUE THREAD

**Issue by oguzzkilic** [jzaefferer/jquery-validation#1505]
Hello,

Why only mm.dd.yyyy format is excepted while doing date control? Date format of some countries is like dd.mm.yyyy and one-way date control causes problems in use. In addition, it causes extra coding.

```javascript
return this.optional( element ) || !/Invalid|NaN/.test( new Date( value ).toString() );
```

Problem occurs because the value obtained from the input is compared with the date method on the code line above. I recommend you to support customizable date format because it will be easier and more comfortable for those who has to create extra solution.

Warm Regards

**Comment by staabm** [comment]
There are several Date plugins for the different formats, see https://github.com/jzaefferer/jquery-validation/tree/master/src/additional

**Comment by oguzzkilic** [comment]
Thanks for helping me @staabm
