### ISSUE TITLE
Should a good idea split this project?

### ISSUE THREAD

**Issue by vmariano** [jzaefferer/jquery-validation#1506]
Hi. I used this plugin in a couple of projects and help me to save lot of time. Thanks.

Very often in my the projects (with exception of ´required´) the build-in rules are not required, and i must add a lot of custom rules.

So, I think that should be a good idea split this project in 2. one with the implementation of the form validation core. And other repo/lib/etc (whatever) with plugins required to the project.

If is this is planed for the  next versions, ignore this issue.

Thanks.

**Comment by tsjoberg** [comment]
+1 - especially if you only use 1 or 2 methods and dont need the other built-in methods

**Comment by jzaefferer** [comment]
This isn't planned. I'm happy to review and merge pull requests to move methods from `core.js` to `additionals`, for example `creditcard` really shouldn't be in core.
