### ISSUE TITLE
Document data-rule-[rule] (was: Rules from data-attributes not working)

### ISSUE THREAD

**Issue by thany** [jzaefferer/jquery-validation#1511]
Rules in data-attributes don't work, and they never will. The plugin expects, for example, a data-attribute `data-ruleMinlength`, but in jQuery's data collection, this data item will never exist, because data-attributes (possibly all attributes) are lowercased.

In the current release 1.13.1, on line 1007:
```
value = $element.data( "rule" + method.charAt( 0 ).toUpperCase() + method.substring( 1 ).toLowerCase() );
```
Change this to:
```
value = $element.data( "rule-" + method );
```
And expect data-attributes like `data-rule-minlength`. Fixed.
It doesn't matter to change the expected html, because it currently doesn't work anyway.

**Comment by staabm** [comment]
could you provide a jsfiddle, or even better a failing unit test?

**Comment by staabm** [comment]
I played a bit arround and came to:
http://jsfiddle.net/bj9szdu1/

it seems we need `value = $element.data( "rule-" + method.toLowerCase() );`

**Comment by jzaefferer** [comment]
> The plugin expects, for example, a data-attribute data-ruleMinlength

No, it expects `data-rule-minlength`, which works fine: http://jsfiddle.net/v6dpyrd5/

Or am I missing something?

**Comment by jzaefferer** [comment]
Can reopen if something else comes up

**Comment by thany** [comment]
Put it in the documentation properly then. Currently, I could find a word about data-attributes, so I dove into the source code. The source forcibly detects for `data-ruleMinlength`, so I've put `data-ruleMinlength` on my element, which wouldn't work.

I had no way of knowing that `data-ruleMinlength` is magically translated into `data-rule-minlength` by anything. And if that's the case anyway, why not change that line I mentioned to a much more readable and consistent way to getting those data attributes?...

I don't see any reason not to remove confusing code.

**Comment by staabm** [comment]
I agree we could document it better. PR welcome

The conversation of keys regarding camel-casing is done by jquery:
http://api.jquery.com/data/#data-html5

**Comment by jzaefferer** [comment]
Somewhat similar to #976.

**Comment by thegde** [comment]
Since conversion of camelCase to hyphen (camel-case) has become a kinda standard (even in $.data() and in angularJS) and html5 recommends small letters in tags and attribs, I would be nice to support converting camelCase to camel-case in data rule.
i.e. 
conversion of current line (line 1007, v1.13.1)
"value = $element.data( "rule" + method.charAt( 0 ).toUpperCase() + method.substring( 1 ).toLowerCase() );"
to 
"value = $element.data( "rule" + method.charAt( 0 ).toUpperCase() + method.substring( 1 ));" 
should work ?

**Comment by staabm** [comment]
@thegde as pointed out above, jQuery will already take care of that.

Or did I miss a case?

**Comment by thegde** [comment]
@staabm I am trying to add and slightly update the good work you have already done.

if  "value = $element.data( "rule-" + method.toLowerCase() );" is used,
the methods like "myRange" wont get converted to "rule-my-range", wouldn't it will be "rule-myrange" ? whereas usually we expect it to be treated as "rule-my-range" ? 

Please correct me if I am wrong.

**Comment by staabm** [comment]
> ... methods like "myRange" wont get converted to "rule-my-range", wouldn't it will be "rule-myrange" ? whereas usually we expect it to be treated as "rule-my-range" ?

Yes thats correct. As I understood it so far the extected format `data-rule-[lowercase-rule-name]`. Supporting camel to dashed case in the rulename would be a separate feature request I guess.
@jzaefferer opinions?

**Comment by thegde** [comment]
Yes I agree. Would be glad to see it.
May be have to keep existing format too, to avoid breaking changes!


Regards
Tejasvi
