### ISSUE TITLE
ASP CDN links not working on main site

### ISSUE THREAD

**Issue by Jrizzi1** [jzaefferer/jquery-validation#1516]
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js

**Comment by jzaefferer** [comment]
Thanks for the report. I've notified them more than a week ago and didn't want to keep track of that, along with some infrastructure issues that make site updates difficult. You can still use 1.13.1 from the ASP CDN, or switch to jsdelivr. Or wait a little longer.
