### ISSUE TITLE
Bounces to top of form after clicking on checkbox, keyboard covers Submit, can't get out

### ISSUE THREAD

**Issue by jamminjames** [jzaefferer/jquery-validation#1520]
I'm not sure if this is caused by jquery-validation, but it started happening after I set it up. After filling out a couple fields, and then clicking on a checkbox, it keeps wanting to bounce up to the top of the form, and the device keyboard won't clear, so there's no way to get down to the Submit button. 

How can I make the keyboard clear after clicking on something that doesn't need a keyboard?

Thanks!

**Comment by jzaefferer** [comment]
Thanks for the report, but this doesn't indicate an issue with the validation plugin. To get help, I recommend to put together a test page using [jsfiddle](http://jsfiddle.net) or [jsbin](http://jsbin.com). Also a post on [the forum](http://forum.jquery.com/using-jquery-plugins) or [StackOverflow](http://stackoverflow.com) is going to be more helpful.
