### ISSUE TITLE
"aria-describedby" being filled with repeating values. Cause: "errorID" being stored as escaped string

### ISSUE THREAD

**Issue by pristinesource** [jzaefferer/jquery-validation#1523]
In /src/core.js starting at line 799 in version 1.14.0

It is storing the string errorID in the attribute as an escaped sting, so it will never match the Regex later when it is queried again.

Here is the code in question:

```javascript
                    errorID = error.attr( "id" ).replace( /(:|\.|\[|\]|\$)/g, "\\$1");
                    // Respect existing non-error aria-describedby
                    if ( !describedBy ) {
                        describedBy = errorID;
                    } else if ( !describedBy.match( new RegExp( "\\b" + errorID + "\\b" ) ) ) {
                        // Add to end of list if not already present
                        describedBy += " " + errorID;
                    }
                    $( element ).attr( "aria-describedby", describedBy );
```
		    

Here is my suggested code fix:

```javascript
                    errorID = error.attr( "id" );
                    var escaped_errorID = errorID.replace( /(:|\.|\[|\]|\$)/g, "\\$1");
                    // Respect existing non-error aria-describedby
                    if ( !describedBy ) {
                        describedBy = errorID;
                    } else if ( !describedBy.match( new RegExp( "\\b" + escaped_errorID + "\\b" ) ) ) {
                        // Add to end of list if not already present
                        describedBy += " " + errorID;
                    }
                    $( element ).attr( "aria-describedby", describedBy );
```

**Comment by staabm** [comment]
Could you provide a jsfiddle demonstrating the error - or even better a failing unit test?

**Comment by pristinesource** [comment]
Here is the JSfiddle.

http://jsfiddle.net/oyg6ec6g/4/

**Comment by pristinesource** [comment]
Just to note, this setup is a duplicate of the "Microsoft Unobtrusive validation support library for jQuery and jQuery Validate" setup/configuration. Which I am certain is used very widely.

https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation/

**Comment by jzaefferer** [comment]
@pristinesource thanks for the report and the jsfiddle. I've been trying to fix these issues for several releases now, and apparently keep failing. Could you look into writing a unit test that captures what you have in your jsfiddle? Once that works, the suggested fix is much easier to verify and the test will prevent further regressions.

**Comment by jzaefferer** [comment]
See also #1458

**Comment by Nettsentrisk** [comment]
This is basically the same problem as noted in #1587.
