### ISSUE TITLE
question: how to add localization message for validator.addmethod

### ISSUE THREAD

**Issue by shyandsy** [jzaefferer/jquery-validation#1524]
For the internal validator, the localization can be implemented by load the  message file.
https://github.com/jzaefferer/jquery-validation/tree/master/src/localization 

Question is how to add localization for $.validator.addMethod

```
$.validator.addMethod("digital_letter_underline",
        function(value, element) {
            return /^[a-zA-Z0-9_]$/.test(value);
        },
        "please input a valid password"              //it is english method
    );
```

**Comment by staabm** [comment]
@shyandsy `$.validator.addMethod()` supports a 3rd arg, namely the message. You can provide whichever string you like, whether it is localized or not.

In case you added your localizations to a file like those found in https://github.com/jzaefferer/jquery-validation/tree/master/src/localization you can just use `$.validator.messages.YourDefinedKey` to pass them as a 3rd arg.
