### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined jquery.validate.js:863

### ISSUE THREAD

**Issue by fenixphp** [jzaefferer/jquery-validation#1527]
Hey that's found a small problem:
- The error occurs when calling `validator.showErrors({key : value});`

**Comment by staabm** [comment]
Please provide a reduced jsfiddle which shows the problem

**Comment by fenixphp** [comment]
http://jsfiddle.net/7r27sgzo/3/

**Comment by jzaefferer** [comment]
You're calling `showErrors` with invalid arguments:

```js
validator.showErrors({
  field : value
});
```

You don't have an input with a name attribute of `field`.
