### ISSUE TITLE
Can't download from "files on Microsoft's Ajax CDN"

### ISSUE THREAD

**Issue by addice** [jzaefferer/jquery-validation#1529]
Hi,

Looks like the link is broken, have to download from the jsDelivr CDN instead.

Please check,
![screenhunter_1376 jul 20 10 29](https://cloud.githubusercontent.com/assets/5733642/8769212/50349a06-2eca-11e5-91dd-01021cbe3838.jpg)

**Comment by jzaefferer** [comment]
I've pinged my Microsoft contacts about the update. Can't do more than that.

**Comment by jzaefferer** [comment]
It worked! Files are available now.

**Comment by endomorphine** [comment]
@jzaefferer hey, can you ping them again? [https://www.asp.net/ajax/cdn/jquery-validate/cdnjqueryvalidate1160]
