### ISSUE TITLE
min/max rules are applied to text fields implicitly

### ISSUE THREAD

**Issue by eidng8** [jzaefferer/jquery-validation#1532]
I've just met a weird problem. I've got something like this:

```html
<input class="infoTableInput2" name="owner_name" type="text" id="owner_name" value="">
```

and the rule:

```javascript
$('#store_form').validate({
    rules : {
        owner_name: {
            required: true
        }
    },
    messages : {
        owner_name: {
            required: '{$lang.owner_name_required}'
        }
    }
});
```

every time I tried to enter something to the field, an error message pops up `Please enter a value greater than or equal to 0.`. But as you can see above, I've not added any extra rule to the element.
After debugging a bit, I've found that it's because the validator loops through all available methods in the normalizer. And the line 981 will always be true while evaluating the min/max method:

```javascript
if ( /min|max/.test( method ) && ( type === null || /number|range|text/.test( type ) ) )
```

**Comment by staabm** [comment]
Please provide a jsfiddle to re-produce
