### ISSUE TITLE
E-mail validation

### ISSUE THREAD

**Issue by pinta83** [jzaefferer/jquery-validation#1537]
E-mail validates an e-mail address without the TDL...
For example "a@a" will validate, and that can not be a valid address because it's missing the TDL name....

If it were "a@a.a" then it theoretically could....

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

**Comment by staabm** [comment]
see https://github.com/jzaefferer/validation-content/pull/14/files for how to use a custom email pattern

**Comment by pinta83** [comment]
Okay, clear enought.
btw. very quick reply, ty :+1:

**Comment by staabm** [comment]
you are welcome. feel free to open new issues in case you hit bugs/problems.
