### ISSUE TITLE
Cannot read property 'call' of undefined.  Exception occurred when checking element XXXX, check the 'onfocusout' method.

### ISSUE THREAD

**Issue by Schwoebel** [jzaefferer/jquery-validation#1538]
```javascript
var addCardForm = $( "#addNew" );
 addCardForm.find('input[name="PersonalId"]').rules("add", {
        onfocusout: function(element, event){
            console.log(element);
        }
  });
```

```html
<form style="padding-top:10px;" class="" id="addNew" action="/card/addNewCard">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div class="form-group">
                                <label for="pn">PersonalId</label>
                                <input type="text" placeholder="ÅÅÅÅMMDDXXXX" id="pn" class="form-control" name="PersonalId" value="">
                            </div>
                        </div>
</div>
</form>
```

Anytime I focus out of the field I get the error message "Cannot read property 'call' of undefined.  Exception occurred when checking element pn, check the 'onfocusout' method.

Am I doing something wrong? Because I feel like this is an issue.  I am following the documentation.

**Comment by staabm** [comment]
the `.rules` method is only available on the `validator` object, not on any `DOMElement` jQuery can `find`

**Comment by staabm** [comment]
Are you sure jquery-validate is already loaded at this point in time?

**Comment by Arkni** [comment]
>I know this issue is old, but I wanted to answer it.

The rules method used only to add your desired rules to the element, not to override the onfocusout.

See http://jqueryvalidation.org/rules/ for how to use the `rules` method.

**Comment by staabm** [comment]
Will close this issue now. Feel free to discuss it further. In case we get to a point where something need to be fixed in jquery-validate-src we can re-open it again
