### ISSUE TITLE
Modification to phoneUS regex

### ISSUE THREAD

**Issue by ledge23** [jzaefferer/jquery-validation#1539]
The project I'm working on requires extensions to be allowed as entries, so I've been hacking on [this regex](http://snipplr.com/view/5407/us-phone-number-with-extension-flexible/) to make it work. So far so good, except I can't get the last unit test to pass unless I force a space between the extension identifier and the extension numbers.

Thoughts? Maybe useful enough?

https://regex101.com/r/mG2bC4/4#javascript

**[EDIT]** [This version](https://regex101.com/r/mG2bC4/5#javascript) passes all unit tests, but doesn't allow for a space-delimited extension (e.g. 209 209 2009 209 doesn't work, whereas 209 209 2009 ext209 -or- ext 209 does)

**Comment by staabm** [comment]
Please provide some example numbers which are valid and dont work atm.

I will re-open the issue in case you provide some.
