### ISSUE TITLE
ErrorPlacement is called without validator scope

### ISSUE THREAD

**Issue by dave-newson** [jzaefferer/jquery-validation#1542]
Unlike all the other functions (highlight, unhighlight and showErrors), errorPlacement is called without the scope of the activate validator.

https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L786
```javascript
this.settings.errorPlacement( place, $( element ) );
```
Suggest this is changed to:
```javascript
this.settings.errorPlacement.call( this, place, $( element ) );
```

Again this is because I'm trying to crowbar in additional functionality, but there are very few locations which allow me to do this.

Is there any reason the scope isn't given to errorPlacement? I can't see one besides "you're not supposed to mess with the internals from here".

**Comment by staabm** [comment]
@dave-newson not sure what you mean by the "scope of the activate validator". the validator is attached to the form which is available per native js properties from every element.

`element.form` returns the HTMLFormElement associated with your element and `$form.data('validator')` will return the validator instance for this form.

Does this work for you?

**Comment by dave-newson** [comment]
@staabm that does work. Sorry for my terminology - too much time spent talking to Angular people.

It still seems an oddity that "this" in `errorPlacement` is different to `this` in `showErrors`, `highlight` and `unhighlight`, but if I can still get there via `$(element).data('validator')` then I'm not too fussed.

**Comment by staabm** [comment]
oh, now I see what your point is.

It seems like we have this discrepancy in several callbacks[1], so we need to discuss for which callbacks it makes sense etc.

[1] https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L826
