### ISSUE TITLE
Use of patterns causes form to submit without proper validation in some cases

### ISSUE THREAD

**Issue by svetoslavgenov** [jzaefferer/jquery-validation#1544]
Demo: http://jsbin.com/yoboliviya

1. Click the form when empty, errors will appear on both fields
2. Then fill only the second field with some random 10 characters
3. Click submit, it will go forward disregarding the error on the first field

The form got submited without proper validation because of the asterix * in the second input pattern.
Chrome 44.0.2403.130 used

**Comment by staabm** [comment]
The pattern in the 2nd field doesnt make sense.

In case you want to match a literal `*` char , you need to escape it, because it is a regex meta character...

**Comment by svetoslavgenov** [comment]
Thank you for your explanation, now I got it.
