### ISSUE TITLE
Check field by option from select

### ISSUE THREAD

**Issue by gibson** [jzaefferer/jquery-validation#1545]
When i manually checking filed by selected option - other fields not checking

example http://jsfiddle.net/f3jt1vje/  -  on submit not checking name field

**Comment by jcspader** [comment]
Your method 'check' is not dynamic.
Maybe you can use the method required with function parameter
http://jqueryvalidation.org/category/methods/#example:-makes-“parent”-required-only-if-age-is-below-13

```javascript 
$.validator.addMethod(
        'check',
    function (value) {
        var valid = $('#testing').validate().element('#test' + value),
            filled = !! $('#test' + value).val();
        return filled && valid;
    },
        'test is wrong');
```

**Comment by staabm** [comment]
No response, closing. Feel free to add further information, will re-open the issue then..
