### ISSUE TITLE
Enable - Disable button based on form being valid

### ISSUE THREAD

**Issue by tundayy** [jzaefferer/jquery-validation#1548]
Please can some give me an example of how to use the validation plugin such that if the form is valid the button is enabled?

**Comment by Kellamity** [comment]
I have a custom script that runs afterJQueryValidate (and at other times) that gets each element on the form, then looks through and checks if any of them are invalid.  If yes, button stays off, if no, button comes on.

It works but if someone has a better idea I'd love to hear about it!

**Comment by staabm** [comment]
See e.g. https://forum.jquery.com/topic/validate-event-hook-for-validation-success-failure
