### ISSUE TITLE
Email validation not required domain

### ISSUE THREAD

**Issue by gadeawzuki** [jzaefferer/jquery-validation#1560]
Hi.

If we add rule for field email, it does not work well.
Email test@test is passed a good valid, domain is not required.

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

see https://github.com/jzaefferer/validation-content/pull/14/files for how to use a custom email pattern
