### ISSUE TITLE
Is it me or is it a bug?

### ISSUE THREAD

**Issue by Lukaszczrz** [jzaefferer/jquery-validation#1564]
Hi,

I am using jQuery Validation plug-in in my two step registration form.

On "First Step" I'm checking username and email availability with remote function.

Here is the bug (or me!):
- If username exist in database and email is not, when I click "next" button the script letting me go to second step. (It shouldn't because username exist!)

but;

- If username not exist and email is exist in the database, It's stops me there and warns me email is exist. So it's working.

- If both username and email exist in the database, also stops me. So again working.

Here is code I'm using;

**HTML:**

    <div class="tab-content">
    	<p>Page.</p>
		<form class="form-horizontal" onsubmit="return false;" action="" method="post" id="myform">
    
		<div id="stepusername">
				
				<p>This is step 1</p>
      		
       			<input type="text" class="form-control" id="username" name="username" placeholder="Username" autocomplete="off"><br>
      			
				<input type="email" class="form-control" id="email" name="email" placeholder="email" autocomplete="off"><br>  			
       			
      			<p><a class="btn btn-primary next">Go to step 2</a></p>  
      			          
     	</div>
     	
     	<div id="stepemail">

				<p>This is step 2</p>
				     	
      			<input type="password" class="form-control" id="password" name="password" placeholder="password" autocomplete="off"><br>
       			
       			<input type="password" class="form-control" id="conf_password" name="conf_password" placeholder="password" autocomplete="off"><br>   			
     			
      			<input class="btn btn-success next" type="submit" value="Finish">
						
     	</div>
     	
		</form>
		
		<div id="stepsuccess">
		
		<p>Show result here.</p>
		
		</div>
		
		
    </div>

**Java Script:**

	<script type="text/javascript">
		// jQuery.validate script, does client-side validation
		$(document).ready(function(){
			$(".next").click(function(){
				var form = $("#myform");
				form.validate({
					errorElement: 'div',
					errorClass: 'formerror',
					highlight: function(element, errorClass, validClass) {
						$(element).closest('.form-group').addClass("has-error");
					},
					unhighlight: function(element, errorClass, validClass) {
						$(element).closest('.form-group').removeClass("has-error");
					},
					rules: {
						username: {
							required: true,
							remote: { 
							url: "check-username.php",
							async: false,
							type: "post", }
                  		},															
						password : {
							required: true,
						},
						conf_password : {
							required: true,
							equalTo: '#password',
						},
						email: {
							required: true,
							remote: { 
							url: "check-email.php",
							async: false,
							type: "post", }
                  		},
					
					},
					
					messages: {
						username: {
							required: "Username required",
							remote: "Taken username.",
						},											
						password : {
							required: "Password required",
						},
						conf_password : {
							required: "Password required",
							equalTo: "Password don't match",
						},
						email: {
							required: "Email required",
							remote: "Taken email.",
						},							
						
					}
						
				});
				
				if (form.valid() === true){
					if ($('#stepusername').is(":visible")){
						current_fs = $('#stepusername');
						next_fs = $('#stepemail');
					}else if($('#stepemail').is(":visible")){
						current_fs = $('#stepemail');
						next_fs = $('#stepsuccess');
					}
					
					next_fs.show(); 
					current_fs.hide();
				}

			});
			
		});
	</script>

Also jsFiddle if you like to see: http://jsfiddle.net/noptpece/

**Comment by Konrud** [comment]
What version of the jquery-validation do you use?

**Comment by Arkni** [comment]
Just tested your code and it's working as expected with no problem.
http://jsfiddle.net/Arkni/sv97jc4p/

**Comment by staabm** [comment]
@Lukaszczrz please provide a jsfiddle demonstrating the error. I will close this ticket now, but feel free to discuss it further. we can re-open after you found a way to reproduce the error.
