### ISSUE TITLE
validations on nested form fields

### ISSUE THREAD

**Issue by forever-ram** [jzaefferer/jquery-validation#1565]
Hi everyone, 
Is it possible to apply jquery validation on nested form fields in rails?
I've search a lot, but not getting any solution for my problem.

Please help me if it is possible to do and how I can do it?

**Comment by staabm** [comment]
I guess you mean nested forms instead of nested fields?

If so, please see https://github.com/jzaefferer/jquery-validation/issues/1311

If I am wrong please reply here, so I will re-open the issue after you described your question in more detail. Thanks.

**Comment by forever-ram** [comment]
No, I'm not talking about the nested form, my problem is for nested fields.
if you are familiar with form helper `nested_form_for` or view helper `f.fields_for` you will better understand my problem.

Here is the  example
in my model `user.rb`

    class User < ActiveRecord::Base
        has_many :photos, dependent: :destroy
        accepts_nested_attributes_for :photos
    end

in my controller `users_controller.rb`

    def new
        @user = User.new
        3.times @user.photos.build
    end 

in my rails view `form.html.erb`

    <%= form_for @user, html: { class: "form-horizontal", role: 'form' } do |f| %>
        <%= f.text_field :name %>
        <%= f.fields_for :photos do |pf| %>
            <%= pf.text_field :order_no %>
            <%= pf.file_field :avatar %>
        <% end %>
    <% end %>

html view of the above rails form

    <form action="/users" class="form-horizontal" role="form">
        <input type="text", name="user[name]">

        <input type="text" name="user[photos_attributes][0][order_no]">
        <input id="user_avatar" class="hide valid" type="file" name="user[photos_attributes][0][avatar]">

        <input type="text" name="user[photos_attributes][1][order_no]">
        <input id="user_avatar" class="hide valid" type="file" name="user[photos_attributes][1][avatar]">

        <input type="text" name="user[photos_attributes][2][order_no]">
        <input id="user_avatar" class="hide valid" type="file" name="user[photos_attributes][2][avatar]">
    </form>

photos fields are dynamic, I mean if we provide button/link for add more photos so there will be more then 3 nested fields

I need to validate that `order_no` fields should have only digits and `avatar` fields should have only image and require true.

Please let me know how I can do this?

**Comment by staabm** [comment]
you could query the DOM for your elements and create the rules for your fields using `rules()`[1]

[1] http://jqueryvalidation.org/rules/

**Comment by forever-ram** [comment]
where I need to add these custom validation rules 
when I put like this

  form.validate({ 
    // other roles are here 
  });
  $('.user_photo_order_no').roles("add", {
      digits: true
  });
no any validation roles are working.

**Comment by staabm** [comment]
See the example on the url posted above. You add those rules after you initialised the validator. 

Its "rules" not "roles"

**Comment by staabm** [comment]
Closing because no feedback for a while

**Comment by arththakkar** [comment]
Facing the same issue. Queried the DOM and created the rules using class just like @forever-ram did, but it only works for the first set of nested_fields.
