### ISSUE TITLE
WRONG EMAIL VALIDATION

### ISSUE THREAD

**Issue by sahildeliwala** [jzaefferer/jquery-validation#1571]
email - "yc@hell" is accepted which I think should not be accepted. I think you are just checking as {text}{symbole}{text} which should be {text}@{text}.{text}.
If its not an issue please Ignore it ;)

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

see https://github.com/jzaefferer/validation-content/pull/14/files for how to use a custom email pattern
