### ISSUE TITLE
Populate customError?

### ISSUE THREAD

**Issue by Nettsentrisk** [jzaefferer/jquery-validation#1585]
With the standard error types, the form element's validity (ValidityState) will be updated automatically as usual. However, for custom validation rules, I see that validity.customError and validity.valid are not changed. Is there a conscious decision behind not doing this, or should it be done for browsers that support it?

I can see some situations where you might want to read off validity information directly from the element, and if there's a customError applied, then that should be reflected.

**Comment by staabm** [comment]
could you provide a small jsfiddle which demonstrates the issue in your use-case?

**Comment by staabm** [comment]
Closing because no response. Feel free to add a jsfiddle, we re-open the issue then..
