### ISSUE TITLE
Validate hidden field

### ISSUE THREAD

**Issue by kevinfilteau** [jzaefferer/jquery-validation#1590]
I use some script that hide fields to enhance the interface.

But hidden fields are not validated. It's there some settings or an easy way to made it works?

Thank

**Comment by Arkni** [comment]
You can set `ignore` option to empty string:
```js
$( form ).validate( {
    // Some options ...
    ignore: "",
    // Other options ...
} );
```

See http://jqueryvalidation.org/category/plugin/#ignore

**Comment by kevinfilteau** [comment]
Thanks you very much. Sorry I didn't see this setting!
