### ISSUE TITLE
ignore validating display:none div elements when submitting a page

### ISSUE THREAD

**Issue by Pathz88** [jzaefferer/jquery-validation#1595]
Hi all... i have my div structure like below. at a moment only one main div will be displayed. for other divs only parent div is display none and when i submit the page child elements don't support for ignore:":hidden". what should i do..?

--this is only hidden div part

div id="divDepartmentArea" runat="server" style="display: none" clientidmode='Static'
div class="marginTop"
asp:TextBox ID="txtFrom" runat="server" ClientIDMode="Static" data-required="true"asp:TextBox
asp:TextBox ID="txtTo" runat="server" ClientIDMode="Static" data-required="true"asp:TextBox
/div
/div"

**Comment by staabm** [comment]
Please provide a jsfiddle which demonstrates the problem

**Comment by staabm** [comment]
Closing because no response. Feel free to add a jsfiddle, we re-open the issue then..
