### ISSUE TITLE
Disable jquery validate on submit, but still run invalidHandler and submitHandler

### ISSUE THREAD

**Issue by bpromasmb** [jzaefferer/jquery-validation#1599]
*[Prior to opening this issue I have asked a [question](http://stackoverflow.com/questions/32909531/disable-jquery-validate-on-submit-but-still-run-invalidhandler-and-submithandle) regarding this on StackOverflow which generated some discussion]*

I have a form containing a dynamic (user-created) amount of input fields, some of which need to be validated. The amount of input fields can very likely get into the tens of thousands, and so when I click submit, if there is a large number of fields created, **jquery validate freezes up my browser for several seconds while it checks and marks my input fields as invalid**. 

This is bad and unnecessary since **I'm already marking my input fields upon creation** and on keyup, and then I have `invalidHandler` take care of alerting the user and then I do a bunch of stuff with my inputs in `submitHandler`.

What I want to do is something like this:

    $("#myForm").validate({
        onsubmit: false,
        onkeyup: function (element) {
            $(element).valid();
        },
        invalidHandler: function (event, validator) {
            //alert user, highlight invalid fields...
        },
        submitHandler: function (form) {
            //a bunch of stuff...
        }
    });

But when I try that and I click submit, the form straight up gets submitted, even if it has invalid fields, passing straight through both my handlers. I get it that it's because I'm not validating on submit, but I assumed that setting  `onsubmit: false` would simply prevent the plugin from **unnecessarily re-checking and re-marking already marked inputs**, while still running my handlers. How do I achieve this?

**Comment by staabm** [comment]
Let me ask first, how will a screen look like with tens of thousands of input fields and how does do you manage that the enduser knows what he is doing?

**Comment by bpromasmb** [comment]
Short answer is that I allow the user to hide and show fields as he or she pleases by toggling `display: none`

The long answer is that I am using the fancytree plugin to help the user generate something that later gets exported as a spreadsheet. So imagine something like [this](http://wwwendt.de/tech/fancytree/demo/index.html#sample-multi-ext.html) but with tons of nodes within folders within folders.

The enduser can keep track of what he's doing because he can collapse folders so only the section he's working on right now is visible. For instance, I could allow the user to have only one folder expanded at a time by collapsing sibling folders when another folder gets expanded to avoid giving him too much "cognitive load".

**Comment by bpromasmb** [comment]
Also, I worked around this issue by setting `onsubmit: false` and moving the code from within ´invalidHandler` and `submitHandler` to my submit button

**Comment by staabm** [comment]
Would it make sense to define a e.g. custom css selector which matches only relevant fields and validate only those?

> Also, I worked around this issue by setting onsubmit: false and moving the code from within invalidHandler and submitHandler to my submit button

Does that mean we can close this issue?

**Comment by bpromasmb** [comment]
I think so.

**Comment by dkniffin** [comment]
I'm running into this right now too. I think this should be an option for the validator. @bpromasmb Can you share the code you used to resolve this?

**Comment by dkniffin** [comment]
Nevermind. Found it. Here's the coffeescript version:

````coffeescript
$('form').validate
  showErrors: ->
    false
````
