### ISSUE TITLE
Trim white space

### ISSUE THREAD

**Issue by manishbathla** [jzaefferer/jquery-validation#1601]
Hi, if I press the space bar thrice, the plugin treats it 3 characters and validates it. Don't you think white space before any character or number should be trimmed?. Try it, hit space bar 3 times for minimum length required and it gets validated. Better option would be to trim white space at the start.

**Comment by staabm** [comment]
See duplicate issues and the response from Jörn to them:
https://github.com/jzaefferer/jquery-validation/issues/1354#issuecomment-67168988

**Comment by staabm** [comment]
I will close this issue, but feel free to discuss it further in case you dont agree

**Comment by Arkni** [comment]
@staabm 
I think of a solution that can be used in cases like this one, this solution rely on using a pre-validate event or a function (as an option) that can be used to change the value before validating a given field.

Your thoughts ?

**Comment by staabm** [comment]
@Arkni do you think we need more then the current submit-handler/onsubmit-option?

**Comment by staabm** [comment]
Yeah, actually we dropped it in the last release, see https://github.com/jzaefferer/jquery-validation/commit/2ad0ca82daf091fc692018b38e01e896fd304015

**Comment by Arkni** [comment]
Yes, I'm aware of that.

What I'm thinking is the ability to do something like this:
```js
$(".selector").validate({
    rules: {
        an_element: {
            required: true,
            othervalidator: true,
            // Transformer or another or better name
            transformer: function(element) {
                // Change/transforme the value of the element
                // And then return the transformed value
                return transformed_value;
            }
        }
    }
});
```

**Comment by staabm** [comment]
I am ok to have a transformation layer in jquery-validate. This should be discussed in a separate feature request/PR

**Comment by Arkni** [comment]
Created #1602
