### ISSUE TITLE
Adding transformation/normalization layer

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1602]
The user can change/transform the value of an element before validating the element in question. The transformed value will be then used by the associated methods instead of the real one.

I'm thinking of adding something like this:
```js
$(".selector").validate({
    rules: {
        an_element: {
            required: true,
            othervalidator: true,
            // Transformer or another or better name
            transformer: function(element) {
                // Change/transforme the value of the element
                // And then return the transformed value
                return transformed_value;
            }
        }
    }
});
```

**Comment by Arkni** [comment]
@staabm 
Can you delete our comments in issue-1601 , in order to let the thread clean ? and continue the discussion here

**Comment by Arkni** [comment]
@jzaefferer 
Can you please take a look at this, and give us your feedback ?
Do you agree with adding this layer to the plugin ?

**Comment by staabm** [comment]
I guess we should name this feature "normalizer" instead of transformer.

Or fan you think of wnuse case in which you actually transforms input into completely different values instead of just trimming spaces or stripping some special chars?

**Comment by Arkni** [comment]
> I guess we should name this feature "normalizer" instead of transformer.

Sounds good to me, as `normalizer` reflects more what we are about to do.

> Or fan you think of wnuse case in which you actually transforms input into completely different values instead of just trimming spaces or stripping some special chars?

A better example is the one I mentioned in [#1615 (comment)](https://github.com/jzaefferer/jquery-validation/issues/1615#issuecomment-149241665), As the `C:\fakepath\` is not added in Firefox and _may_ change in Chrome and Edge in the coming releases. So instead of patching the plugin, the user can use the code from the spec instead.

Another example, is when using the `url` method, this require the user to enter at least `//` as in `//google.com` or to input the full url `tld://google.com` where `tld = https?|ftp`. So we can check if the used used the TLD and the `//` is not add them so the element can pass the check:
```js
$( "form" ).validate( {
    rules: {
        file_input: {
            required: true,
            url: true,
            normalizer: function( element ) {
                var url = element.value;

                // Check if it doesn't start with http:// or https:// or ftp://
                if ( url && url.substr( 0, 7 ) !== "http://"
                         && url.substr( 0, 8 ) !== "https://"
                         && url.substr( 0, 6 ) !== "ftp://" ) {
                    // then prefix with http:// or even https://
                     url = "http://" + url;
                }

                // Return the new url
                return url;
            }
        }
    }
} );
```

**Comment by staabm** [comment]
Regarding fakepath: since this is something which is didctated by the http spec I think the validation plugin should be able to handle this magic value on its own - so without the user to register a certain transformer in addition to the rule. If the new layer works that way we can use it internally to automatically register a transformer for file inputs, but maybe its easier to handle this fakepath thing direclty in the fileinput validation lines.

Regarding your url example: I would consider what you write down also normalization therefore this would work that way.

**Comment by Arkni** [comment]
> Regarding fakepath: since this is something which is didctated by the http spec I think the validation plugin should be able to handle this magic value on its own - so without the user to register a certain transformer in addition to the rule.

Agreed!

>If the new layer works that way we can use it internally to automatically register a transformer for file inputs

If you have a form with 2 or more file input, this will lead to a register a transformer to each of the inputs, this will makes the rules bigger and bigger.

>but maybe its easier to handle this fakepath thing direclty in the fileinput validation lines.

Yep, it's easier that way, we should change the `elementValue` method as it used by `check` method in order to retrieve the value of the input and pass it to all the validators attached to the file input.

> Regarding your url example: I would consider what you write down also normalization therefore this would work that way.

I don't have other examples rather than the trimming and the url ones. right now I'm out of ideas :dizzy_face:

**Comment by staabm** [comment]
Great. So we agree that we should call it "normalizer" instead of "tranformer".

> Yep, it's easier that way, we should change the elementValue method as it used by check method in order to retrieve the value of the input and pass it to all the validators attached to the file input.

So you mean we check in `elementValue` if the input is of type file and then strip the value like suggested in the http spec, right?

**Comment by Arkni** [comment]
I think we have to let this issue open and also the PR until there other users asking for this feature as in this [StackOverflow question](http://stackoverflow.com/questions/1827483/jquery-validate-plugin-how-to-trim-values-before-form-validation)

> So you mean we check in elementValue if the input is of type file and then strip the value like suggested in the html5 spec, right?

Yep.
