### ISSUE TITLE
Invalid fields that get deleted are still counted as invalid

### ISSUE THREAD

**Issue by bpromasmb** [jzaefferer/jquery-validation#1604]
In a dynamic form, where the user can create and delete fields, if a user deletes a field while it is invalid and then checks `validator.numberOfInvalids()`, the field count will return a number that includes the now-deleted field.

I know I could validate the entire form again in order to mark the fields again, but in dynamic forms there really is no limit to how big they can get (the app I'm building can easily go to upwards of thousands of input fields...) and so calling `validator.valid()` can get pretty costly, freezing the browser while it goes through the form and marks fields as valid or invalid.

I think this would be a feature request, for an element delete event handler that removes elements upon deletion from whatever count or list the plugin keeps.

Fiddle: http://jsfiddle.net/hMJEy/1369/

**Comment by Arkni** [comment]
As a quick solution, you can add this method to your code:
```js
// Remove the given element from the plugin
//    `element`  A JQuery object.
//    `validator` The jquery validation instance
// Usage:
//     var validator = $( "#myForm" ).validate();
//     removeElement( validator, $( "element selector" ) );
function removeElement( validator, element ) {
	// Remove attached rules
	element.rules( "remove" );

	// Remove it from submitted
	delete validator.submitted[ element[ 0 ].name ];

	// Remove it from errorList
	validator.errorList = $.each( validator.errorList, function( error, index ) {
		if ( error.element === element[ 0 ] ) {
			validator.errorList.splice(index, 1);
			return false;
		}
	} );

	// Remove it from invalid elements
	delete validator.invalid[ element[ 0 ].name ];

	// Then remove it from the form
	element.remove();
}
```

**Updated fiddle:** http://jsfiddle.net/Arkni/af9av9hu/

**Comment by staabm** [comment]
I guess we should also profile what exactly needs that much time, so maybe we can improve performance so the browser will not freeze.

@bpromasmb which browser in which version on which plattform do you use?

**Comment by bpromasmb** [comment]
Thank you Arkni, I'll look into implementing that.

staabm, I'm running chrome version 46.0.2490.71 m, on windows 7. However I don't know if performance is the real issue here, since I am admittedly working with too many input fields and I am already studying ways to decrease the number of fields I have in my DOM at one time. I don't put you guys at fault for this performance hit.

**Comment by staabm** [comment]
Ok will close then. Feel free to discuss the issue further if you have more information or todos regarding the topic.
