### ISSUE TITLE
TypeError with object element ex. $el or el

### ISSUE THREAD

**Issue by aisconverse** [jzaefferer/jquery-validation#1606]
When using such a construction:
$elInnerReq.closest('form').validate().element($elInner);

Where: var $elInnerReq = $('#element') and $elInner = $('.element')

 produces an error console:

TypeError: $elInnerReq.closest(...).validate(...) is undefined

What could be the problem?

**Comment by staabm** [comment]
@aisconverse please provide a jsfiddle which shows the problem

**Comment by staabm** [comment]
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.
