### ISSUE TITLE
Required validator doesn't work on blur when form was not validated entirely

### ISSUE THREAD

**Issue by zhmenka** [jzaefferer/jquery-validation#1610]
Hi,
 
According to current implementation required rules only hit in two cases:
1. when submit the whole form entirely
2. on blur - when form was already submitted and field was in any way not valid.
 
So at least 2 cases are skipped:
1. when user see form the first time (not submitted yet): all rules work perfectly on blur except required
2. even after submitting if field was correct required rule definitely not working on blur.
 
I believe that required rule must work on blur at every moment as other rules.
 
Best regards,
 
Eugenia

**Comment by Arkni** [comment]
`required` method will not validate an empty input unless it's already validated, that's the intended behavior.
