### ISSUE TITLE
C:\fakepath\ is added to length when checking the length of a file type

### ISSUE THREAD

**Issue by zoo1** [jzaefferer/jquery-validation#1615]
C:\fakepath\ is added in to the value field of file inputs. This should be stripped out when validated. The validators affected are maxlength, minlength, rangelength, range, min, and max. My current solution is to add `b=a(c).attr('type')=='file'?b.replace(/C:\fakepath\/i,'');` to each of the validators. However, I know this is not an elegant solution and was wondering if one the maintainers could point me in the right direction.

Testing Notes:
test form: https://jsfiddle.net/zp423Lup/6/
test file to downloaded file: https://www.owasp.org/images/5/52/OWASP_Testing_Guide_v4.pdf
note that the length of the file name is 26 characters and the maxlength is 30 characters so it should pass.

Browsers affected: latest version of Chrome and Safari
Plug-in Versions affected: v1.13.0 - latest

**Comment by Arkni** [comment]
Instead of modifying the validators you mentioned above, you can modify the method `elementValue`. This method is used by `check` method in order to retrieve the value of your input and passe it to all the validators attached to the input element in question.

So something like this will suffice:
```diff
diff --git a/src/core.js b/src/core.js
index 2c6a29f..3ff73ad 100644
--- a/src/core.js
+++ b/src/core.js
@@ -600,26 +600,31 @@ $.extend( $.validator, {
 
 		elementValue: function( element ) {
 			var val,
 				$element = $( element ),
 				type = element.type;
 
 			if ( type === "radio" || type === "checkbox" ) {
 				return this.findByName( element.name ).filter(":checked").val();
 			} else if ( type === "number" && typeof element.validity !== "undefined" ) {
 				return element.validity.badInput ? false : $element.val();
 			}
 
 			val = $element.val();
+
+			if ( type === "file" ) {
+				val = val.replace( /C:\\fakepath\\/i, "" );
+			}
+
 			if ( typeof val === "string" ) {
 				return val.replace( /\r/g, "" );
 			}
 			return val;
 		},
 
 		check: function( element ) {
```

**Comment by staabm** [comment]
Why does this Fakepath exist in the first place?

**Comment by Arkni** [comment]
@staabm 
See:
* http://www.w3.org/TR/html5/forms.html#dom-input-value-filename
* http://www.w3.org/TR/html5/forms.html#fakepath-srsly

**Comment by staabm** [comment]
So I guess we should use the method mentioned in the spec instead of doing a custom regex, right?

**Comment by Arkni** [comment]
> So I guess we should use the method mentioned in the spec instead of doing a custom regex, right?

Yep

**Comment by staabm** [comment]
Nice. So I would merge a PR which contains a unit test and a fix.

**Comment by Arkni** [comment]
> Nice. So I would merge a PR which contains a unit test and a fix if anyone is willing to provide one

The problem is how can someone mock the `file` input ?
Also, this input doesn't accept changing its value dynamically using the value attribute or JavaScript.
The only way to set the value of a file input is by the user to select a file.

**Comment by Arkni** [comment]
There is another option, is by using the `transformer` option (Not available yet, needs discussion), so the user can do:

```js
$( "form" ).validate( {
    rules: {
        file_input: {
            required: true,
            othervalidator: "somevalue",
            // Transformer or another or better name
            transformer: function( element ) {
                var path = element.value;
                if ( path.substr( 0, 12 ) == "C:\\fakepath\\" ) {
                    return path.substr( 12 ); // modern browser
                }
                var x;
                x = path.lastIndexOf( "/" );
                if ( x >= 0 ) { // Unix-based path
                    return path.substr( x + 1 );
                }
                x = path.lastIndexOf( "\\" );
                if ( x >= 0 ) { // Windows-based path
                    return path.substr( x + 1 );
                }

                return path; // just the file name
            }
        }
    }
} );
```
