### ISSUE TITLE
Validation doesn't work when submit again

### ISSUE THREAD

**Issue by 1983cc** [jzaefferer/jquery-validation#1616]
When I try to run an example in the book  named *Knockout js* published by O'Relilly (the example 9-4 of the book) , the code was wrritten as follow:
	
    <!DOCTYPE html>
    <html lang="en">
    <head>
	    <meta charset="UTF-8">
	    <title>Knockout Mapping plugin with options</title>	
    </head>
    <body>
	    <form data-bind="submit: validateAndSave, with: currUser">
		    <input type="text" data-bind="value: firstName" placeholder="Enter your first name" required /><br/>
		    <input type="text" data-bind="value: lastName" placeholder="Enter your last name" required /><br/>
		    <input id="email" type="email" data-bind="value: email" placeholder="Enter your email" required /><br/>
		    <input type="submit" data-bind="value: (id==0) ? 'Create' : 'Update'" />
	    </form>
	
	    <script src="js/jquery.js" type="text/javascript"></script>
	    <script src="js/jquery.validate.js" type="text/javascript"></script>
	    <script src="js/knockout-3.3.0.js" type="text/javascript"></script>
	    <script src="js/knockout.mapping.js" type="text/javascript"></script>
	    <script>
		    function ViewModel(user) {
			    var self = this;
			
			    var mapping = {
				    'observe': ["firstName", "lastName", "email"],
				    'ignore': ["created"]
			    };				
			
			    self.currUser = ko.mapping.fromJS(user, mapping);
									
			    self.validateAndSave = function(form) {	
				    if(!$(form).validate()) return;
				
				    if (self.currUser.id == 0) {										
					alert("Creating a user");
				    }
				    else {								
					    alert("Updating a user");	
				   }				
			    };		
			
		    };
		
		    var user = {
			    id: 1,
			    firstName: 'Mike',
			    lastName: 'Wilson',
			    email: 'mike@notar.com',
			    created: '2014-10-12'
		    };
		
		    var viewModel = new ViewModel(user);
		    ko.applyBindings(viewModel);		
		
	    </script>	    
    </body>
    </html>
	

When I click submit button, post it successfully and the jQuery.validation works well, then I change the content of form to make it invalid and submit again, the jQuery.Validate does not work and it always submit successfully. 
	
I know it is reasonable generally, but if I saves the form and do not want to close window, this looks like abnormal.
	
I tried to debug it, and it seem to do thing with Knockout. 
	
Thank you.

**Comment by staabm** [comment]
@1983cc I dont see jquer-validate api used in this example. Shouldnt your problem be reported to the knockout-js project?

@Arkni any experience with the technology stack in question?

Will close the issue now. We can re-open if required. So feel free to discuss it further

**Comment by Arkni** [comment]
> @Arkni any experience with the technology stack in question?

Sorry, no experience :(

**Comment by 1983cc** [comment]
@staabm I had rose this question in Knockout project. But @mbest said it's not the problem of Knockout, and I think so, too.

**Comment by staabm** [comment]
@1983cc please reduce the example as much as possible and show us a jsfiddle to reproduce it

**Comment by Arkni** [comment]
@1983cc 
Use this code instead:
```js
// Initialize the validator
var validator = $("form").validate();

function ViewModel(user) {
    var self = this;

    var mapping = {
        'observe': ["firstName", "lastName", "email"],
        'ignore': ["created"]
    };

    self.currUser = ko.mapping.fromJS(user, mapping);

    self.validateAndSave = function (form) { 
        // Check of the form is valid
        if (validator.size() !== 0) {
            return;
        }

        if (self.currUser.id == 0) {
            alert("Creating a user");
        } else {
            alert("Updating a user");
        }
    };

};

var user = {
    id: 1,
    firstName: 'Mike',
    lastName: 'Wilson',
    email: 'mike@notar.com',
    created: '2014-10-12'
};

var viewModel = new ViewModel(user);
ko.applyBindings(viewModel);
```

_**Workin example:**_ http://jsfiddle.net/Arkni/d0o479az/

**Comment by mbest** [comment]
@Arkni is correct. Actually this is what I said:

> Your code is incorrect. According the [jQuery Validation documentation](http://jqueryvalidation.org/documentation/), the `validate` function returns an object and so will never be "falsy". What you really need to use is [`valid()`](http://jqueryvalidation.org/valid/).

**Comment by staabm** [comment]
You should use `valid` not `size` method.

**Comment by Arkni** [comment]
> You should use valid not size method.

That's why I suggest the two ways.
I will update my answer then to use only the `valid` method.

**Comment by 1983cc** [comment]
@Arkni I appreciate for your answer。

**Comment by Arkni** [comment]
> @Arkni I appreciate for your answer。

You're welcome :)
