### ISSUE TITLE
Validation Postal Codes Portugal

### ISSUE THREAD

**Issue by Ginmau** [jzaefferer/jquery-validation#1617]
Not so much an issue, I wanted to share the code I updated to validate Portuguese Postal Codes in case you want to add it to the list:

    $.validator.addMethod( "postalcodePT", function( cep_value, element ) {
        return this.optional( element ) || /^\d{3}-\d{3}?$|^\d{4}-?\d{3}?$/.test( cep_value );
    }, "Preencha um código postal válido." );

**Comment by staabm** [comment]
PR welcome
