### ISSUE TITLE
Errorlist containing more errors than it should

### ISSUE THREAD

**Issue by charsleysa** [jzaefferer/jquery-validation#1618]
Hi there,

During development I came across an issue with jQuery Validation plugin.

It seems that the ErrorList isn't cleared when the first input is ignored causing pollution.

Here is a JSFiddle of the issue. https://jsfiddle.net/xLcz7ts9/
Open the Developer console and watch the console log.

You'll see that the ErrorList slowly grows larger and larger.
When this occurs on a page with lots of inputs just 4 iterations is all it takes to freeze the web browser.

My workaround (which may be used as the solution) is to change the `element: function (element)` from the following:
```js
            element: function (element) {
                ...
                if (checkElement === undefined) {
                    delete this.invalid[cleanElement.name];
                } else {
                    this.prepareElement(checkElement);
                    this.currentElements = $(checkElement);
                ...
            },
```

To the following:
```js
            element: function (element) {
                ...
                if (checkElement === undefined) {
                    this.prepareElement(cleanElement);
                    this.currentElements = $(cleanElement);
                    delete this.invalid[cleanElement.name];
                } else {
                    this.prepareElement(checkElement);
                    this.currentElements = $(checkElement);
                ...
            },
```

P.S. I'm using the lastest code from the master branch, this was tested in Chrome and IE11, and should be reproducible in any browser.

**Comment by staabm** [comment]
Please check whether the suggested fix from https://github.com/jzaefferer/jquery-validation/pull/1584#discussion_r44677327 also fixes your issue

**Comment by Arkni** [comment]
> Please check whether the suggested fix from #1584 (comment) also fixes your issue

I think this issue is different the one you linked to. From what I see, I can tell that this issue have something to do with the `valid` method, I will try to investigate the issue when time allows.

**Comment by Arkni** [comment]
I've opened a PR containing the fix, check #1646

**Comment by staabm** [comment]
@charsleysa please double check the PR fixes your problem

**Comment by Arkni** [comment]
@charsleysa 
any feedback on #1646 ?

**Comment by charsleysa** [comment]
@Arkni there are some failed unit tests when building the PR version of the repo so I haven't been able to test it on our web app but I have created an updated JSFiddle with the updated code. https://jsfiddle.net/xLcz7ts9/2/

Issues seems to have been fixed. Thanks.

**Comment by Arkni** [comment]
> @Arkni there are some failed unit tests when building the PR version of the repo so I haven't been able to test it on our web app but I have created an updated JSFiddle with the updated code. https://jsfiddle.net/xLcz7ts9/2/

Which tests are failing ? because as you can see in the PR, all tests have been passed.

**Comment by charsleysa** [comment]
@Arkni here is the output from `grunt --force`:
```bat
C:\Users\scharsle\Downloads\jquery-validation-master>grunt --force
Running "concat:dist" (concat) task
File "dist/jquery.validate.js" created.

Running "concat:extra" (concat) task
File "dist/additional-methods.js" created.

Running "copy:dist" (copy) task
Copied 57 files

Running "jscs:all" (jscs) task
Keyword `else` should not be placed on new line at src/core.js :
   863 |    // If the element is not a child of an associated label, then it's n
ecessary
   864 |    // to explicitly apply aria-describedby
   865 |    else if ( error.parents( "label[for='" + this.escapeCssMeta( element
ID ) + "']" ).length === 0 ) {
------------^
   866 |     errorID = error.attr( "id" );
   867 |
>> 1 code style errors found!
Warning: Task "jscs:all" failed. Used --force, continuing.

Running "jshint:core" (jshint) task
>> 107 files lint free.

Running "jshint:test" (jshint) task
>> 7 files lint free.

Running "jshint:grunt" (jshint) task
>> 1 file lint free.

Running "qunit:files" (qunit) task
Testing test/index.html ........................................................
...........................................Exception occurred when checking elem
ent stepOnUnsupportedTypeInput, check the 'step' method. Error: Step attribute o
n input type date is not supported.
................................................................................
.............................................OK
>> 1297 assertions passed (8056ms)

Done, but with warnings.
```

**Comment by Arkni** [comment]
> @Arkni here is the output from grunt --force:

Thanks, now I see what you mean.
All tests passed except the code style checker. The warning have nothing to do with this issue and the change I introduced in #1646 .

@staabm should I fix that warning in the same PR or in another one ?

**Comment by staabm** [comment]
Since the mentioned lines were not touches with this PR please make a separate one

**Comment by Arkni** [comment]
> Since the mentioned lines were not touches with this PR please make a separate one

Will make one soon
