### ISSUE TITLE
About email validation

### ISSUE THREAD

**Issue by YildirimErdemli** [jzaefferer/jquery-validation#1633]
Hi,

There is no domain extention control on email validation.
If write account@domain validation is OK, but @domain is not a domain.
Because there is no an extention.

![image](https://cloud.githubusercontent.com/assets/892994/10931488/5f94250c-82d0-11e5-8339-f90cdccea832.png)

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

see https://github.com/jzaefferer/validation-content/pull/14/files for how to use a custom email pattern
