### ISSUE TITLE
valid() doesn't work

### ISSUE THREAD

**Issue by geoidesic** [jzaefferer/jquery-validation#1634]
I'm having some trouble understanding how to use this plugin correctly under certain circumstances.

1. If I simply do form.validate(); instead of form.submit() it all works perfectly with one exception, which is that the returned validation object will report no errors unless I use a setTimeout function to test for the errors. The form however shows the error validation as expected.

2. If instead I run form.validate() when the form is created, and then try to test form.valid() before submitting, the form shows as valid.

So I can't figure out how to use .valid() it always seems to be true even when the validation errors appear within the form.

Note that what I'm trying to achieve is to prevent a dialog box (https://github.com/nakupanda/bootstrap3-dialog/issues/152, which contains the form) from closing if the form is invalid.

**Comment by staabm** [comment]
@geoidesic did you try examples from the docs to get a basic understanding on how things work?
http://jqueryvalidation.org/documentation/

without a jsfiddle which shows your problem we cannot help you.

**Comment by staabm** [comment]
Will close for now, until we get feedback

**Comment by geoidesic** [comment]
This can stay closed. I built the fiddle and it works: http://jsfiddle.net/0sbqvq64/3/
