### ISSUE TITLE
Without closing </span> tag, rest of validated fields disappear

### ISSUE THREAD

**Issue by bigteejay** [jzaefferer/jquery-validation#1635]
I have three fields, using ASP5 and MVC6, running in Firefox on Win 7.  All three (sample subset in fdlr, https://jsfiddle.net/nL5sh10b/2/) have validation rules applied (as per ASP MVC ViewModel, in JS sample provided).  If the first validation fails, the remaining fields (their labels and inputs and offending validation spans) are removed from form/dom/html (no longer appear in View Source).

Including closing </span> tags fixes issue (no longer removes the rest of the fields and their associated html content.) As far as I can tell, /> should be fine... http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5/7854998#7854998

**Comment by staabm** [comment]
It dependes whether your document is HTML4, XHTML, HTML5 or XML etc

Also the stackoverflow anser you are pointing to says already that `<span />` is not correct.
