### ISSUE TITLE
Error with highlight on remote

### ISSUE THREAD

**Issue by stassara** [jzaefferer/jquery-validation#1640]
Hi,

Using the following code I found that when I send the form only with the email field completed, if remote return false then the validator execute highlight only for email field.

Link for the code: (http://jsfiddle.net/ckckxLrs/)
![captura de pantalla 2015-11-11 a las 11 18 16](https://cloud.githubusercontent.com/assets/5396721/11092935/dd778a64-8865-11e5-972c-60a372986ab7.png)

Any way to fix it?
Thanks.

**Comment by Arkni** [comment]
The same as in #1584
