### ISSUE TITLE
How can i convert this small code into a validator.addMethod

### ISSUE THREAD

**Issue by cbanicolas** [jzaefferer/jquery-validation#1645]
Hi, in wich way i should convert this peace of small code into a validator.addMethod? the code checks my number of chars inside my tinymce textarea.

                    if (getStats('id_contenido').chars < 50) {
                        $("#textarea_td").prepend('<div class="alert alert-danger">Asegúrese de que este valor tenga como mínimo 50 caracteres (tiene ' + getStats('id_contenido').chars + ').</div>');
                        $('html, body').animate({
                            scrollTop: $("#textarea_td").offset().top
                        }, 300);
                        return false;
                    }

Thanks a lot ! I am not very good with javascript.

**Comment by staabm** [comment]
See e.g.
http://stackoverflow.com/questions/241145/jquery-validate-plugin-how-to-create-a-simple-custom-rule
http://jqueryvalidation.org/jQuery.validator.addMethod/
