### ISSUE TITLE
Run a function before the validation

### ISSUE THREAD

**Issue by sarit8** [jzaefferer/jquery-validation#1653]
How can I run a function before the validation execute.
I tried submitHandler, onsubmit, invalidHndler but nothing helped.

I execute the plugin by:
$("#loginForm").validate({
     rules: {
        username: {
            emailVal: true
        }
     }
)}

when:
  emailVal:function(value, element) {
            return this.optional(element) || /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(value);
        }

**Comment by staabm** [comment]
@sarit8 what are you trying to achieve?

**Comment by sarit8** [comment]
@staabm - I want to ignore/delete the spaces in case the user click on spacebar after he entered a valid email by:
  var strippedUsername = $('#username').val().trim();
        $('#username').val(strippedUsername);

**Comment by staabm** [comment]
In https://github.com/jzaefferer/jquery-validation/pull/1609 we added a "transformation-layer" and documented in https://github.com/jzaefferer/validation-content/pull/15

we havent had a release since then so. In case you are ok with waiting a few weeks and testing this cutting edge feature, please do.

**Comment by sarit8** [comment]
@staabm - so there is no way now to run a function before the validate except trigger a function by some event (for example "onfocus) outside the validate()?

**Comment by staabm** [comment]
@sarit8 with a stable release there isnt. Auto-trimming of user-input was dropped in 1.14.0, so you could also work with 1.13.1 until we have a release which supports this feature.

**Comment by staabm** [comment]
Feel free to ask further questions, I will close the issue for now.

We can re-open in case something needs to change.
