### ISSUE TITLE
Validate verifies the dynamic addition of form？

### ISSUE THREAD

**Issue by zhangangs** [jzaefferer/jquery-validation#1654]
I dynamically added a validate, form can not work, do you have this solution?

**Comment by Arkni** [comment]
Please provide a [jsfidlle](http://jsfiddle.net/) ?

**Comment by staabm** [comment]
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.
