### ISSUE TITLE
Validate on "#id" rather than "name"

### ISSUE THREAD

**Issue by FoldZero** [jzaefferer/jquery-validation#1664]
Title says it all.
Allow to validate using the input id's rather than the name.

Some large preformatted forms do not have a name field, this means a lot of work adding the field in at runtime.

Would be useful to just use the unique id's already there.

**Comment by staabm** [comment]
How do you handle server side processing when forms dont have names?

**Comment by staabm** [comment]
No response + duplicate of https://github.com/jzaefferer/jquery-validation/issues/659
