### ISSUE TITLE
Remote validator message not show

### ISSUE THREAD

**Issue by minibear0523** [jzaefferer/jquery-validation#1666]
I'm using node.js v4.1.2 and express.js framework with jQuery Validator. I want to validate username with remote validator to check if it is existed.
My front-end code are
```
$accountInfoForm.validate({
      debug: true,
      rules: {
        username: {
          required: true,
          remote: {
            url: '/account/check_username',
            method: 'POST',
            data: {username: function() {return $('#inputName').val();}}
          }
        },
        email: {required: true, email: true}
      },
      messages: {
        username: {
          required: '用户名不能为空',
          remote: '您输入的用户名已存在'
        },
        email: {required: '电子邮箱不能为空', email: '请输入正确格式的电子邮箱地址'}
      },
```
Any my server-side function is
```
router.post('/check_username', function(req, res, next) {
  var newName = req.body.username;
  if (newName == req.user.username) {
    return res.status(200).json({username: true});
  }
  Account.find({username: newName}, function(err, user) {
    if (err) return res.status(200).json({username: true});
    return res.status(200).json({username: false});
  });
})

router.get('/register', function(req, res, next) {
  res.render('front/account/register.jade')
})
```
But when the input username is existed, the error message does not show as other validator's error message.

**Comment by highri5e** [comment]
Hey, what you want to return is a string rather than key-value pair, like so:

return res.status(200).json("false");

or if you want a custom message, return the message as string:

return res.status(200).json("username must be unique");

**Comment by staabm** [comment]
@minibear0523 will close for now. Feel free to discuss this further here, in case @highri5e reply doesnt work for you
