### ISSUE TITLE
[Build] Failure: grunt - Running "jscs:all" (jscs) task - Fatal error: Neither config file nor grunt options were defined

### ISSUE THREAD

**Issue by shehi** [jzaefferer/jquery-validation#1667]
Ideas?

```
cd `pwd`/public/bower_components/jquery.validation && npm install && grunt && cd ../../../;
loadDep:supports-color →  ▀ ╢██████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN prefer global jshint@2.5.11 should be installed with -g

> commitplease@2.0.0 install /home/shehi/Projects/Basis/public/bower_components/jquery.validation/node_modules/commitplease
> node install

Could not find git repo in /home/shehi/Projects/Basis/public/bower_components/jquery.validation/.git

> phantomjs@1.9.19 install /home/shehi/Projects/Basis/public/bower_components/jquery.validation/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [=====================================---] 92% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Removing /home/shehi/Projects/Basis/public/bower_components/jquery.validation/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1450259622030/phantomjs-1.9.8-linux-x86_64 -> /home/shehi/Projects/Basis/public/bower_components/jquery.validation/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/shehi/Projects/Basis/public/bower_components/jquery.validation/node_modules/phantomjs/lib/phantom/bin/phantomjs

> jquery-validation@1.14.0 prepublish /home/shehi/Projects/Basis/public/bower_components/jquery.validation
> grunt

Running "concat:dist" (concat) task
File "dist/jquery.validate.js" created.

Running "concat:extra" (concat) task
File "dist/additional-methods.js" created.

Running "copy:dist" (copy) task
Copied 57 files

Running "jscs:all" (jscs) task
Fatal error: Neither config file nor grunt options were defined

npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! jquery-validation@1.14.0 prepublish: `grunt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jquery-validation@1.14.0 prepublish script 'grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jquery-validation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jquery-validation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jquery-validation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shehi/Projects/Basis/public/bower_components/jquery.validation/npm-debug.log
```

**Comment by staabm** [comment]
@Arkni

**Comment by shehi** [comment]
This happens because Bower installation ignores all dotFiles, including ```.jshsrc``` (or whatever it is called), which is required for Grunt (that much I gathered from my searches). You should un-ignore these required files from ```bower.json```.

**Comment by staabm** [comment]
I am wondering why it works on travis

**Comment by shehi** [comment]
That's why you should use Docker in Travis, to control your environment. You have no idea how Travis' environment was built and what it consists of.

**Comment by Arkni** [comment]
@staabm 
Sorry, I have been very busy the last days.

> This happens because Bower installation ignores all dotFiles, including .jshsrc (or whatever it is called), which is required for Grunt (that much I gathered from my searches). You should un-ignore these required files from bower.json.

Yes you're right. That's the culprit.

> I am wondering why it works on travis

The file `.travis.yml` contains instructions to only use npm (no bower used at all), that's why we didn't see that error.

**Comment by staabm** [comment]
> Sorry, I have been very busy the last days.

dont worry, I get into this situation also regularly.

PR to fix this is welcome.


> The file .travis.yml contains instructions to only use npm (no bower used at all), that's why we didn't see that error.

should we change the travis script to reflect the same procedure/steps as we propage in the readme for a "regular" user?

**Comment by Arkni** [comment]
> should we change the travis script to reflect the same procedure/steps as we propage in the readme for a "regular" user?

I don't see that as a requirement. The build instructions describe the way to build the project after making some changes (and that's require `nodejs` and `npm` installed, bower not required). If the user use `bower` to only manage the dependencies of his project, then there is no need to rebuild a dependency (as it's already done).

**Comment by Arkni** [comment]
@shehi 
Why you need to rebuild the project if its already done ?

**Comment by shehi** [comment]
@Arkni : It is?! I download with Bower and then build it. You say you have build already existing inside downloaded repo?!

**Comment by Arkni** [comment]
> You say you have build already existing inside downloaded repo?!

Yes that what I said, if you do:
```
bower install jquery-validation
// or
bower install git://github.com/jzaefferer/jquery-validation
```
will give you the same version 1.14.0, and the structure of the downloaded package as the following:
```
.
├── bower.json
├── build
│   └── release.js
├── changelog.md
├── CONTRIBUTING.md
├── dist
│   ├── additional-methods.js
│   ├── additional-methods.min.js
│   ├── jquery.validate.js
│   └── jquery.validate.min.js
├── Gruntfile.js
├── LICENSE.md
├── package.json
├── README.md
├── src
│   ├── additional
│   │   ├── accept.js
│   │   ├── additional.js
│   │   ├── alphanumeric.js
│   │   ├── bankaccountNL.js
│   │   ├── ...
│   │   ├── ...
│   │   ├── vinUS.js
│   │   ├── zipcodeUS.js
│   │   └── ziprange.js
│   ├── ajax.js
│   ├── core.js
│   └── localization
│       ├── messages_ar.js
│       ├── messages_bg.js
│       ├── messages_bn_BD.js
│       ├── ...
│       ├── ...
│       └── methods_pt.js
└── validation.jquery.json
```

>There is no /dist folder in the repo tho. Or do you see jquery.validation.min.js anywhere inside repo?

There is a difference between what you see in the repo and what published to `npm` and `bower`. The repo does not contain the `dist` folder for a reason (avoiding building the project for every change), but the published version does (e.g. see this tag: https://github.com/jzaefferer/jquery-validation/tree/1.14.0, the dist folder is there)

**Comment by shehi** [comment]
How could I know you have additional files in tagged releases lol :D Thanks mate, closing this one now.

**Comment by Arkni** [comment]
You're welcome :)
