### ISSUE TITLE
Remote validation deletes previous validation errors

### ISSUE THREAD

**Issue by suclogger** [jzaefferer/jquery-validation#1669]
Similar to #1375 , #12  and #512 .

Here is my test code.
using jQuery 1.9.0 and jQuery validation 1.14.0
```
<!DOCTYPE html>
<html>
<head>
    <script src="jquery.js"></script>
    <script src="jquery.validate.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#submitForm").validate({
                rules: {
                    "requiredElement": "required",
                    "remoteElement": {
                        required: true,
                        remote: {
                            url: "a method returns true",
                            type: "post",
                            data: {
                                test: "not necessary"
                            },
                            // set async to false
                            async: false
                        }
                    }
                }
            });
            $("#testBtn").click(function () {
                console.log($("#submitForm").validate().form());
            });
        });
    </script>
</head>
<body>
<form id="submitForm">
    <div>
        it's a required element!
    </div>
    <input name="requiredElement"/>
    <div>
        it's a remote element!
    </div>
    <input name="remoteElement"/>
    <div>
        it's a button!
    </div>
    <input type="button" id="testBtn" value="test"/>
</form>
</body>
</html>
```

Every first time the test button is clicked, the validate result is not correct: 
**Although the required element `requiredElement` is left empty, but the validate result still indicates valid.**

After some digging,in `core.js` line 1424:
```
validator.prepareElement( element );
```

`prepareElement` is called after remote method return a valid result, which cause the former errors being erased.  

Maybe you would indicate #12 #issuecomment-14179880 
>but he uses async: false, which isn't supported and never will be.

Bu if we don't use ` async: false`, the result of `$("#submitForm").validate().form()` is still not correct because the valid result would return valid before the asynchronous method returns.

**I didn't see why we need to call the `prepareElement` after remote method returns true, and I also didn't see why we shouldn't use `async: false`.**

And as mentioned issues are all closed, so I open this new issue to describe the problem. 
Hoping to get an answer on how to correctly use the remote check.

**Comment by staabm** [comment]
using async=false is discouraged because it affects browser performance and can make it even stall.

**Comment by staabm** [comment]
per reporter no longer reproducible, see https://github.com/jzaefferer/jquery-validation/pull/1712#issuecomment-185533704
