### ISSUE TITLE
Validate fields on change that aren't focused

### ISSUE THREAD

**Issue by krypsin** [jzaefferer/jquery-validation#1671]
I've got this problem that I have been rattling my brain over for days now and I can't find a solution for this.

Basically I have a registration form that uses postal code validation services that when you begin typing the post code, it provides you with a dropdown location chooser and when you click the location you want it will fill out remaining fields like Address & County.

So there's 3 fields where this problem come to hand:
  - Postal Code
  - Address Line 1
  - County

They will all be filled out but only the first one will be validated as that is the one that is focused by the user, so when I tab out my form looks like this:

![screenshot from 2015-12-17 10 55 40](https://cloud.githubusercontent.com/assets/8135396/11868010/c7627bfe-a4ac-11e5-906c-a73ca94d6dc9.png)

I hope this is a clear enough explanation. The only way to validate the other two fields is by clicking in and out on them or tabbing through them.

Any ideas?

**Comment by staabm** [comment]
You can validate the whole form at once by using `valid()`[1] but I am not sure this is what you want
It sounds like also defining dependencies[2] between the fields could be a option for you, see `depends`

[1] http://jqueryvalidation.org/valid/
[2] http://jqueryvalidation.org/validate/#rules

**Comment by krypsin** [comment]
Well I did try using valid() on the fields individually like so:
`$('input[name="register_attribute_1"]').on('change', function(){
	$(this).valid();
});
$('input[name="register_attribute_2"]').on('change', function(){
	$(this).valid();
});
$('input[name="#register_attribute_3"]').on('change', function(){
	$(this).valid();
});`

but it didn't actually do anything (the selectors are correct) but when I do it manually from dev console it works fine.

I took at look at the depends method but seems confusing as it looks like it services the same purpose as using a function for required .e.g:
`register_attribute_5: {
	phoneUK: true,
	required: function(element){
		return $('#register_attribute_4').is(':blank');
	}
}`

Would you be able to give an explanation of the depends option?

**Comment by staabm** [comment]
`valid()` validates the form. to validate only one element use `element()`.

**Comment by krypsin** [comment]
`element()` was very useful, thank you.

Turns out I had to contact the company that provides my postal validation service for a specific event listener as their script doesn't trigger on blur, change or anything (it's something else they use).

Thanks again, though.

For anyone that uses PCAPredict services, you can use this snippet:

```
capturePlus.listen("load", function (control) {
    control.listen("populate", function (address) {
		$('#form_id').validate().element('input[name="register_attribute_2"]');
		$('#form_id').validate().element('select[name="register_attribute_3"]');
	});
});
```
