### ISSUE TITLE
Validating checkbox error

### ISSUE THREAD

**Issue by pascaldls** [jzaefferer/jquery-validation#1675]
i have 2 forms on my page while validating one of them it is validating the checkbox on the other form
reason ( validate.js ) function elementValue 
			if ( type === "radio" || type === "checkbox" ) {
				return $( "input[name='" + element.name + "']:checked" ).val();
i have made a simple workaround by checking for the element class and id 
				return $( "input[name='" + element.name + "']" 
					+ ( element.id ? "#"+ element.id : "" )
					+ ( element.className 	? "."+ element.className : "" )
					+ ":checked" ).val();
may be a better way would be to validate only the elements in this form
hope its helps

**Comment by staabm** [comment]
This should be fixed by https://github.com/jzaefferer/jquery-validation/commit/64d6d7f7518541b113f9405695e5c1095e30bfe2 and work with 1.14 and above.

Which version are you using?
