### ISSUE TITLE
Add maxbytes method?

### ISSUE THREAD

**Issue by mirachat** [jzaefferer/jquery-validation#1682]
Javascript's length method, which is used by jquery-validation to calculate an input's content length, simply returns #letters in ASCII scenarios, or #characters in non-ASCII scenarios. Sometimes we want to calculate the total number of bytes instead, especially when letters and characters are mixed. For example, "您a" has #bytes of 4, since each character takes 3 bytes, and each letter takes 1.

Is it worth adding such a method?

Thanks.

**Comment by Arkni** [comment]
I don't know why you did close the issue, but here are some helpful resources:
* http://stackoverflow.com/questions/5515869/string-length-in-bytes-in-javascript/23329386#23329386
* https://gist.github.com/mathiasbynens/1010324
* https://github.com/substack/utf8-length/issues/2#issuecomment-29539311

Based on those links, you can build your own `maxByte` rule and contribute it back to this lib if you want :)
