### ISSUE TITLE
How to check password strength ?

### ISSUE THREAD

**Issue by NiranjanaK** [jzaefferer/jquery-validation#1683]
Hi @jzaefferer 
I need some more additional requirement to check password strength like combination of uppercase,lowercase,digit and special character. Is there any function defined for that?

**Comment by staabm** [comment]
Nope there isnt.

As mentioned earlier, I dont think this makes sense to be bundled with the lib. Password strength rules are very different, depending on the problem domain.

**Comment by XenRevo** [comment]
I recommend [this](https://timseverien.com/passy/).

**Comment by Joyrex** [comment]
Seems the library's author (at one point) disagreed with that stance: https://github.com/jzaefferer/jquery-validation.password
