### ISSUE TITLE
Validate and focus on error tabs

### ISSUE THREAD

**Issue by mtran21** [jzaefferer/jquery-validation#1688]
How do I set focus on the bootstrap tab that has required field when submit button is clicked?

**Comment by staabm** [comment]
The information provided is not enough to help you.

Whats your exact problem? Please provide a jsfiddle which demonstrates your problem

**Comment by staabm** [comment]
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.
