### ISSUE TITLE
jQuery range validation fails for negative numbers with only a lower bound

### ISSUE THREAD

**Issue by git-hub-user** [jzaefferer/jquery-validation#1689]
I have an issue with range validation on text input fields for numbers. I wanted require the input to be -50 or higher. 

See http://jsfiddle.net/RSchreurs/vkreywe0/.

Validation fails for -333 and -33, but not for -99 and -9.
It should fail for -333 and -99, but not for -33 and -9. 

This issue occurs for input fields with only a lower bound (data-val-range-min). Looking at the results (and a bit at the jQuery.validation source), I think this issue is a result of a textual comparison on negative numbers.
I found this bug in version 1.14.0 of jQuery.validate. I used Firefox 43.0.4.
The bug is not found in earlier version of jQuery validate, e.g. 1.7. There are updates in the code related to range validation, between those versions.

This fiddle relies on jQuery validate unobtrusive, but I do not think the issue is in that library.

**Comment by Arkni** [comment]
I just tested your usecase without using `jQuery validate unobtrusive` and it's working as expected, see:
* https://jsfiddle.net/Arkni/v3y1xz3e/

I think the problem is in the unobtrusive lib. You should check with them instead.

**Comment by staabm** [comment]
Doesnt seem to be jq-validate related. If you got more information feel free to speak up - we will re-open this issue then.
