### ISSUE TITLE
[Discussion] Validate inputs with same name

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1690]
Hi @staabm 

There are 3 PR that address the problem of validating inputs with same name. I think 2 PR should be closed in favor of the older one.

The PR in question are:
* #717 
* #1330 
* #1665 (**closed**)

Also, I see that a number of users are requesting this feature, so maybe we can implement it.

**Comment by staabm** [comment]
Which to close? Suggestions?

**Comment by Arkni** [comment]
We always close the new ones in favor of the first PR. So, I think closing #1330 will be OK as #717 seems more robust.

**Comment by staabm** [comment]
Here we go..
