### ISSUE TITLE
date-method in FireFox and IE 11 and Edge error

### ISSUE THREAD

**Issue by janjon** [jzaefferer/jquery-validation#1696]
see http://jqueryvalidation.org/date-method

value:2016-01-21 14:50:06

date-method in FireFox and IE 11 and Edge output "Please enter a valid date."
 , but in chrome is normal.

version 1.14.0
please retest!

**Comment by Arkni** [comment]
See this question on Stackoverflow: http://stackoverflow.com/questions/3257460/new-date-is-working-in-chrome-but-not-firefox

**Comment by staabm** [comment]
@janjon The docs page you quoted already tells you that this method should not be used:

> This method should not be used, since it relies on the new Date constructor, which behaves very differently across browsers and locales. Use dateISO instead or one of the locale specific methods (in localizations/ and additional-methods.js).
