### ISSUE TITLE
Custom rule for all inputs in a div

### ISSUE THREAD

**Issue by JesusCarvalho** [jzaefferer/jquery-validation#1697]
I'm trying to apply the following logic:

1. Inputs in a specific div are NOT required for successful form validation
2. BUT if any in those div are filled in, then ALL must be completed for successful form validation

I feel like this is very easy using a boolean combination of :filled and :blank to the effect of (pseudocode):

if ( number of :filled in div > 0) and (number of :blank in div >0) then return fail 
...
...
..

But looking around online there doesn't seem to be a  DRY way to apply that rule to all inputs in the div at once.

Am I missing something?

**Comment by staabm** [comment]
See `rules` and `depends` on http://jqueryvalidation.org/validate/

**Comment by staabm** [comment]
I will close this issue for now. Feel free to ask further questions or discuss additional points nevertheless here.
