### ISSUE TITLE
jQuery Validation doesn't fire if next input is non-blank

### ISSUE THREAD

**Issue by terryaney** [jzaefferer/jquery-validation#1698]
I've set up a simple fiddle at https://jsfiddle.net/51uwoc5w/7/ that has two inputs, the first of which has validation rules (of required) applied to it.  Strange behaviors happen if the second input has any value.

Here are the four scenarios (of course non-working one was my preferred method of UI interaction/testing).  Success is defined by seeing a 'highlight' and 'errorPlacement' event.

Scenario 1 (works) - Both inputs blank, using mouse
1) Type value in first input
2) Click with mouse outside input
3) Click with mouse inside input
4) Clear input
5) Validation occurs (success)

Scenario 2 (works) - Both inputs blank, using keyboard (tab/shift+tab)
1) Type value in first input
2) Press TAB
3) Press SHIFT+TAB
4) Clear input
5) Validation occurs (success)

Scenario 3 (works) - Second input has value, using mouse
1) TAB to or click second input and type a value
2) SHIFT+TAB or click first input and type a value
3) Click with mouse outside input
4) Click with mouse inside input
4) Clear input
5) Validation occurs (success)

Scenario 4 (**fails**) - Second input has value, using keyboard
1) TAB to or click second input and type a value
2) SHIFT+TAB or click first input and type a value
3) Press TAB
4) Press SHIFT+TAB
5) Clear input
6) Validation **does not** occur (**failure**)

**Comment by Arkni** [comment]
This is already addressed in #1579 and #1680. So, it should be fixed by now.

But, It would be great if you test the code in master and provide some feedback :)

**Comment by terryaney** [comment]
Note, if I add the following to iGUI, things seem to work.

		function jQueryValidateInput() {
			var input = $(this);
			var val = input.val();
			if (val == "") {
				input.valid();
			}
		}

		$('.iGUI').on("input", validateInput );

**Comment by terryaney** [comment]
Ah, thanks Arkni, will go try.

**Comment by terryaney** [comment]
Embarrassed, but is there just a download for latest generated *.js file?  Or do you need to do entire build process yourself (with nodejs and grunt cli)?

**Comment by Arkni** [comment]
The second.

But you can download the file `jquery.validate.js` from here (I did the build myself): https://gist.github.com/Arkni/40956198a7449d88fe0e

**Comment by terryaney** [comment]
Thanks so much.  Seems to have corrected my problem.

**Comment by Arkni** [comment]
Thanks for confirming :)

**Comment by staabm** [comment]
@terryaney just to let you know. We are finishing the next release in the next days
