### ISSUE TITLE
grouped Date-Select: error message disappears even if the group is considered invalid

### ISSUE THREAD

**Issue by staabm** [jzaefferer/jquery-validation#1699]
when selects are grouped together, error message handling is wired.
even when one of the fields of the group is considered invalid, no error message is rendered.

see https://jsfiddle.net/wzbptn6z/2/

I am opening this issue mostly for discussion purposes, as I am not 100% confident that it is something which need to be handled by jquery-validation core, as the behaviour seems to only occur because of the `onfocusout` triggered validation.

**Comment by staabm** [comment]
@Arkni would be interessed in your opinion on this topic.

**Comment by Arkni** [comment]
I confirm the issue, tested in Chromium 48.0.2564.82 and FF43.

The same issue appears using the master version, Here is a screen-cast of the test:
![anim](https://cloud.githubusercontent.com/assets/6888059/12718543/23c980b4-c8e7-11e5-8531-5b1f6823ca13.gif)

Right now, I have no idea why this happened. But will investigate this behavior and see if we can fix it soon before the next release.

**Comment by staabm** [comment]
I think it happens because of the used `focusout` handler.

when focus-out on the month-select the error message appears (because months is invalid) and the focus-in on the year is hides the message again as the year-select is valid.

this happens very fast, one after another.

**Comment by Arkni** [comment]
> I dont see the difference. whats different?

In the fiddle, the error disappear only after the `year` lose focus.
![anim](https://cloud.githubusercontent.com/assets/6888059/12718936/df9e49bc-c8e9-11e5-939d-a0cbabcae8ed.gif)

But in the test with master version, the error disappear as soon as the `year` receive the focus. That's the only difference.

**Comment by Arkni** [comment]
I tracked the issue down to `defaultShowErrors` method. After doing some debugging, I found that `this.errorList` is empty when the `year` element is valid, but it shouldn't be (`month` is invalid). Then, I realize that this list is cleared before validating every element inside `reset` method and I guess there is a reason for doing that (which I don't know).

**Comment by staabm** [comment]
Maybe we just miss "group-support" in reset().. I guess the method doesnt account for the group feature yet. Will have a look later. Thx for your initial investigation

**Comment by staabm** [comment]
After thinking a bit more about it... 

when validating only a single element like `this.element(element)` does, we should check whether this element is part of a group and if so we need to also validate all elements of the group in the same run.

WDYT?

**Comment by Arkni** [comment]
> when validating only a single element like this.element(element) does, we should check whether the current element is part of a group and if so we need to also validate all elements of the group in the same run.

So, if you have 3 elements in a group, the validation will run 3 times for every element. Am I right ?

> The current element should only been considered valid when all elements of the group are valid..
> In this run we should not add a "invalid" class to all members of the group, but we should take them into account to determine the "valid/invalid" class for the current element....

We can rely on `invalid` object, which contains valid and invalid elements. I'm thinking of doing this check inside `defaultShowErrors` method. So instead o showing errors according to `errorList` which is cleared for every element, we can use the `invalid` object extended by the content of `errorMap`. I didn't test this idea, yet. But I'm planning to.

**Comment by staabm** [comment]
> So, if you have 3 elements in a group, the validation will run 3 times for every element. Am I right ?

I guess we should only do it that way, in case a single element is validated using `element`. In case the whole form is validated, we dont need to check the groups, as all elements are checked nevertheless..

**Comment by Arkni** [comment]
Sounds good to me.

**Comment by staabm** [comment]
I tried to implement something to fix this bug, but it feels like my assumption of the group based behaviour feels like would only hold in my certain case (multiple selects for a date).

not sure those assumptions will also work for grouped input fields in the wild. I can atm not think of other situations where people work with the grouping-feature to achieve different things..

**Comment by Arkni** [comment]
> ..this will only hold in case all the fields are required... in case of a optional date select trinity it feels like it should be configured with the depends feature additionally... (the selects should be required when one holds a value, but all should be handled as optional when none has a value)
> 
> whats the expected behaviour when some fields of the group are optional and some are required?

IMO nothing will change, as the rules for a specific element (required or optional) are filtered first before validating it. So if an element is optional and the requirement to make it required is not met, then it will skip validation as `rules()` will return an empty object.

> usability wise it is strange when the user starts filling the fields from the front, and after the first field is filled in a error occurs because not yet filled fields are considered invalid.

Maybe you can validate other elements only if those are present in `submitted` or `invalid` objects (as done in `onkeyup` handler) ?

**Comment by staabm** [comment]
I guess a few lines of code is better then a thousand words.
Thats what I tried:

```js
		// http://jqueryvalidation.org/Validator.element/
		element: function( element ) {
			var cleanElement = this.clean( element ),
				checkElement = this.validationTargetFor( cleanElement ),
				elements = [],
				group,
				v = this,
				elementResult,
				overallResult = true;

			if ( checkElement === undefined ) {
				delete this.invalid[ cleanElement.name ];
			} else {

				// If this element is grouped, then validate all group elements already
				// containing a value
				group = this.groups[ checkElement.name ];
				if ( group ) {
					$.merge( elements, $.map( this.groups, function( testgroup, name ) {
						var cleanElement;
						
						if ( testgroup === group && name) {
							cleanElement = v.clean( v.findByName( name ) );
							if (cleanElement.value) {
								return v.validationTargetFor( cleanElement );
							}
						}
						
						return null;
					}));
				} else {
					elements.push(checkElement);
				}
				
				$.each(elements, function( i, element ) {
					v.prepareElement( element );
				});
				
				this.currentElements = $( elements );
				for ( var i = 0; elements[ i ]; i++ ) {
					elementResult = this.check( elements[ i ] ) !== false;
					if ( elementResult ) {
						this.invalid[ checkElement.name ] = false;
					} else {
						this.invalid[ checkElement.name ] = true;
					}
					overallResult = overallResult && elementResult;
				}

				if ( !this.numberOfInvalids() ) {

					// Hide error containers on last error
					this.toHide = this.toHide.add( this.containers );
				}
				this.showErrors();
			}

			// Add aria-invalid status for screen readers
			$( element ).attr( "aria-invalid", !overallResult );

			return overallResult;
		},
```

**Comment by Arkni** [comment]
Looks good to me, here are some reviews:
```diff
// .... snip..
        // http://jqueryvalidation.org/Validator.element/
        element: function( element ) {
            var cleanElement = this.clean( element ),
                checkElement = this.validationTargetFor( cleanElement ),
                elements = [],
                group,
                v = this,
                elementResult,
                overallResult = true;

            if ( checkElement === undefined ) {
                delete this.invalid[ cleanElement.name ];
            } else {

                // If this element is grouped, then validate all group elements already
                // containing a value
                group = this.groups[ checkElement.name ];
                if ( group ) {
                    $.merge( elements, $.map( this.groups, function( testgroup, name ) {
                        // Already declared
-                       var cleanElement;

                        if ( testgroup === group && name) {
                            // `findByName` return a jQuery object, not an HTML element
-                           cleanElement = v.clean( v.findByName( name ) );
+                           cleanElement = v.clean( v.findByName( name )[ 0 ] );
                            if (cleanElement.value) {
                                return v.validationTargetFor( cleanElement );
                            }
                        }

                        return null;
                    }));
                } else {
                    elements.push(checkElement);
                }

                // Why you prepare all elements before validating
                // I expect preparing every element in its round
-               $.each(elements, function( i, element ) {
-                   v.prepareElement( element );
-               });

                this.currentElements = $( elements );
                for ( var i = 0; elements[ i ]; i++ ) {
+                   v.prepareElement( elements[ i ] );
                    elementResult = this.check( elements[ i ] ) !== false;
                    if ( elementResult ) {
                        this.invalid[ checkElement.name ] = false;
                    } else {
                        this.invalid[ checkElement.name ] = true;
                    }
                    overallResult = overallResult && elementResult;
                }

                if ( !this.numberOfInvalids() ) {

                    // Hide error containers on last error
                    this.toHide = this.toHide.add( this.containers );
                }
                this.showErrors();
            }

            // Add aria-invalid status for screen readers
            $( element ).attr( "aria-invalid", !overallResult );

            return overallResult;
        },
// .... snap..
```

**Comment by Arkni** [comment]
Never mind my previous comment, I tested your changes along with the code of the fiddle, by it's not validating on focus out. I think you have to add the current element to `elements` array whether it has a value or not (inside the first else before `if ( group ) { ... }`).

**Comment by staabm** [comment]
Need to test that thx.

One thing: the invalid state os of now will depend on all group-fields. I get the feeling that his might leave a field marked as invalid (via aria attribute), even if it only was invalid because of a other element in the group. When this invalid field later on gets the valid the first mentioned field will still be aria-invalid although all elements of the group already got valid

**Comment by Arkni** [comment]
> One thing: the invalid state os of now will depend on all group-fields. I get the feeling that his might leave a field marked as invalid (via aria attribute), even if it only was invalid because of a other element in the group. When this invalid field later on gets the valid the first mentioned field will still be aria-invalid although all elements of the group already got valid

You mean `aria-invalid` right ?
We can avoid that, but before that, I have a question:
* Does it make sense to add `aria-invalid` to an ignored element ?

IMO, only the validated element should have that attribute set to `true|false`.
WDYT ?

**Comment by staabm** [comment]
Agree that ignored elements should not be touched by jq-validate

**Comment by Arkni** [comment]
OK, here is an updated version of `element()`:
```js
// http://jqueryvalidation.org/Validator.element/
element: function( element ) {
	var cleanElement = this.clean( element ),
		checkElement = this.validationTargetFor( cleanElement ),
		v = this,
		result = true,
		rs, group;

	if ( checkElement === undefined ) {
		delete this.invalid[ cleanElement.name ];
	} else {
		this.prepareElement( checkElement );
		this.currentElements.push( checkElement );

		// If this element is grouped, then validate all group elements already
		// containing a value
		group = this.groups[ checkElement.name ];
		if ( group ) {
			$.map( this.groups, function( testgroup, name ) {
				if ( testgroup === group && name !== checkElement.name ) {
					cleanElement = v.validationTargetFor( v.clean( v.findByName( name ) ) );
					if ( cleanElement && cleanElement.name in v.invalid ) {
						v.currentElements.push( cleanElement );
						result = result && v.check( cleanElement );
					}
				}
			} );
		}

		rs = this.check( checkElement ) !== false;
		result = result && rs;
		if ( rs ) {
			this.invalid[ checkElement.name ] = false;
		} else {
			this.invalid[ checkElement.name ] = true;
		}

		if ( !this.numberOfInvalids() ) {

			// Hide error containers on last error
			this.toHide = this.toHide.add( this.containers );
		}
		this.showErrors();

		// Add aria-invalid status for screen readers
		$( element ).attr( "aria-invalid", !rs );
	}

	return result;
},
```

You may need to test it with real world project to make sure it's working as expected (even if the tests pass, we may ignore some usecases)

**Comment by staabm** [comment]
just did some dummy testing and it looks good so far. I will let this be tested by some others devs.

nit: the `$.map` is useless atm, right? could "just be" a `for` or `$.each`?

**Comment by Arkni** [comment]
> nit: the $.map is useless atm, right? could "just be" a for or $.each?

Yep, you can replace it with `$.each( ... )`

**Comment by staabm** [comment]
ok, will do they change at merge-time.

@Arkni thx so far.

**Comment by staabm** [comment]
fix landed in https://github.com/jzaefferer/jquery-validation/commit/2992ab6db9bde87c5f4b840431940f95f63821c1?w=1

**Comment by staabm** [comment]
Hm I think we found one case which doesnt work with his change.

- load page containing 3 (DD.MM.YYYY) grouped selects (like in the examples we had initially)
- select a day
- tab to month
- tab to year (now field is rendered invalid)
- shift-tab back to month
- select a month
- tab to year
- select a year
- tab to the next input

-> group still rendered invalid even if all 3 fields have a valid value

@Arkni could you confirm?

**Comment by Arkni** [comment]
Nope, I can't reproduce the issue.

I tested in Chrome 50, Firefox 46 and Firefox 49 (developer edition) and everything works as expected.

**Comment by staabm** [comment]
I guess what my tests above try to reproduce is https://github.com/jzaefferer/jquery-validation/issues/1816

**Comment by Arkni** [comment]
Yeah, we need a regression test to make sure no problem will appear in the near future.

I'll be able to make one in the next days, in case the author of #1805 is not willing to create one.
