### ISSUE TITLE
Can we add a $("#element").rulesCount() function

### ISSUE THREAD

**Issue by fabriziomazzoni** [jzaefferer/jquery-validation#1703]
As per is there a method to know how many rules have been created for the element such as ruleCount()? Or a .hasRules() method to know if there are or not any rules?

Would it be possible?

**Comment by staabm** [comment]
@fabriziomazzoni please describe your use-case... why do you need this kind of information?

**Comment by staabm** [comment]
we have a `.rules()` method, see http://jqueryvalidation.org/rules/

so you can do `jQuery("#myelement").rules().length` to count the rules

**Comment by fabriziomazzoni** [comment]
Thats exactly what I am trying to do but it is not working. I have posted
to stack exchange but no one seems to be able to help.

**Comment by Arkni** [comment]
`.rules()` returns a regular object, not a `jQuery` object. As a solution you do:

```js
Object.keys( $( "#element" ).rules() ).length;
```

And for `hasRule`:

  ```js
  $( "#element" ).rules().hasOwnProperty( "name of rule" );
  ```
