### ISSUE TITLE
Feature request: Remove validator

### ISSUE THREAD

**Issue by RoBorg** [jzaefferer/jquery-validation#1704]
It would be useful to have an option to remove the validator from a form - I think all it needs to do it remove the data and unbind the events.

At the moment I'm doing this outside the plugin like this:

```
form.add(form.find(':submit, input, select, option, textarea')).off('.validate .validate-equalTo');
form.removeData('validator');
```

**Comment by nebrot** [comment]
With 1.14 there is an "destroy"-method, see #1392

**Comment by staabm** [comment]
netbrot had the right answer. will close this issue now.

feel free to ask if you have followup questions.

**Comment by RoBorg** [comment]
Awesome, thanks!
A couple of small questions:

1. Can it get added to the documentation?
2. The equalTo method adds a "blur.validate-equalTo" event, which I don't believe will be unbound, is that right?

**Comment by staabm** [comment]
1. you are more than welcome to provide the docs as a PR in https://github.com/jzaefferer/validation-content ;-)

2. I guess you are right. there is a open todo in the code[1].

[1] https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L1371

**Comment by staabm** [comment]
we should use `.one` to fix that: http://api.jquery.com/one/

but this will also not clear the event listener on `destroy`

**Comment by Arkni** [comment]
> we should use .one()[1] to fix that TODO.

I think it's the same as using `.off( ... ).on( ... )` but more readable.
IMO, the goal of that TODO is to bind the event once for all without unbinding it every time.
Anyway, until there is a better solution, using `one( ... )` makes more sense here.

> but this will also not clear the event listener on destroy

We have to add it, then.

**Comment by Arkni** [comment]
@staabm I updated my previous comment!
I will create a new issue to discuss the first point.

**Comment by staabm** [comment]
I guess we need to discuss how we can clear the listener on `destroy` - so how to find the elements on which this elements have been registered...

**Comment by Arkni** [comment]
@staabm 
see https://github.com/jzaefferer/jquery-validation/issues/1707#issuecomment-182926873
