### ISSUE TITLE
1.14.1?

### ISSUE THREAD

**Issue by LaurentGoderre** [jzaefferer/jquery-validation#1705]
It has been several months and 90 commits since last releases. Do you know if there is a new version planned anytime soon?

**Comment by staabm** [comment]
Yes, its planned. Its just around the corner, after we polished the remaining glitches

**Comment by LaurentGoderre** [comment]
Great! Do you have a ball park idea on when? Couple of weeks/months?

**Comment by staabm** [comment]
Weeks

**Comment by staabm** [comment]
Btw: I guess we will go for 1.15 :-)
