### ISSUE TITLE
[ equalTo ] bind `blur` event only once to the target of `equalTo` rule

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1707]
From #1704:
* `@staabm`:

>we should use .one()[1] to fix that TODO. but this will also not clear the event listener on destroy
>
>[1] http://api.jquery.com/one/

* `me`:

>> we should use .one()[1] to fix that TODO.

>~~I think it's the same as using `.off( ... ).on( ... )` but more readable.~~
It's not equivalent to `off( ... ).on( ... )` in the use case of `equalTo` rule. The event should still there in order to validate the element (which `equalTo` rule was attached to) after every focus out of the target.
IMO, the goal of that TODO is to bind the event once for all without unbinding it every time.
~~Anyway, until there is a better solution, using `one( ... )` makes more sense here~~.

>> but this will also not clear the event listener on destroy

>We have to add it, then.

---
The problem here is, every time the element was validated, the event was (un)binding from|to `target`.
Even if we use `.one( ... )`, the only benefit is making the code more readable and simple.

//Cc @staabm

**Comment by Arkni** [comment]
Doing some testing today I noticed that, when using `.one( ... )`, the number of handlers attached to `blur.validate-equalTo` event of the target incremented every time the element was validated (`onkeyup`). So using `one( ... )` is not an option here.
Following is a screen-cast of the result when using `one( ... )` to bind the blur event:
![anim](https://cloud.githubusercontent.com/assets/6888059/12980332/f400e198-d0d3-11e5-8a7b-15968e9fa3f5.gif)

**Comment by staabm** [comment]
thx for testing. seems we have to leave it as is then.

**Comment by Arkni** [comment]
There is a work around for fixing that, we can add a class `equalTo-blur` for example to `target`.
with this, we can avoid binding|unbinding the event every time:
```js
if ( this.settings.onfocusout )
    target.not( ".equalTo-blur" ).addClass( "equalTo-blur" ).on( "blur.validate-equalTo", function() {
        $( element ).valid();
    } );
}
```

or even better:
```js
if ( this.settings.onfocusout && target.not( ".equalTo-blur" ).length ) {
    target.addClass( "equalTo-blur" ).on( "blur.validate-equalTo", function() {
        $( element ).valid();
    } );
}
```
This will give us a way to unbind the `blur` event when destroying the plugin.

WDYT ?

**Comment by staabm** [comment]
ohh this sounds like we could kill two birds with one stone. awesome.

**Comment by Arkni** [comment]
> I would add a identifier to the classname used here, to make it obvious that it was added by jq-validate

Make sense. I'll create a PR asap :)

**Comment by staabm** [comment]
:heart:
