### ISSUE TITLE
`resetForm` should also remove `valid` class from elements

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1708]
I noticed that calling `validator.resetForm()` on a form that contain some valid elements and others invalid, only removes highlights (`error` class) and hides errors, but the `valid` class still attached to previously valid elements.

IMO, calling `resetForm()` should also remove the `valid` class.

The code responsible for this is the following ([src/core.js#L528-L534](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L528-L534)):
```js
if ( this.settings.unhighlight ) {
	for ( i = 0; elements[ i ]; i++ ) {
		this.settings.unhighlight.call( this, elements[ i ],
			this.settings.errorClass, "" );
	}
} else {
	elements.removeClass( this.settings.errorClass );
}
```

I guess it should be changed to:
```js
var classes = this.settings.errorClass + " " + this.settings.validClass
if ( this.settings.unhighlight ) {
	for ( i = 0; elements[ i ]; i++ ) {
		this.settings.unhighlight.call( this, elements[ i ], classes, "" );
	}
} else {
	elements.removeClass( classes );
}
```

I didn't create a jsfiddle as it's easy to reproduce using `demo/index.html`.

//Cc @staabm

**Comment by staabm** [comment]
:+1: agree that also valid class should be removed

**Comment by staabm** [comment]
Doesnt the `resetElements` `ELSE`-clause miss the special case for `element.type == "radio"` like the un/highlight functions have it.

**Comment by Arkni** [comment]
> the suggested patch might work, but api wise unhighlight expects the error class as 2nd arg and we pass in the error+valid class which only works because we rely on implementation details.

Yeah, I only relied on the current implementation and forgot about the semantic of the `unhighlight` method.

> maybe we can use unhighlight as before (to do a api wise removal of error state), but strip the valid class after calling unhighlight

:+1:

**Comment by Arkni** [comment]
> Doesnt the resetElements ELSE-clause miss the special case for element.type == "radio" like the un/highlight functions have it.
> 
> I guess this ELSE clause is mostly dead, as by default a unhighlight callback is defined and I guess most people wont undefine it but just redefine it..

Yes, I think so.
I tracked down that `ELSE` clause to #1323 which is the PR that added the support of using `unhighlight` inside `resetForm` instead of just removing the `error` class, but let the direct use of `elements.removeClass( ... )`.
I guess the best way is to play it safe, we don't know but we may encounter a user that set `unhightlight` to `undefined` just for fun or some use case.

**Comment by Arkni** [comment]
What should be the decision then ?

**Comment by staabm** [comment]
leave the ELSE clause as is and do the other changes as suggested above.
