### ISSUE TITLE
"this" not working in submitHandler

### ISSUE THREAD

**Issue by caioavila-arvore** [jzaefferer/jquery-validation#1713]
"this" work in "invalidHandler", but not working in "submitHandler". Why?

```javascript

var formValidation = $(".formValidate").validate({
  invalidHandler: function(event, validator) {
    // $(this) WORKING
    $(this).find(".msg_error .alert").remove();

  },
  submitHandler: function(form) {

    // $(this) NOT WORKING
    if($(this).hasClass("book_select")){

      if ($(this).find('#book_slug').length == 0) {
          alert('Select a book');
      }
      return false     
 
    }else{            
      Patterns.showLoad();
      formValidation.submit();
    }

  }
});
```

**Comment by Arkni** [comment]
The `this` inside `submitHandler` is the validator instance not the form. And `this` inside `invalidHandler` is a reference to the element where the event is being delivered; for directly bound events `this` is the element where the event was attached. In other words, it's the `form` instance.

So instead you have to use `$(form)` inside `submitHandler`.

**Comment by caioavila-arvore** [comment]
Nice! Thank you!
