### ISSUE TITLE
Error to include lib jquery.validate.js

### ISSUE THREAD

**Issue by iuri** [jzaefferer/jquery-validation#1714]
Hi there,

My website is broken because it can't find the following JS library anymore
<script type="text/javascript" src="http://jzaefferer.github.com/jquery-validation/jquery.validate.js"></script>

Where could I find the file jquery.validate.js as well as its dependencies? 

Best wishes

**Comment by diego3** [comment]
http://jqueryvalidation.org/files/jquery-validation-1.14.0.zip

**Comment by iuri** [comment]
Hi there,

I received the zip file with the source code. But I haven't found the 
file jquery.validate.js specifically.
Where's it located?

Best wishes

**Comment by Arkni** [comment]
inside `dist` folder
