### ISSUE TITLE
Impossible to validate an hidden select

### ISSUE THREAD

**Issue by romain-granai** [jzaefferer/jquery-validation#1716]
I'm using JQuery Validate + JQuery Selectmenu, JQuery Selectmenu hides the original select fields so it's impossible to validate the fields, I tried to use : 
- ignore: []
- ignore: ""

and probably 10 other solutions found on the web, but still after 2 full days of debugging, I can't make it works.

Need help, Thanks

**Comment by staabm** [comment]
how does your js code look like which initializes the validator?

**Comment by staabm** [comment]
Closing because lack of feedback
