### ISSUE TITLE
Textarea with name="post[anons]" not work. Really?

### ISSUE THREAD

**Issue by nkl90** [jzaefferer/jquery-validation#1718]
Hello! I am use CKEDITOR for my textarea fields. I try this method: http://jsfiddle.net/rohanppatil/BmZ93/8/
But it did not work. Then I try add in errorPlacement: function(error, element) { console.log(element); } and noticed that these fields do not tested. All tested fields display in console, but textarea with name="post[anons]" and name="post[text]" dont display in console. Then I found this topik on stackoverflow http://stackoverflow.com/questions/7598771/jquery-validate-textareafilled . Really? Jquery-validation dont support textareas with array in name, e.g. name="array[item]"?

**Comment by staabm** [comment]
which version of jquery-validate do you use?

AFAIR we fixed this with the yesterday released 1.15.0.

**Comment by staabm** [comment]
your fiddle uses jquery validate 1.10.0 (which is over 4 years old) and superseded by several releases.
please try a up 2 date jquery validate version.

we will re-open the issue in case you can reproduce the error on 1.15.0

**Comment by nkl90** [comment]
I update lib, but this dont work. In examples that come with plugin this is work. But in my situation this does not work. I try validate CKEDITOR field of this example https://dzone.com/articles/using-jquery-validate-plugin This my code: http://pastebin.com/Lp3ViKHm After submit form, i view in console only this elements:

> [input#post_header.form-control.error, context: input#post_header.form-control.error]
> [select#post_blog.form-control.error, context: select#post_blog.form-control.error]

post[anons] and post[text] is textarea.

**Comment by Arkni** [comment]
@nkl90 
Check this updated fiddle: http://jsfiddle.net/BmZ93/279/

The changes I did are:
* Using `editor1[]` as the name of the textarea
* Using the latest version of `jQuery validation`
* Using the version `4.4.3` of `CKEditor` which support the change event.
* And adding this piece of code:

  ```js
  // I deleted it from the HTML code
  var editor = CKEDITOR.replace('editor1');

  // Revalidate the textarea on change
  editor.on('change', function() {
      $('#editor1').valid();
  });
```

And it's working as expected.
