### ISSUE TITLE
Request for minimalistic way to add rules and messages

### ISSUE THREAD

**Issue by ashish-joshi-sr** [jzaefferer/jquery-validation#1721]
can we have support for such type of rule?

`
rules:{        
        name:{required: true, message:'Please enter service name.'},
}
`
so that we can provide only one object and minimize effort with large forms..

**Comment by staabm** [comment]
you can already add rules on a per element basis, see http://jqueryvalidation.org/rules/

Is this what you are after?

**Comment by ashish-joshi-nct** [comment]
no in above method we have to list all rules first the provide object of messages...
i require to give messages along with rule itself like below....

`
rules:{        
        name:{required: true,message:"Please enter service name."}, 
        description:{required: true,message:"Please enter short description."}, 
}
`

**Comment by staabm** [comment]
I still dont get which problem you are trying to address... where is the problem exactly?

you can even add one rule after another, still not sure what you wanne do though.
```js
$( "#myinput" ).rules( "add", {
  required: true,
  messages: {
    required: "Required input",
  }
});

$( "#myinput" ).rules( "add", {
  minlength: 2,
  messages: {
    minlength: jQuery.validator.format("Please, at least {0} characters are necessary")
  }
});
```

**Comment by ashish-joshi-nct** [comment]
Sorry for not making enough elaboration.... it not an issue but i seek some minimalistic way to add things because i have a very large form...

$("#form_myservice").validate({      
      rules:{        
        name:{required: true,message:"Please enter service name."}, 
        description:{required: true,message:"Please enter short description."}, 
        cateid:{required: true,message:"Please select dish category."}, 
      }
});

**Comment by staabm** [comment]
A minimalistic way for doing what?

**Comment by ashish-joshi-sr** [comment]
no prob. i'll try to customize it and if it works i'll add it here..
