### ISSUE TITLE
Bug CC validation

### ISSUE THREAD

**Issue by clevrweb** [jzaefferer/jquery-validation#1723]
![image](https://cloud.githubusercontent.com/assets/10823752/13401095/5fc82de6-ded0-11e5-8182-0c3b450c0b46.png)

When you enter 17 digits it is been validated

**Comment by staabm** [comment]
Why do you think it is invalid?

Per http://www.validcreditcardnumber.com its a valid number

**Comment by clevrweb** [comment]
![image](https://cloud.githubusercontent.com/assets/10823752/13404668/671ac0b2-dee0-11e5-8e5c-f0871c2dce4a.png)

Because it says that "Issuer identification number" - "We couldn't find an institution that matched your credit card number. Sorry."

**Comment by staabm** [comment]
we dont have a whitelist of all registered issuers... And having one which is up2date is not feasible.

**Comment by staabm** [comment]
I will close this for now as I dont see how we could improve here. Feel free to suggest how to get better in this case
