### ISSUE TITLE
Issue and Pull Request templates

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1726]
See:
* https://github.com/blog/2111-issue-and-pull-request-templates
* https://help.github.com/articles/creating-an-issue-template-for-your-repository/
* https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by Arkni** [comment]
Example of issue template:
```md
### Subject of the issue
Describe your issue here.

### Your environment
* version of `jquery-validate`
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo
in [JSFiddle](https://jsfiddle.net) or [JSBin](https://jsbin.com/).

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
```

**Comment by Arkni** [comment]
Example of PR template:
```md
### Checklist for this pull request

Before you submit a pull request, please make sure you have to following:

* Your code should contain tests relevant for the problem you are solving
* All new and existing tests passed
* Your commits messages format follows the jQuery [git commit message format](http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines)

#### Description
Please describe your pull request.

Thank you!
```

**Comment by staabm** [comment]
We should also mention the famouse email problem and how one can handle it / like in the readme

**Comment by Arkni** [comment]
Ha, I don't know how I forgot about this.

I think we need only to link to the notice in README, not replicating it. wdyt ?
By the way, I updated my comment about `issue template`, please check it.

**Comment by staabm** [comment]
> I think we need only to link to the notice in README, not replicating it. wdyt ?

I am ok with copying the text over instead of only linking. a lot of people are to lazy to follow a link.

I like the templates so far, feel free to PR them

**Comment by Arkni** [comment]
> I am ok with copying the text over instead of only linking. a lot of people are to lazy to follow a link.

I agree.

> I like the templates so far, feel free to PR them

Will do, but what should I use as component of the commit ? `Chore` maybe ?

**Comment by Arkni** [comment]
See #1728
