### ISSUE TITLE
Check for a single validation field?

### ISSUE THREAD

**Issue by IntellectProductions** [jzaefferer/jquery-validation#1727]
So I'm building my application in emberjs and want to know if there is a way to just somehow give the validation some rules on ONE field and only initiate that on `focusOut`. Every time they focus out on the input, I want to run maybe 1-2 rules on one field, if it returns false, it errored. If it returns true, it's valid. So then I can do the following true/false on my markup. I tried using `ember-validations`, but the errors array is ALWAYS not empty because it automatically makes all inputs have errors.. but when you cover all the rules, it doesn't erase those errors. You have to save it on the database and see if errors get returned. I just want to check client side.

I know with this plugin (I've used it multiple times before), you have a set of rules for your ENTIRE form, but I just want these simple check methods.

Thanks for any help!

**Comment by staabm** [comment]
You can validate a single element with http://jqueryvalidation.org/Validator.element/ (if this was the question)

**Comment by staabm** [comment]
Feel free to ask further questions, will close for now.
