### ISSUE TITLE
Contenteditable fails

### ISSUE THREAD

**Issue by networkedbenny** [jzaefferer/jquery-validation#1729]
When there is a contenteditable element in the form, clicking on that element to focus it causes javascript errors. This is reproducible in Firefox 44 and Chrome 49.

The error raised is "TypeError: owner is undefined" or similar.

I have a feeling this is due to [delegate()](https://github.com/jzaefferer/jquery-validation/blob/f07a267d1e7273f0994c7439a5606721cdf04edb/src/core.js#L383) in init(), as contenteditable elements do not have a this.form attribute.

Here is an example (sorry I am not smart enough to automate the focus click, that has to be done manually):
https://jsfiddle.net/w3zrrzyk/

**Comment by Arkni** [comment]
I confirm. The `delegate` method should be changed to work with `contenteditable` elements.

**Comment by chrisatomix** [comment]
This was breaking WYSIWYG functionality on a project (same console errors, plus all toolbar buttons took two clicks to trigger).

This was my quick hack of src/core.js to get it working:
```js
function delegate( event ) {
    //var validator = $.data( this.form, "validator" ),
    var validator = $.data( $(this).parents('form')[0], "validator" ),
        eventType = "on" + event.type.replace( /^validate/, "" ),
        settings = validator.settings;
    if ( settings[ eventType ] && !$( this ).is( settings.ignore ) ) {
        settings[ eventType ].call( validator, this, event );
    }
}
```
The fix doesn't sit right with me, but it seems to work for now (and I'm facing a tight deadline). Hopefully a more robust solution can be pushed through soon.

(In case it's relevant, we're using Trumbowyg as the editor)

**Comment by BenDTU** [comment]
Yup, this is an issue. It still occurs if you include contenteditable in 'ignore' and don't even want to validate it.

**Comment by staabm** [comment]
Could someone confirm that https://github.com/jzaefferer/jquery-validation/pull/1778 fixes this issue?

**Comment by djangosdk** [comment]
onfocusout still has problem with contenteditable
**Uncaught TypeError: Cannot read property 'replace' of undefined**
 ```js
// source http://stackoverflow.com/a/12254194
 function injectTrim(handler) {
  return function (element, event) {
    if (element.tagName === "TEXTAREA" || (element.tagName === "INPUT" 
                                       && element.type !== "password")) {
      element.value = $.trim(element.value);
    }
    return handler.call(this, element, event);
  };
 }
$("form").validate({
    onfocusout: injectTrim($.validator.defaults.onfocusout)
 });
```
