### ISSUE TITLE
404 errors on Microsoft CDN links

### ISSUE THREAD

**Issue by sparky672** [jzaefferer/jquery-validation#1735]
FYI - All Microsoft CDN links listed on the jqueryvalidation.org home page are no good...

[1.15.0 files on Microsoft's Ajax CDN](http://jqueryvalidation.org/#1-15-0-files-on-microsoft-s-ajax-cdn-(hotlinking-welcome):)

**Comment by staabm** [comment]
@jzaefferer anyone we can reach to get the cdn updated?

**Comment by sparky672** [comment]
I'm surprised that these CDN links have remained dead for this long.

**Comment by alphabase** [comment]
Any news or progress on this issue?

**Comment by staabm** [comment]
no response yet from the aspnet team: https://twitter.com/markusstaab/status/702782741209849856

**Comment by sparky672** [comment]
This is getting embarrassing... more than 2 weeks?

Seriously, might as well take the Microsoft CDN links off the website until the issue is resolved.

**Comment by staabm** [comment]
just removed the link to MS CDN from the homepage, until they reply to our email.

```
<h3>1.15.0 files on Microsoft's Ajax CDN (hotlinking welcome):</h3>
<ul>
	<li><a href="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js">http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js</a></li>
	<li><a href="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js">http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js</a></li>
	<li><a href="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js">http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js</a></li>
	<li><a href="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js">http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js</a></li>
	<li>Localization Files at http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/localization/messages_##.js where ## is the loc code.</li>
	<li><a href="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8/jquery.validate-vsdoc.js">vsdoc file for VisualStudio</a></li>
</ul>
```

**Comment by staabm** [comment]
Closing, see https://github.com/jzaefferer/jquery-validation/issues/1747#issuecomment-204515737
