### ISSUE TITLE
Jquery 2.2.1 broke $.validator.setDefaults

### ISSUE THREAD

**Issue by MrGorki** [jzaefferer/jquery-validation#1737]
I am using 1.14 and just updated the query library to 2.2.1 and setDefaults option got broke and don't apply the showErrors method during validation.

Did anyone notice any similar issue nowadays?

**Comment by Arkni** [comment]
It would be a plus if you can provide a [`JSfiddle`](https://jsfiddle.net/).

**Comment by MrGorki** [comment]
I found that the problem was caused by select2 not validation. Sorry.
