### ISSUE TITLE
highlight unhighlight and errorPlacement methods not always called properly for jquery selectmenu and datepicker controls

### ISSUE THREAD

**Issue by alexandis** [jzaefferer/jquery-validation#1739]
I'm not sure this attached files (quite complex things inside) would allow to reproduce the problem, because I use ajax remote validation among other types.

However, the problem i see in some cases is that
**highlight**, **unhighlight** and **errorPlacement** methods are not always called as expected when I change the value of element to be validated (in the given case it's selectmenu):

sometimes **errorPlacement** or **highlight** is not called at all when it must, because I change the value to incorrect (in given case - after drop-down list value change) - so I do not have proper error class assigning,
sometimes **unhighlight** is not called when it must, because I change the value to correct - so I do not have proper error class clearing...

I have found a hack, that suggest I should call _valid()_ for **select** twice in _change_ event of corresponding **selectmenu** element (see _CommonUtils.js_ - _decorateDropDownList_ method), otherwise after first call the proper value is still considered wrong. Anyway, when I make two calls - the error classes are cleared properly, but instead I have other issues. BTW, I experience the same issues with jquery datepicker control - I also have to call _valid()_ twice after I change its value (and close it correspondingly).

[Mail registries - LOAD_files.zip](https://github.com/jzaefferer/jquery-validation/files/167626/Mail.registries.-.LOAD_files.zip)

**Comment by alexandis** [comment]
I'm ready to close this issue meanwhile - i've moved some logic from errorPlacement to highlight (related to assigning error classes). However, before this, I'd like to know, why some of those methods are not called when changing value from erroneous to correct and back (when it looks like they should)? Is there really a bug with this for selectmenu and datepicker controls?

**Comment by Arkni** [comment]
> I'm not sure this attached files (quite complex things inside) would allow to reproduce the problem, because I use ajax remote validation among other types.

It would be a plus if you can provide a [`JSfiddle`](https://jsfiddle.net/). Also for the `Ajax` calls, you can use [`jQuery Mockjax`](https://github.com/jakerella/jquery-mockjax) to simulate the requests.

**Comment by staabm** [comment]
Which version of jquery-validate do you use?

**Comment by alexandis** [comment]
Sorry, i guess I forgot to close this issue. I've managed to resolve it.

**Comment by walkman-kuan** [comment]
I have a similar problem. That is, *highlight* isn't always called as expected when I change the value of element to be validated.

**Comment by walkman-kuan** [comment]
@alexandis What is your solution? If you can add the errorClass to elements in the **highlight** function?
