### ISSUE TITLE
Docs: examples still use version 1.14.0 instead of the latest one

### ISSUE THREAD

**Issue by Arkni** [jzaefferer/jquery-validation#1743]
Every example in the website still use the old version. And this url http://jqueryvalidation.org/files/dist/jquery.validate.min.js still resolve to http://cdn.jsdelivr.net/jquery.validation/1.14.0/jquery.validate.min.js.

It should point to latest version instead.

//cc @staabm

**Comment by Arkni** [comment]
@staabm any updates on this issue ?
I just want to make sure that [`normalizer`](http://jqueryvalidation.org/normalizer/) will work as expected.

**Comment by staabm** [comment]
I guess we should move to cdn urls, because I dont have access to the filesystem on jqueryvalidation.org

PR welcome.

**Comment by Arkni** [comment]
See jzaefferer/validation-content#23
