### ISSUE TITLE
Version Issues & Broken Links

### ISSUE THREAD

**Issue by chrisbo** [jzaefferer/jquery-validation#1747]
With reference to http://jqueryvalidation.org/ content

Compared to the http://jqueryvalidation.org/files/jquery-validation-1.15.0.zip download on the page, the Bower install is only partial and the NuGet install is version 1.14.0 (not current)

All of the following links are broken:

http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js

**Comment by Arkni** [comment]
> Compared to the http://jqueryvalidation.org/files/jquery-validation-1.15.0.zip download on the page, the Bower install is only partial

I think you mean the bower installed package lacked `test`, `demo` and some other files. Those are ignored in [`bower.json`](https://github.com/jzaefferer/jquery-validation/blob/7b0d035397bcce5372e0dfaee8ef0cc28c5006e6/bower.json#L19-L26).


> and the NuGet install is version 1.14.0 (not current)
> 
> All of the following links are broken:

Those links are down for now. Duplicate of #1735

**Comment by chrisbo** [comment]
OK. All good with me. Just thought I'd let you know

**Comment by staabm** [comment]
@chrisbo thx for the heads up.

**Comment by staabm** [comment]
Cdn was updated 

http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js

**Comment by Arkni** [comment]
#1735 should be closed too.
