### ISSUE TITLE
Missing *dist* Folder in GitHub Download

### ISSUE THREAD

**Issue by chrisbo** [jzaefferer/jquery-validation#1748]
The *dist* folder is missing in the GitHub download. Hence, in particular, the Bootstrap demo does not work and probably all the other demos

**Comment by Arkni** [comment]
You should not download the master unless you want to build it yourself, instead, you have to get the source code (or `jquery-validation-1.15.0.zip` file) attached with the release (https://github.com/jzaefferer/jquery-validation/releases/tag/1.15.0).

**Comment by chrisbo** [comment]
OK. Thanks
