### ISSUE TITLE
Using Bootstrap modals as separate "forms"

### ISSUE THREAD

**Issue by sgaul1** [jzaefferer/jquery-validation#1753]
Basically, I have this page set up where there are tons of tables and buttons being hidden dynamically using jquery.  Each table will have a few Modals (popups) that allow the user to manipulate data in these tables and update the database.  My question is would it be possible to re-create my validation rules based off which modal is opened?  It doesn't seem to be working currently and only the first modal is working as it should.

Jquery Validator Version = 1.15
Browsers = IE 11, EDGE, CHROME 49.0.2623.87

**Comment by Arkni** [comment]
Why not using one modal for each table ?

**Comment by sgaul1** [comment]
The problem is not that there is more than one modal per table, but that each modal will need to be validated separately from the rest of the modals (i.e. If validation is set for the first modal, and I try to submit from the second, it will do nothing because there was nothing input in the first modal.)

**Comment by Arkni** [comment]
From my point of view, this is a bad design.

I mean, if you have a table with columns `NAME, DESCRIPTION, QUANTITY` and you have a button for editing the current line. then the modal will have the following fields: `name`, `description` and `quantity` and it's common to all lines. In this case, you only need to use one modal per table.

**Comment by sgaul1** [comment]
There is adding, editing and deleting modals, all which allow for different data to be inserted, edited, or deleted.  You are still missing the point. Regardless of how many modals there are on the page, I can't validate more than one at a time.

**Comment by Arkni** [comment]
OK, I get it now.
So every table has 3 modals (you can reduce it to 2, one for inserting and editing (use a hidden field to distinguish between a new record and an update, and the other modal for deleting which doesn't need a validation). You just need to bind the data correctly.


> My question is would it be possible to re-create my validation rules based off which modal is opened? It doesn't seem to be working currently and only the first modal is working as it should.

If you can provide a simple JSFiddle example, I might help solving this issue.

**Comment by sgaul1** [comment]
I have attached a sample of my Javascript/JQuery.  Essentially what I would like to happen is to recreate the rules of validation whenever a new modal is opened.
[jscode.txt](https://github.com/jzaefferer/jquery-validation/files/184226/jscode.txt)

**Comment by Arkni** [comment]
You can do the following:
```js
    $('#modal2').on("shown", function () {
        var rs = ajaxRulesReponse,
            rules = {};

        $.each(rs, function (key, value) {
            rules[key] = $.validator.normalizeRule(value);
        });

        $.extends(rules, {
            modal2-1: {
                required: true,
                valueNotEquals: "0"
            }
        });

        $("#form1").validate({
            rules: rules
        })
    });
```

**Comment by sgaul1** [comment]
I get an error when I use this new code:
"JavaScript runtime error: 'ajaxRulesReponse' is undefined"

I also found a problem with my on code, instead of using "$('#modal2').on("shown",...", you have to use " $('#modal2').on("show.bs.modal",..." in order for the event to fire off and change the rules

**Comment by Arkni** [comment]
> I get an error when I use this new code:
> "JavaScript runtime error: 'ajaxRulesReponse' is undefined"

It's from your code. I'm not the one who put it there.

> I also found a problem with my on code, instead of using "$('#modal2').on("shown",...", you have to use " $('#modal2').on("show.bs.modal",..." in order for the event to fire off and change the rules

So you're using **`Bootstrap`**, here is a list of available events: http://getbootstrap.com/javascript/#modals-events

**Comment by sgaul1** [comment]
I got it from a previous post of @jzaefferer 

jzaefferer  commented on Oct 4, 2011
Would those replace the existing rules? This should do the trick, replicating some code from the init method:

var rules = ajaxRulesReponse;
$.each(rules, function(key, value) {
  rules[key] = $.validator.normalizeRule(value);
});
$(...).validate().settings.rules = rules;

Here is the link to the thread: https://github.com/jzaefferer/jquery-validation/issues/214

Its a similar issue, but wasnt able to find a solution there

**Comment by Arkni** [comment]
OK, so if I understand you problem, the solution should be like this:

```js
$( "#modal2" ).on( "show.bs.modal", function () {
    var customRules = {
            "modal2-1": {
                required: true,
                valueNotEquals: "0"
            }
        };

    $( "#form1" ).validate().settings.rules = customRules;
} );
```

**Comment by sgaul1** [comment]
`$( "#modal2" ).on( "show.bs.modal", function () {
    var customRules = {
            "modal2-1": {
                required: true,
                valueNotEquals: "0"
            }
        };

    $( "#form1" ).validate().settings.rules = customRules;
} );`

Thank you very much for your help! This has solved my issue!

**Comment by Arkni** [comment]
You're welcome :)
you can close this issue then.
