### ISSUE TITLE
Why is there both jquery.validation package and jquery-validation package ?

### ISSUE THREAD

**Issue by elhampour** [jzaefferer/jquery-validation#1762]
I want to install the jquery validation but i found that there is two package available ? what is the difference between these two ?

**Comment by Arkni** [comment]
I think you mean the **`Installation via Package Managers`**'s section in docs:
* `jquery-validation` is the name to use when using `bower` or `npm` to install this plugin.
* `jQuery.Validation` when using [`NuGet`](https://www.nuget.org/packages/jquery.validation)

**Comment by staabm** [comment]
Will close for now. Feel free to discuss further
