### ISSUE TITLE
JQuery Validation, call the valid method, is not call remote

### ISSUE THREAD

**Issue by lcyan** [jzaefferer/jquery-validation#1763]
JQuery Validation, call the valid method, is not call remote, remote valid is not work.

$id_mobile.valid()

**Comment by Arkni** [comment]
Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps.

**Comment by toabi** [comment]
I think this might be a duplicate of https://github.com/jzaefferer/jquery-validation/issues/1045

**Comment by staabm** [comment]
Agree, duplicate of #1045.

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
