### ISSUE TITLE
Validate on Javascript call

### ISSUE THREAD

**Issue by southmeadows** [jzaefferer/jquery-validation#1766]
I have a button that calls a javascript and ajax to save the form data. So there is no form submit.
I added this to the save() function and it doesnt seem to do anything. 

The field when passed over will produce an error properly which is good. But it doesnt want to check when  make this call below. 

Any ideas?

$("#formdeal").validate();

**Comment by Arkni** [comment]
The `.validate()` method does not belong inside a click handler for the form. The `.validate()` method is used for initializing the plugin on your form and only gets called once after the form is created, typically within a DOM ready handler.

If you want to validate your form whenever clicking on `save` button, use the [`valid()`](http://jqueryvalidation.org/valid/) method:
```js
$("#save_button").on("click", function() {
    // ...
    var isValid = $("#formdeal").valid():
    // ...
});
```

You can also use [`validator#form()`](http://jqueryvalidation.org/Validator.form/) method.

**Comment by southmeadows** [comment]
Thank you. That works great

-- 
Mark
