### ISSUE TITLE
defaultShowErrors is returning undefined

### ISSUE THREAD

**Issue by stephenbe** [jzaefferer/jquery-validation#1768]
### Subject of the issue

I am trying to use this.defaultShowErrors(), but it doesn't seem to work. I used the exact configuration from the doc : https://jqueryvalidation.org/validate/#showerrors

### Your environment
* version of `jquery-validate` : 1.15.0
* which browser and its version Chrome 50.0.2657.0 (64-bit)

### Steps to reproduce
http://codepen.io/stephendesjardins/pen/LNmVOO?editors=1111

### Expected behaviour
I should show a list of errors.

### Actual behaviour
Nothing happens, when I console.log(this.defaultShowErrors); It is returning undefined

**Comment by staabm** [comment]
`defaultShowErrors()` doesnt return anything, thats the reason you see `undefined`.
Errors will be rendered using highlight/unhighlight callbacks, not with a return-value, see https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L839


Whats your use case, what are you trying to achieve?

**Comment by stephenbe** [comment]
Oh okay, I didn't understand that function properly. I will be able to achieve what I want with the errorList parameter! Thank you!
