### ISSUE TITLE
Event for failed validation ?

### ISSUE THREAD

**Issue by nWidart** [jzaefferer/jquery-validation#1769]
Hello,

### Subject of the issue
I use this plugin on the bootstrap framework. I have a form that's displayed on multiple tabs. Currently, when the validation fails on tab number 2, there is no way to tell that something failed on that tab.

I would like to add a red border to the tab, that has errors in it.

To this end I'm wondering if there's an event that's triggered or something for us to hook into when the validation fails ? 
This would hopefully allow me to add the desired red borders.

### Your environment
* version of `jquery-validate`: `v1.15.0`
* which browser and its version: Chrome 50

Thank you,

**Comment by staabm** [comment]
Hi!
You should check the invalidHandler or errorPlacement callbacks/options.

https://jqueryvalidation.org/validate/

**Comment by nWidart** [comment]
Hello,

Thank you very much for the quick answer!
This helps a lot indeed, must have missed it while going through the documentation.


Thanks again.

**Comment by nWidart** [comment]
Quick follow-up, I have a form with an array of fields belonging together, ie:

```
<input class="form-control error" name="billing_address[name]" type="text" id="billing_address[name]" aria-required="true" aria-invalid="true">
<input class="form-control error" name="billing_address[street]" type="text" id="billing_address[street]" aria-required="true">
<input class="form-control valid" name="billing_address[city]" type="text" id="billing_address[city]" aria-required="true" aria-invalid="false">
```

I was expecting to be able to access the errors like so:

```
validator.invalid.billing_address.city
```

But this didn't work and had to access it like so:

```
validator.invalid['billing_address[city]']
```

Which doesn't look very nice.

Example in image: ![](https://cldup.com/9FLWcI7CDh-3000x3000.png)


Is it intended to have the strange return, or shouldn't it be something like the following: 
![](https://cldup.com/-nwYYWqrcX-2000x2000.png)

Thank you,

**Comment by staabm** [comment]
to get the object structure you propose we would need to parse the element name and group by "similar" names. This would need to be done on each validation phase so could render as a perf penalty later on.

I agree the structure you propose feels more natural, but changing this structure also would be a BC break and will break lot of exisiting code.

**Comment by nWidart** [comment]
I see, was just an idea.

Thank you for your reply and help! 😄
