### ISSUE TITLE
notEqualTo snippet in additional methods uses jQuery instead of $

### ISSUE THREAD

**Issue by cmartyniuk** [jzaefferer/jquery-validation#1773]
By using jQuery, the snippet is relying on a global jQuery object instead of correctly using $ which would be provided in a wrapper function by build tools (i.e., grunt) or requirejs, amd, etc.

in src/additional/notEqualTo.js

`jQuery.validator.addMethod( "notEqualTo", function( value, element, param ) {`

Should be: 

`$.validator.addMethod( "notEqualTo", function( value, element, param ) {`

**Comment by staabm** [comment]
Relying on `$` would not work in jQuery noConflict mode

**Comment by TrueWill** [comment]
I ran into this as well and have opened a pull request.

**Comment by staabm** [comment]
Refs https://github.com/jzaefferer/jquery-validation/pull/1793

**Comment by Steven-Pingel** [comment]
>Relying on $ would not work in jQuery noConflict mode

Doesn't appear to be a problem for the other functions in `additional-methods.js`?
