### ISSUE TITLE
Mimetype Jquery Validations Error

### ISSUE THREAD

**Issue by prafulbagai** [jzaefferer/jquery-validation#1775]
### Mimetype Jquery Validations Error

I've an input file field. I want that the file uploaded should be either image/video file. So following is jQuery Validation rule:-

    img1: {
        accept: "image/*, video/*",
    },

But when I upload a video, it gives me a `Incorrect mimetype error`. **Why?** Upoading images works fine though, but when I accept only the video, it works, ie

    img1: {
        accept: "video/*",
    },

**How can I accept images and videos at the same time?**

For the following rule:-

    img1: {
        accept: "video/*,image/*",
    },

Videos are accepted and while uploading images, it gives a mimetype error- which means anything which is referred second throws a mimetype error.

### Your environment
* version of `jquery-validate` - 1.15.0
* which browser and its version - Checked on latest Chrome & Mozilla.

### Steps to reproduce
https://jsfiddle.net/nLphsovw/1/

    <!doctype html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>Required, only audio files allowed:</title>
            <link rel="stylesheet" href="http://jqueryvalidation.org/files/demo/site-demos.css">
        </head>
        <body>
            <form id="myform">
                <label for="field">Required, audio files only: </label>
                <input type="file" class="left" id="field" name="field">
                <br/>
                <input type="submit" value="Validate!">
            </form>
            <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
            <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
            <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js"></script>
            <script>
                // just for the demos, avoids form submit
                jQuery.validator.setDefaults({
                  debug: true,
                  success: "valid"
                });
                $( "#myform" ).validate({
                  rules: {
                    field: {
                      required: true,
                      accept: "image/*,video/*"
                    }
                  }
                });
            </script>
        </body>
    </html>

### Expected behaviour
It should just accept both the video and audio files.

### Actual behaviour
It returns a **Please enter a value with a valid mimetype.**

**Comment by staabm** [comment]
Hmm looks like this commit https://github.com/jzaefferer/jquery-validation/commit/9962f627c0d75e97b30092b4d03c665e597c9d45 dropped support of the comma separator. Cant find the related PR right now.

Would be great you could PR a failing unit test.

**Comment by Arkni** [comment]
The patch in #1779 should fix this issue.

**Comment by staabm** [comment]
@prafulbagai could you confirm that #1779 fixes your issue?

**Comment by prafulbagai** [comment]
Hi Markus, Brahim

How do I apply this patch? I mean I've just directly imported
`jquery.validate.min.js` in my HTML code, ie

<script src="js/jquery/1.12.0/jquery.validate.min.js</script>

I can see the changes been done in 2 files, ie `src/additional/accept.js` and
  `test/methods.js`.
How can I make the changes and check my code? Thanks for helping.

Regards

**Comment by Arkni** [comment]
Hi @prafulbagai 

The `accept` method is part of the `additional-methods`. So, I go and built it for you, you can find the `additional-methods` files (minified and normal) in this Gist: https://gist.github.com/Arkni/5df1bd0bb426f766d004927d831d5def

**Comment by prafulbagai** [comment]
Hi Brahim,

Thanks for sharing the updated additional-methods file. It worked like a
charm.

Regards
