### ISSUE TITLE
Custom method is not validating

### ISSUE THREAD

**Issue by Masquetina** [jzaefferer/jquery-validation#1782]
### Subject of the issue
Custom method does not validate user input correctly.

### Your environment
* version of `jquery-validate` - 
https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/jquery.validate.min.js
* which browser and its version - 
Linux, FF, latest

### Steps to reproduce
https://jsfiddle.net/jw7uyu23/3/

### Expected behaviour
It should check if the user added two random numbers correctly.

### Actual behaviour
What ever user type in, it is "Not correct", even if it actually is.

I'm new at this, please help me solve it.
Thanks

**Comment by Arkni** [comment]
You have an error in your configuration, instead of passing `true` to `eval`, you should pass the `params` array or `[random_1, random_2]`. So the final code will be:
```js
$("#schoolQuery").validate({
    rules: {
        result: {
            eval: [random_1, random_2] // or just pass `params`
        }
    },
    messages: {
        result: {
            eval: "Not correct."
        }
    }
});
```

**Comment by Masquetina** [comment]
It works! Thank you.
