### ISSUE TITLE
There is a bug of errorMessage  when i update the input  tag‘s value with js..

### ISSUE THREAD

**Issue by outNapGnaw** [jzaefferer/jquery-validation#1796]
the errorMessage  wont show as usual when i try to update the input  tag‘s value with js.
code:$("#email").val("    ssss               "); The tags of errorMessage  dont show with so many speace key.

**Comment by Arkni** [comment]
When you update the value programmatically, you should re-validate your element:
```js
var validator = $("#your_form").validate({...});

// ...

var email =  $("#email");
email.val("ssss");

// Revalidate the element
validator.element(email);

// Or just trigger the keyup event
email.trigger("keyup");
```

**Comment by outNapGnaw** [comment]
thanks

**Comment by staabm** [comment]
Closing because it looks like the initial question was answered. Feel free to add further comments in case I am wrong.
