### ISSUE TITLE
Please publish a new release

### ISSUE THREAD

**Issue by ricardopolo** [jzaefferer/jquery-validation#1798]
Hi. When are you going to release a new version, that includes this fix? https://github.com/jzaefferer/jquery-validation/pull/1785

Thanks :)

**Comment by staabm** [comment]
Will try to prepare something next week

**Comment by ricardopolo** [comment]
Thanks @staabm, we'll be waiting :)

cc @codingneat

**Comment by staabm** [comment]
Hey Guys!

I am very sorry, I wasnt able to make it today. next week I am on holiday, so I think next possible release date is 1st of July.

**Comment by girtsl** [comment]
Hi,

Will you also include this PR - https://github.com/jzaefferer/jquery-validation/pull/1760?
IIRC, this was broken in 1.15 and prevents us from upgrading from 1.14. If anything, the unit tests should have been added for the changes in 1.15. and not used as an excuse for not merging the PR.

Cheers!

**Comment by staabm** [comment]
will release something after we got those PR merged.

**Comment by ricardopolo** [comment]
Thank you so much, we are waiting :)

**Comment by staabm** [comment]
After we got the deploy pipeline fixed for the docs repos, we are back at finishing the PRs and will release it after that.

Sorry for the inconvenience

**Comment by staabm** [comment]
we just releases jquery validation 1.15.1 on github.
its also published via npm.

we will change the docs on the website after all CDNs picked up the latest release.

Sorry for the long delay.

**Comment by ricardopolo** [comment]
https://github.com/aspnet/jquery-validation-unobtrusive/issues/41
