### ISSUE TITLE
Add class and atrribute when JQuery Validation return invalid result

### ISSUE THREAD

**Issue by phongphan117** [jzaefferer/jquery-validation#1799]
I use <i>Materialize CSS</i> to make a form. In framework have the form validation, but because it can't detect incorrect validation so much. So I found <i>JQuery Validation</i> plugin. I think its good to integrate with <i>Materialize CSS</i>.

In <i>Materialize CSS</i> have 2 HTML classes and 2 HTML attributes to tell validation which user input.

* When **correct**, <i>Materialize CSS</i> will add `valid` class at input field (`<input>`) to make a green `border-bottom` and add `data-success="[valid-text]"` attribute at input field label (`<label>`) tags to show the valid text under the input field(`<input>`).
* When **incorrect**, <i>Materialize CSS</i> will add `invalid` class at input field (`<input>`) to make a red `border-bottom` and add `data-error="[invalid-text]"` attribute at input field label (`<label>`) tags to show the invalid text under the input field(`<input>`).

I'll try to read the <i>JQuery Validation</i> documentation with myself but I have no idea to make it following the <i>Materialize CSS</i> conditions because I don't know how to get validation status from <i>JQuery Validation</i> to add class and add attribute follow the <i>Materialize CSS</i> conditions.

Can someone help me what should I do from my code in [jsFiddle](https://jsfiddle.net/phongphan117/6tnpu08z/)?

Ps. Sorry for my bad English.

### Your environment
* I use jQuery Validation 1.15.0 to validate my form that created with Materialize CSS 0.97.6 and jQuery 3.0.0
* I use Chrome 51 to test it.

### Steps to reproduce
https://jsfiddle.net/phongphan117/6tnpu08z/

**Comment by staabm** [comment]
I am not sure what the actual question is...?

**Comment by phongphan117** [comment]
I want to know about how to add custom attribute (such as data-error or data-success for display valid or invalud message) and add class after jQuery Validation send valid or invalid result by jQuery Validation.

**Comment by nebrot** [comment]
To change the valid and invalid class, you can use:
https://jqueryvalidation.org/validate/#validclass
https://jqueryvalidation.org/validate/#errorclass

For the custom attribute you could try these methods:
https://jqueryvalidation.org/validate/#highlight
https://jqueryvalidation.org/validate/#unhighlight

**Comment by staabm** [comment]
Will close the issue now. Feel free to ask further if things are not clear right now.
