### ISSUE TITLE
Docs: Examples don't work because of mixed content (https / http)

### ISSUE THREAD

**Issue by nebrot** [jzaefferer/jquery-validation#1808]
### Subject of the issue
The site www.jqueryvalidation.org uses https, but examples in iframe are using http-ressources:

```
http://code.jquery.com/jquery-1.11.1.min.js
http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js
http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js
```
Examples aren't working, because Browser like Firefox blocks these files.

### Steps to reproduce
1. Open https://jqueryvalidation.org/min-method
2. Open console
3. Reload
4. Log of blocked http-ressources

**Comment by staabm** [comment]
thanks for reporting. fix committed with https://github.com/jzaefferer/validation-content/commit/5fdc11f9f1e8716fc23db961962f0d548736b1e6

deployment has some problems right now, therefore it could take a few days until this gets online

**Comment by staabm** [comment]
after fixing the deployment pipeline the changes are now LIVE. might take a few hours to make it thru the cloudflare cache though.
