### ISSUE TITLE
Validation of invalid selectbox is not executed

### ISSUE THREAD

**Issue by vkurlyan** [jzaefferer/jquery-validation#1818]
### Your environment
* jquery-validate 1.15.0
* chrome 51.0.2704.106 (64-bit)

### Steps to reproduce
* open https://jsfiddle.net/vgtba9u1/9/
* set day, month and year to 1. They have valid class.
* set day, month and year to default (empty) value. 

### Expected behaviour
They must be invalid with message and error class

### Actual behaviour
They still have valid class. Validation was not fired for these fields.

**Comment by staabm** [comment]
we fixed a glitch with groups of 3 and more fields with 1.15.1. could you double check whether this issue persists for the latest version of jq-validate?

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
