### ISSUE TITLE
Incorrect filtering on radio/checkboxes

### ISSUE THREAD

**Issue by kevinboldy** [jzaefferer/jquery-validation#1819]
Hi
I believe the following excerpt of version 1.15.0 of jquery.validate.js is incorrect:

		validationTargetFor: function( element ) {
			// If radio/checkbox, validate first element in group instead
			if ( this.checkable( element ) ) {
				element = this.findByName( element.name );
			}
			// Always apply ignore filter
			return $( element ).not( this.settings.ignore )**[ 0 ]**;
		},

I BELIEVE IT SHOULD BE:

		validationTargetFor: function( element ) {
			// If radio/checkbox, validate first element in group instead
			if ( this.checkable( element ) ) {
				element = this.findByName( element.name )**[ 0 ]**;
			}
			// Always apply ignore filter
			return $( element ).not( this.settings.ignore );
		},

**Comment by staabm** [comment]
Can you show us a example, jsfiddle or other repro script which shows this is a problem?

we want this method to return a DOMElement so we unwrap the jquery set before `return`.
jquery itself can handle the case in which a jquery-wrapped-set is wrapped again with `$()` so, I dont see what the issue can be you are pointing to.

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
