### ISSUE TITLE
Jquery validation is not working in .net core 1

### ISSUE THREAD

**Issue by amirzandi** [jzaefferer/jquery-validation#1821]
Hello,

Fter I installed this plug in as a Bow in my .net core 1 project and implementing the jquery-validation.js file into my page which contains a form with some validation, I found out that my page is being refreshed after submit button has been pressed, unlike what I had in my previous MVC projects. 
The whole form was not refreshing and generally the submit button was not submitting while a field was empty. 

Is there any trick that anyone can help me on this issue? 

Thanks all.

**Comment by staabm** [comment]
When required fields are emtpy this plugin prevents form submission which is what it makes inline validation.

Could you show a example website which demonstrates your problem?

**Comment by amirzandi** [comment]
thanks for your reply. it does not work like what you have explained. Unfortunately, the project is still running on my local server and I am not able to share it for remote view. 

It actually works but the only problem that I have is, the whole page is refreshing when submit button is pressed and after the page has refreshed, it shows validation messages. 

What I had in my previous MVC5 projects was, it prevents page to be fully refreshed when a required filed was empty.

Thanks,

**Comment by ctolkien** [comment]
@amirzandi I believe your issue is probably with https://github.com/aspnet/jquery-validation-unobtrusive, not with this plugin.

**Comment by staabm** [comment]
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.
