### ISSUE TITLE
Unexpected Behaviour on Drop Downs

### ISSUE THREAD

**Issue by marcogreselin** [jzaefferer/jquery-validation#1822]
### Subject of the issue
After clicking submit, if there is an error on a `select` drop down, if you click on the dropdown it will pop twice before you can make a selection.

### Your environment
* version of `jquery-validate`: CDN.
* latest Chrome

### Steps to reproduce
Here is [JFiddle](https://jsfiddle.net/ezf68gkt/). Click on the button first. Then click on the dropdown menu and see that it pops.

### Expected behaviour
It should not pop I think.

### Actual behaviour
It pops.

**Comment by springBriz** [comment]
me either.
only in Chrome.

`this.element( element );` in onclick function.

**Comment by springBriz** [comment]
oops.
it's a bug of chrome.
and it's resolved. (version 52.0.2743.82)

**Comment by marcogreselin** [comment]
oh great thanks!
