### ISSUE TITLE
[Request] es6 model support

### ISSUE THREAD

**Issue by ifelsee** [jzaefferer/jquery-validation#1833]
it's My Fault , i set something wrong in webpack
---------
I use webpack make me use es6, so that i can import jquery in my conponents like this
```
import $ from 'jquery'
```
but it seems that `jquery-validation` doesn't support the ES6 `moldel` ?
Or maybe i didn't found how to use 
 However, thanks

**Comment by staabm** [comment]
dulicate of https://github.com/jzaefferer/jquery-validation/issues/1829
