### ISSUE TITLE
RequireJS for additional-methods

### ISSUE THREAD

**Issue by marcusds** [jzaefferer/jquery-validation#1836]
additional-methods.min.js has a requirejs requirement of "./jquery.validate.min", but this really just should be "jquery.validate.min". That way by default it'll look in the same directory, but it will also allow people to use maps or paths to change the location it looks for jquery.validate.min,js.

Otherwise, ",/jquery.validate.min" can look in a path relative to the require script, not actually additional-methods.js itself. But with it set to "jquery.validate.min" one can set a the proper path with a map.

**Comment by staabm** [comment]
the author of requirejs told us that this is the way to go: https://github.com/jzaefferer/jquery-validation/issues/1789#issuecomment-225369334

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
