### ISSUE TITLE
Custom message in html

### ISSUE THREAD

**Issue by smashraid** [jzaefferer/jquery-validation#1837]
I try to place a custom message in the html for checkbox or radio button following this [demo](https://jqueryvalidation.org/files/demo/radio-checkbox-select-demo.html) but the message for gender will be 
`<label for="gender" class="error">Please select your gender</label>`
but only said **this field is required**

i notices in the [sample](http://plnkr.co/edit/6Jbn41?p=preview) that this was working until version 1.10
![image](https://cloud.githubusercontent.com/assets/2209373/17599465/d5cfe3ce-5fc4-11e6-9469-687dcb37166a.png)

but if change to latest version doesn't work
![image](https://cloud.githubusercontent.com/assets/2209373/17599516/1a2bc06a-5fc5-11e6-9c3f-e2baeb4c157f.png)

With version 1.15.1
![image](https://cloud.githubusercontent.com/assets/2209373/17634574/ef31db18-6098-11e6-9c7f-83bfbfdffe8d.png)

**Comment by staabm** [comment]
please try 1.15.1 which is actually the latest version right now.

**Comment by smashraid** [comment]
Updated the issue with version 1.15.1 @staabm same issue

**Comment by staabm** [comment]
we need to figure out whether this was broken intentionally or not. I am not sure why it worked that way in 1.10 to be honest.

**Comment by Arkni** [comment]
The culprit is this commit 856cec06b822ff9e33d837169a5044bfee0a7131 which is a patch to fix #430

**Comment by smashraid** [comment]
Can I revert that change? Or this is not supported anymore?

**Comment by Arkni** [comment]
I'm afraid you can't as it seems the change was intentional by the author.
I think, you can use `data-msg|data-msg-*` attribute to define your message instead of using an existing label. That way, `jquery-validation` will use that error message instead of the default one.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
