### ISSUE TITLE
date validation broken for many years

### ISSUE THREAD

**Issue by jsmad** [jzaefferer/jquery-validation#1845]
### Subject of the issue
For more than 5 years now, I've been using my own fork of this plugin. Every year or so, I download the latest version (now at 1.15.1) like I always do and give it a go to see if the "date" was ever fixed.

I don't know the politics, why the devs refuse to fix this issue, but because I find a lot of people asking for help on this, I decided to offer my (rather simplistic) solution, which simply verifies the overall format of the date but does not check its actual validity:

Find the "date:" function and replace it with the following:

```javascript
date: function( value, element ) {
	return value.match(/^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$/);
},
```

### Your environment
* version of `jquery-validate`: all of them
* which browser and its version: the issue appears mostly in Chrome

### Steps to reproduce
Just validate an input field for a date with dd/mm/yyyy or dd-mm-yyyy  format

### Expected behaviour
Verify a valid date

### Actual behaviour
Fails to verify

**Comment by staabm** [comment]
see the docs for the method: https://jqueryvalidation.org/date-method/

> This method should not be used, since it relies on the new Date constructor, which behaves very differently across browsers and locales. Use dateISO instead or one of the locale specific methods (in localizations/ and additional-methods.js).

we should remove this method entirely in a new major version. fixing it for a certain format, like you did is not a proper solution either.
