### ISSUE TITLE
.rules function only adding rule to first element selected

### ISSUE THREAD

**Issue by JBratteli** [jzaefferer/jquery-validation#1853]
jquery-validate 1.15.0
Chrome 52

$('[name_="FirstName"], [name_="LastName"], [name*="Message"]', form).rules('add', { required: true });
ought to make all elements with FirstName, LastName, or Message in the name required. Instead it just makes the first element that matches the selector required.

I was able to work around the bug by altering the code to:
$('[name_="FirstName"]', form).rules('add', { required: true });
$('[name_="LastName"]', form).rules('add', { required: true });
$('[name*="Message"]', form).rules('add', { required: true });

To test my theory, I also tried:
$('[name_="Name"]', form).rules('add', { required: true });
$('[name_="Message"]', form).rules('add', { required: true });
As I thought, that only selected one of the Name fields.

**Comment by staabm** [comment]
you should use `.each` as this is expected behavour.
