### ISSUE TITLE
How to add a custom message for the extension-method

### ISSUE THREAD

**Issue by suture** [jzaefferer/jquery-validation#1863]
Using the code example shown on this page
https://jqueryvalidation.org/extension-method/

How can I add a custom message?
Currently the error message reads "Please enter a value with a valid extension."

I'd like to change it to something else.

**Comment by kpduncan** [comment]
From the .rules() page:

> Both rules and messages can be specified using data attributes, using data-msg (a generic, not
> method specific message), `data-msg-[method]` and `data-rule-[method`].

Another reference with a list of rules: Using the jQuery Validate Plugin with HTML5 Data Attribute Rules

**Comment by suture** [comment]
Many thanks. I ended up creating a custom method which solved the problem.
