### ISSUE TITLE
Support jquery3?

### ISSUE THREAD

**Issue by Guymestef** [jzaefferer/jquery-validation#1866]
### Subject of the issue

When I bundle my scripts with webpack, jquery.validate require at most jquery 2. So I have jquery 2 and jquery 3 bundled instead of just jquery 3.
### Your environment
- version of `jquery-validate`: 1.15.1
### Steps to reproduce

Bundle jquery 3 and jquery.validate with webpack
### Expected behaviour

jquery.validate should support jquery 3
### Actual behaviour

jquery.validate supports at most jquery 2

Allowing jquery 3 in the packages.json should be enough to solve the issue. But I didn't check if jquery.validate is fully compatible with jquery 3.

**Comment by staabm** [comment]
PR welcome

**Comment by RehanSaeed** [comment]
This issue suggests that jQuery 3.0 is not supported: 

https://github.com/jzaefferer/jquery-validation/issues/1882

**Comment by david-witt-fluid** [comment]
I've been using this plugin with jQuery 3.0 and the migration plugin. So far, everything seems to be working. The only issue I've come across has been a warning from the migrate deprecation warning:

jQuery.expr[":"] is now jQuery.expr.pseudos

It maybe a simple case of find and replace to swap out one method for another.

**Comment by staabm** [comment]
@david-witt-fluid  see https://github.com/jzaefferer/jquery-validation/pull/1814
