### ISSUE TITLE
New Additional Methods For Files

### ISSUE THREAD

**Issue by ghost** [jzaefferer/jquery-validation#1869]
### Subject of the issue

Looking for input on adding new additional methods.
### Your environment
- jQuery Version v1.15.0
- Chrome 53.0.2785.116 m (64-bit)
- Java Web App - Using [WET](https://github.com/wet-boew/wet-boew)
### Behaviour of methods

There is a total of five method relating to file inputs.

Method 1 - `fileMinimum`: Forces file input to have a minimum number of files
Method 2 - `fileMaximum`: Forces file input to have a maximum number of files
Method 3 - `fileRange`: Forces file input to have a set number of files in a number range
Method 4 - `fileLimit`: Forces file input to have a set number of files
Method 5 - `maxsize`: Forces the file input to stay under a set size limit

These method would remove the need for the `required="required"` the issue with this attribute is after user attaches file the validation don't clear until user leaves the focus of the file input (clicks another input or the web page). Issue wasn't able to address with file inputs with same name. Instead I just added a method to the click event of the form submit that does a blur focus on those inputs that way they'll validate.
### JavaScript

``` javascript
( function() {

    function bindChangeEvent( element, params ) {
        $("form input[type=file]").each(function() {
            var name = $(this).attr("name");
            if(name === $(element).attr("name")) {
                $(this).bind("change", function(){
                    $(this).blur().focus();
                });
            }
        });
    }

    function findFiles( method, element, params ) {
        var number = 0;
        if($(element).val()){
            number = 1;      
        }
        $("#upload input[type=file]").each(function() {
            var value = $(this).val();
            var name = $(this).attr("name");
            if(value && name === $(element).attr("name")) {
                number++;
            }
        });
        switch(method) {
            case 'min':
                if(n >= params) {
                    return true;
                }
                break;
            case 'max':
                if(n <= params && n > 0) {
                    return true;
                }
                break;
            case 'range':
                if(n >= params[0] && n <= params[1]) {
                    return true;
                }
                break;
            case 'limit':
                if(n === params){
                    return true;
                }
                break;
        }
        return false;
    }

    $.validator.addMethod( "fileMinimum", function( value, element, params ) {
        bindChangeEvent( element, params );
        return findFiles( 'min', element, params );
    }, $.validator.format( "Please attach at least {0} document(s)" ) );

    $.validator.addMethod( "fileMaximum", function( value, element, params ) {
        bindChangeEvent( element, params );
        return findFiles( 'max', element, params );
    }, $.validator.format( "Please attach no more than {0} document(s)" ) );

    $.validator.addMethod( "fileRange", function( value, element, params ) {
        bindChangeEvent( element, params );
        return findFiles( 'range', element, params );
    }, $.validator.format( "Please attach between {0} and {1} document(s)" ) );

    $.validator.addMethod( "fileLimit", function( value, element, params ) {
        bindChangeEvent( element, params );
        return findFiles( 'limit', element, params );
    }, $.validator.format( "Please attach {0} document(s)" ) );
    $.validator.addMethod( "maxsize", function( value, element, param ) {
        var i;
        bindChangeEvent( element, params );
        for ( i = 0; i < element.files.length; i++ ) {
            if(element.files[i].size > (1048576 * param)) {
                return false;
            }
        }
        return true;
    }, $.validator.format( "Document(s) size must not exceed {0} MB" ) );

}() );
```
### JavaScript Minify

``` javascript
!function(){
    function b(c,d){$("#upload input[type=file]").each(function(){var b=$(this).attr("name");b===$(c).attr("name")&&$(this).bind("change",function(){$(this).blur().focus()})})}
    function e(a,c,d){var n=0;$("#upload input[type=file]").each(function(){var b=$(this).val(),e=$(this).attr("name");b&&e===$(c).attr("name")&&n++});switch(a){case"min":if(n>=d)return!0;break;case"max":if(n<=d&&n>0)return!0;break;case"range":if(n>=d[0]&&n<=d[1])return!0;break;case"limit":if(n===d)return!0;break;}return!1}
    a.validator.addMethod("fileMinimum",function(a,c,d){b(c,d);return e("min",c,d);},a.validator.format("Please attach at least {0} document(s)")),
    a.validator.addMethod("fileMaximum",function(a,c,d){b(c,d);return e("max",c,d);},a.validator.format("Please attach no more than {0} document(s)")),
    a.validator.addMethod("fileRange",function(a,c,d){b(c,d);return e("range",c,d);},a.validator.format("Please attach between {0} and {1} document(s)")),
    a.validator.addMethod("fileLimit",function(a,c,d){b(c,d);return e("limit",c,d);},a.validator.format("Please attach {0} document(s)")),
    a.validator.addMethod("maxsize",function(a,c,d){b(c,d);var e;for(e=0;e<c.files.length;e++)if(c.files[e].size>1048576*d)return!1;return!0;},a.validator.format("Documents size must not exceed {0} MB"))
}()
```

**Comment by cybersubtype** [comment]
Sorry had issue with old account. This is my post info any one wants to bring input on this.

**Comment by cybersubtype** [comment]
Sorry I had to open an new account. I'm still working on this and their is a few bugs with the code above. When I get time late today I'll create a live demo on my website with the bugs fixed.

**Comment by cybersubtype** [comment]
@Arkni or @staabm Have any input? I worked out some bugs but can't get it too work with out a function running on form submit in one scenario. View [demo and updated code](https://www.cybersubtype.ca/apps/wet-demos/forms/) at my blog.

**Comment by Arkni** [comment]
@cybersubtype 
Sorry, I wasn't able to respond in time.

>Cause their both using the same name attribute, but this is require with the language I'm using on my server.

As you may know, `jquery-validation` requires that every element has a unique name except for `radio` and `checkbox` elements which may share the same name.

See this [link](https://jqueryvalidation.org/reference/#link-markup-recommendations) for a reference:
>**Markup recommendations**
>
Mandated: A 'name' attribute is required for all input elements needing validation, and the plugin will not work without this. A 'name' attribute must also be unique to the form, as this is how the plugin keeps track of all input elements. However, each group of radio or checkbox elements will share the same 'name' since the value of this grouping represents a single piece of the form data.
>
Optionally: Each input can have a label associated with it, where the 'for' attribute of the label refers to the 'id' attribute of the input. It's also a common practice to have 'id' and 'name' attributes with the same value, although keep in mind that since this plugin does not use the 'id' attribute, this is not mandatory.

With the current version of the plugin, there is no way you can validate your file elements without making changes to the plugin itself in order to handle elements with same name. For the records, there is an open pull request #717 (there is also a closed one #1330) which may seem like a good start to you.

So, as a conclusion, you have to give each of your file elements a unique name, otherwise only the first one will be validated.

**Comment by cybersubtype** [comment]
This is disappointing, but understandable. Current application I developing is using WET (government bootstrap) so I'm limited to jQuery validation. At this current time I well continue to use these additional methods plus another method to validate the form on submit for none unique names and the language I use requires for file inputs.

**Comment by cybersubtype** [comment]
@Arkni Thanks anyway. You can close this and if anyone is interested in my work around while I wait too see if I can change validations tools they can view it here: https://www.cybersubtype.ca/apps/wet-demos/form-validation/file/

**Comment by staabm** [comment]
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.
