### ISSUE TITLE
submitHandler not firing

### ISSUE THREAD

**Issue by dwg-andy** [jzaefferer/jquery-validation#1870]
### Subject of the issue
submitHandler not firing

### Your environment
* version of `jquery-validate` 1.15.0
* which browser and its version Chrome 53.0.2785.116

### Steps to reproduce
Complete the form with all required fields and submit.     
You'll notice that if you incorrectly complete the email or phone field, those validate just fine. However the simple submitHandler never fires.  I also tried just using submitHandler with no rules, and got the same result.  
https://jsfiddle.net/usznkfzs/.

### Expected behaviour
Ideally email and phone fields would be validated by the plugin then it would fire the function in the submitHandler

### Actual behaviour
Email and phone are validated, however nothing fires in the submitHandler once all fields are validated.
I've also tried using debug:true rather than preventDefault. However debug:true doesn't seem to do anything either for me.

**Comment by kaanyurukcu** [comment]
Hi there,

You shouldn't be attaching a handler on the submit event of the form, you should let validate plugin handle the event for you and then you can do your stuff in submitHandler prop of validate plugin.

Here's the correct fiddle: [https://jsfiddle.net/usznkfzs/1/](https://jsfiddle.net/usznkfzs/1/)

**Comment by dwg-andy** [comment]
ah. that makes sense.  thanks.
