### ISSUE TITLE
Missing dist folder again

### ISSUE THREAD

**Issue by denisz1** [jzaefferer/jquery-validation#1877]
Using this package via Bower. [Once again](https://github.com/jzaefferer/jquery-validation/issues/1420) the package is missing the `dist` folder.

So it breaks building of existing system. i.e. it is breaking change.

Please please please put it back.

**Comment by mgol** [comment]
The `dist` folder is not missing, see: https://github.com/jzaefferer/jquery-validation/tree/1.15.1.

You should not use the `master` version but a released one.

**Comment by jrock2004** [comment]
So I have updated to this version and one person on my team is still not getting dist folder. Any ideas?

**Comment by mgol** [comment]
@jrock2004 I've just checked and it's there:
```
$ bower install jquery-validation@1.15.1
$ ls bower_components/jquery-validation/dist
additional-methods.js     additional-methods.min.js jquery.validate.js        jquery.validate.min.js
```

**Comment by smithaitufe** [comment]
I just followed your suggestion. I used bower install jquery-validation@1.15.1 but I can't find the dist folder. Is there something else that must be done to see it?

**Comment by mgol** [comment]
@smithaitufe Make sure you use the latest bower (currently 1.8.0) and clear its cache by `bower cache clean`. You may also remove `bower_components` to a the clear state.

In any case, the `dist` folder is definitely in the package. If you don't have it, this is an issue with bower, not with the jquery-validation plugin.

**Comment by smithaitufe** [comment]
@mgol
Thanks. I did that and got it working.
