### ISSUE TITLE
Homepage: Current version outdated (1.15.0 superceded by 1.15.1)

### ISSUE THREAD

**Issue by Chealer** [jzaefferer/jquery-validation#1881]
According to [the homepage](https://jqueryvalidation.org/), the current version is 1.15.0. This version was superceded by 1.15.1 in July: https://github.com/jzaefferer/jquery-validation/releases/tag/1.15.1

**Comment by Arkni** [comment]
ping @staabm

**Comment by staabm** [comment]
just redeployed the contents and invalidated the cloudflare cache. thx for the heads up. should be fine now.

**Comment by Chealer** [comment]
Does this mean it should be fixed now now? I am still seeing 1.15.0.

**Comment by staabm** [comment]
I will get in contact with our webserver admin.

**Comment by staabm** [comment]
Sollte jetzt passen.

**Comment by Chealer** [comment]
I am still seeing the version as 1.15.0.

**Comment by staabm** [comment]
Did you try a force reload in your browser?

**Comment by kodecount** [comment]
@staabm I only see 1.15.1 on IE (I'm on a Canadian Network).

**Comment by Chealer** [comment]
Yes. My Firefox 45.4.0 still shows 1.15.0. It resolves the domain name https://jqueryvalidation.org/ to 104.28.20.119:443

Chromium on the same machine displays 1.15.1.

I have retried an hour after writing the above, and I now get 1.15.1 on Firefox, from the same IP address.

I have just retried twice and obtained 1.15.1, then went back to 1.15.0.

**Comment by kodecount** [comment]
@Chealer I agree it is random. Sometimes even IE will revert to 1.15.0.

**Comment by staabm** [comment]
Hmm maybe there is an upstream issue with cloudflare..
