### ISSUE TITLE
size() Function Has Been Remove From jQuery Since 3.0

### ISSUE THREAD

**Issue by GrayYoung** [jzaefferer/jquery-validation#1882]
Just hope author can make jquery.validation work out on jquery 3.0 .

**Comment by RehanSaeed** [comment]
I think the `size()` you are referring to is another function in the script also called `size()` and not from jQuery. https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L575

Are you finding any problems with using jQuery 3.0 with this script?

**Comment by staabm** [comment]
@RehanSaeed  is right. we internally have a size() method. we dont rely on the deprecated jquery method (at least not in the core.js).

in case you spotted it somewhere else, please get back to us.
