### ISSUE TITLE
Documentation for v1.11.1

### ISSUE THREAD

**Issue by airtonix** [jzaefferer/jquery-validation#1883]
Where is the documentation for v1.11.1 ?

I have been forced to work on a project someone else started that has this library installed.

**Comment by staabm** [comment]
the offical docs are at https://jqueryvalidation.org/ and we dont version the docs itself (except mentioning on a per method/feature basis when it was added)

**Comment by airtonix** [comment]
Wow. All due respect, but that's a horrible experience for developers.

Highly suggest you start using documentation.js to publish the docs as part
of the readme here in github.

Bonus: you get rid of your hosting costs with that WordPress site.

**Comment by staabm** [comment]
@airtonix feel free to provide your freetime (like we do) to progress the project further into a better future ;-)
