### ISSUE TITLE
jQuery Validation Plugin considers multiple empty space as valid to pass required field validation

### ISSUE THREAD

**Issue by cheonhyangzhang** [jzaefferer/jquery-validation#1886]
### Subject of the issue
Required fields should mean user need to input something. Just putting spaces should not pass required validation.

### Your environment
* version of `jquery-validate`： 1.15.0
* All browser.

### Steps to reproduce
https://jqueryvalidation.org/files/demo/ Try in the demo, when put name field with only a few spaces, then click "submit" no error message showed. It thinks input with spaces only pass the required validation.

### Expected behaviour
jQuery validation should not pass for just blank spaces input.

### Actual behaviour
jQuery validation considers a pass for just blank spaces input.

**Comment by Arkni** [comment]
@cheonhyangzhang 

Trimming white spaces was dropped from core in 2ad0ca82daf091fc692018b38e01e896fd304015 as part of a fix for issue #1498, also see this comment https://github.com/jzaefferer/jquery-validation/issues/1354#issuecomment-67168988.

As a solution, a normalization layer was added in #1609 ([docs](https://jqueryvalidation.org/normalizer/)) that can be used to transform the value of an element before validation. This feature was available since `1.15.0`. In other words, you can do something like this:
```js
$("#myForm").validate({
  rules: {
    username: {
      required: true,
      // Using the normalizer to trim the value of the element
      // before validating it.
      normalizer: function(value) {
        // Note: the value of `this` inside the `normalizer` is the corresponding
        // DOMElement. In this example, `this` reference the `username` element.
        // Trim the value of the input
        return $.trim(value);
      }
    }
  }
});
```

**Comment by cheonhyangzhang** [comment]
@Arkni Thanks for the info.

**Comment by cheonhyangzhang** [comment]
@Arkni 
In the code snippet above, the normalizer is defined inside of rule for a certain field, is there a way to apply a normalizer for all required fields?  Instead of having normalizer function individually for each field

**Comment by Arkni** [comment]
I'm afraid you cannot do that in the main time, as the normalization layer is bound to the element level (as if it was a rule).

**Comment by cheonhyangzhang** [comment]
@Arkni 

I think I can use jQuery.validator.addClassRules() as a workaround. However, this requires all the required field has the same class 'required'. 
https://jqueryvalidation.org/jQuery.validator.addClassRules/

```
jQuery.validator.addClassRules("required", {
  required: true,
  normalizer: function(value) {
    return $.trim(value);
  }
});
```

**Comment by Arkni** [comment]
That might work.

I think we may change the behaviour of the normalization layer to run for all fields if it's present in the top level (the same level as `rules`) without affecting the current behaviour, that way you can transform the values of a set of elements without attaching the same normalizer to the aforementioned elements, and you can override it on element level by specifying a normalizer for the specific element that you want to transform differently.

In pseudo code, this will look like:
```js
$("#myForm").validate({
  normalizer: function(value) {
    // Trim the value of every element
    return $.trim(value);
  },
  rules: {
    username: {
      required: true,
      // Here, we override the global normalizer
      normalizer: function(value) {
        value = value.replace("something", "new thing");
        return $.trim(value);
      }
    }
  }
});
```
What do you think ?

**Comment by cheonhyangzhang** [comment]
Yes. I think this makes much more sense. 

Are you saying this is already working in the current version or it will be planned to be implemented in future version?

**Comment by Arkni** [comment]
Not implemented yet, but I hope it well be planned for the next release.
I will try to implement it when time allows, as currently don't have the bandwidth to work on it.

/cc @staabm

**Comment by cheonhyangzhang** [comment]
@Arkni 
That sounds great. 
Thanks for the help.

**Comment by staabm** [comment]
lets discuss the topic on a PR.

**Comment by Arkni** [comment]
@cheonhyangzhang @staabm 
I've opened #1905 to address this.

**Comment by arnabmunshi** [comment]
` rules: {
      username: {
        required: true,
        normalizer: function(value) {
          return $.trim(value);
        }
      }
    },`
its worked ...
