### ISSUE TITLE
About messages_az under src/localization

### ISSUE THREAD

**Issue by pvnr0082t** [jzaefferer/jquery-validation#1890]
Hi @jzaefferer ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs), we want to host this library.
I found that there is `messages_az` under `src/localization` folder. Should it be `messages_az.js`?
Could you please help me confirm this? Thank you.

https://github.com/cdnjs/cdnjs/issues/9491
https://github.com/cdnjs/cdnjs/pull/9568

**Comment by staabm** [comment]
thx for the headsup. will be fixed in the next release.
