### ISSUE TITLE
form.submit crashes Browser

### ISSUE THREAD

**Issue by magic-77** [jzaefferer/jquery-validation#1903]
Hi,
i'm using the latest Version.
So after all Fields are valid, and $(form).submit() is called the Browser stucks ans crashes.
Using debug Function show me endless entries with "has no name assigned"

So what i'm doing wrong?

And here is a demo, i reduced the Form Fields to two.
http://eee-ltd.com/_proto3/initiative-application.html

this is the code i'm using

    `$formPage.validate({
      debug: true,
      focusInvalid: false,
      errorClass: 'invalid',
      errorElement: 'em',
      ignore: '.selectric-input',
      errorPlacement: function(error, element) {
        // empty Function removes Error Messages
      },
      invalidHandler: function(error, validator) {
        if (validator.errorList.length >= 1) {

          var _notValidList = validator.errorList,
            _notValidElements = [],
            _select,
            _formGroup,
            _targetAccordion;

          $(_notValidList).each(function(i, e) {
            _notValidElements.push($(e.element)[0]);
            _formGroup = $(e.element).closest('.form__group');
            _formGroup.addClass('open');
            _targetAccordion = _formGroup.children('.accordion');

            if (!_targetAccordion.hasClass('active')) {
              _targetAccordion.addClass('active');
              _targetAccordion.next().addClass('open');
            }
          });
        }
      },
      highlight: function(element, errorClass, validClass) {
        switch ($(element)[0].type) {
          case 'select-one':
            $(element).offsetParent().next().addClass(errorClass);
            break;
          case 'file':
            $(element).next().addClass(errorClass);
            break;
          case 'text':
            $(element).addClass(errorClass);
            break;
          case 'checkbox':
            $(element).offsetParent().addClass(errorClass);
            break;
        }
      },
      unhighlight: function(element, errorClass, validClass) {
          switch ($(element)[0].type) {
            case 'select-one':
              $(element).offsetParent().next().removeClass(errorClass);
              break;
            case 'file':
              $(element).next().removeClass(errorClass);
              break;
            case 'text':
              $(element).removeClass(errorClass);
              break;
            case 'checkbox':
              $(element).offsetParent().removeClass(errorClass);
              break;
          }
      },
      submitHandler: function(form) {
          $(form).submit();
      }
    });`

and HTML (simplyfied)

    `<form name="form__initapp" action="/index.html" method="post" class="form__initapp form__page">
	<label class="form__label"><div>SALUTATION <span class="form__mandatory">*</span></div></label>
	<div class="form__select-wrap">
		<select class="form__select" name="tx_initiativeapplication_registration[newInitiativeapplication][salutation]" required>
			<option value="" disabled selected>Please select ...</option>
			<option value="4" class="option-child">Mr</option>
			<option value="5" class="option-child">Mrs</option>
			<option value="6" class="option-child">Miss</option>
			<option value="7" class="option-child">Ms</option>
		</select>
	</div>

	<label class="form__label"><div>FIRST NAME <span class="form__mandatory">*</span></div></label>
	<input type="text" name="tx_initiativeapplication_registration[newInitiativeapplication][firstName]" maxlength="20" class="form__input" required>

	<label class="form__label"><div>COUNTRY <span class="form__mandatory">*</span></div></label>
	<input type="text" name="tx_initiativeapplication_registration[newInitiativeapplication][country]" maxlength="20" class="form__input" required>

	<div class="form__checkbox">
		<input type="checkbox" name="terms" value="None" id="cdsterms" class="" required>
		<label for="cdsterms"></label>
	</div>
</form>`

**Comment by staabm** [comment]
please provide a jsfiddle which reproduces the error.

**Comment by magic-77** [comment]
The Full Version of the Form
eee-ltd.com/_proto3/initiative-application.html

**Comment by magic-77** [comment]
ok, i found out, that the buttons itself had no name. so i improved the html.
Now the submit is called, but the browser temporary freeze, and i get this error message

    `Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.test (native)
    at Array.<anonymous> (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:1769:21)
    at http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:2322:22
    at superMatcher (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:2543:12)
    at Array.<anonymous> (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:1989:6)
    at http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:2322:22
    at superMatcher (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:2543:12)
    at Sizzle.select (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:2722:44)
    at Sizzle (http://localhost:3000/typo3conf/ext/basicprovider/Resources/Public/assets/js/cds.min.js:890:9)`

**Comment by magic-77** [comment]
Here is a jsfiddle too
https://jsfiddle.net/npyv65yc/1/

**Comment by Arkni** [comment]
@magic-77 
See https://jqueryvalidation.org/documentation/#link-too-much-recursion

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
