### ISSUE TITLE
Validation not using pattern attribute

### ISSUE THREAD

**Issue by peiche** [jzaefferer/jquery-validation#1916]
I would expect an input field's `pattern` attribute to be taken into account when being validated, but it's not.

### Your environment
* jquery-validate v1.15
* Chrome 55

### Steps to reproduce
In defining a field with the `required` and `pattern` attributes, the form's validation does not validate according to the pattern.
Example: http://codepen.io/peiche/pen/egZYYE/

### Expected behaviour
The form should be prevented from submitting if the value of the field does not match the pattern.

### Actual behaviour
The form submits, regardless of whether the value of the field matches the pattern or not. To validate according to a pattern, the pattern must be defined in a custom validation method. This is not ideal, requiring the pattern to live in two places (the markup and javascript), resulting in duplicate code.

**Comment by Arkni** [comment]
`pattern` method is not part of the core, you should include the `additional` methods to get it.

**Comment by peiche** [comment]
Thanks for the help. That's exactly what I was looking for.
