### ISSUE TITLE
Have a way to know which rule has failed for an input

### ISSUE THREAD

**Issue by EPinci** [jzaefferer/jquery-validation#1917]
### Subject of the issue
Using the (un)highlight function there's no way of knowing which rule has failed for the input to be validated. Having a way to know which rule has failed would allow to customize the highlighting according (e.g.: having a different icon shown for required vs invalid format)

### Your environment
jquery validate 1.16.0

### Steps to reproduce
n/a

**Comment by staabm** [comment]
Closing this one in favor of #1925 which requires the same feature but contains more details.
