### ISSUE TITLE
jquery-validtion shake input field issue.

### ISSUE THREAD

**Issue by alexrmacleod** [jzaefferer/jquery-validation#1919]
When a user fills in their email incorrectly on the id=“subscribeform” first input field found [http://goeasysmile.com/](url) this input field will shake from left to right. This is great and a good visual indication that something is wrong.

However;

Every letter typed after that point causes the input field to continue to shake making for a very bad typing user experience when the user is trying to correct their email.

This Issue: The problem is with the validate.js plugin. Once the field is marked as incorrect, the plugin will check for the correct value on each press. Usually the Error message will be below the textbox, it will hide once user enter correct format. But in our case its animation, so it keeps running.

That's why its buffered

Solution? How would I let validate.js know when the id=“subscribeform” input field is empty and turn off the invalid status as the user makes a second attempt at their email entry? Perhaps somewhere in main.js?

As always any help appreciated.

**Comment by Arkni** [comment]
You can try disabling the [`onkeyup`](https://jqueryvalidation.org/validate/#onkeyup) handler:
```js
$( "#myForm" ).validate({
  onkeyup: false,
  // ...
});
```

**Comment by staabm** [comment]
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.
