### ISSUE TITLE
Check validate true or false from server

### ISSUE THREAD

**Issue by spizzi77** [jzaefferer/jquery-validation#1927]
Hy All,
Sorry if i write here, but i need of an help, i'm using this customizable plugin to validate big form data from my project at work, i have a probem hope you can help me.
I need sometimes to do some Ajax request to define if required true or false but on the submit handlers, i explain better, some time an input can be required true or false only when i send some parameter to the DB and the DB answer me, yes for that parameters input must be required or not.
So i do the validate of the form but in the mean time i must do an Ajax call to the server that says me yes that input must be required or not, i seen the remote method but i notified that it's on keyup i need of some other.
I tried also doing an Ajax call with a function example using "depends" required:{depends:myAjaxCall} 
but i notified that ajax request starts for 3/4 times,but i must try the  stopPropagation();
In last words before do the submit of the form in the submitHandler, before this, i must do an Ajax Call(but when i click the submit button for sure in that moment) and only one time at the server, and i must send to the server differents parameters, with those parameters server call the DB and answers me INPUT REQUIRED or INPUT NOT REQUIRED, if required i must stop the validation and write the message "input required" near the label if not required continue and submits form.
Any help?

**Comment by spizzi77** [comment]
Hy all,
I resolved in this way and works fine...in the submitHandler i inserted and event.preventDefault, and after at the click of the submit button i do this:
```javascript
//At the click of the submit button check if the form is valid
    $('#confermaCensimentoPF').click(function() {
    	 var formValida = $('#censimentoPFForm').valid();
         if (formValida == true){
                //if the form is valid check if we need the fiscal code
         	controllaTin = controlliTinResidente();
               //if we don't need the fiscal code go on and save on the db
         	if (controllaTin != 'true'){
	         	compattaPersoneFisiche();
         	}
         	else{//If we need the fiscale code add rules required
				$('[name=codFiscEstRes]').rules('add', {
					required:true,	
					messages:{required:'Codice Tin Obbligatorio'},
				});
         	}
         }
    });	
```

**Comment by sparky672** [comment]
> _"in the submitHandler i inserted and event.preventDefault"_

That makes no sense.  There is no `event` argument available within the `submitHandler` and there is no default action to prevent here.  In other words if you have an `event.preventDefault()` within your `submitHandler`, it's totally superfluous and unnecessary.

**Comment by spizzi77** [comment]
Hello Sparky,
Yes you are in right, no need to insert event.preventDefault(), when i wrote the message i just starting using jqery validation and i didn't know all the functionality, but i can attach a deferred object out of the submit handler with no problem, btw in all my project in production i'm using jquery validation since more that 1 year and i must say that it's really perfect to manage forms and events, it's very customizable i'm using it also with bootstrap 4.1.1 with no problems.
Have good days
Spizzi
