### ISSUE TITLE
Validation for Indian Number

### ISSUE THREAD

**Issue by vishalsingh119** [jzaefferer/jquery-validation#1929]
I try to put validation for mobile number.as code given at website <input    class="required" name="field" id="field" > and js is field: {required: true,	digit:true,minlength:10,maxlength:13} but validation not working.

If any one have any idea to validate mobile number as indian standard.Kinldy share with me.

**Comment by staabm** [comment]
Please provide a jsfiddle or other code which reproduces your issue

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
