### ISSUE TITLE
Better form design demo

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/jquery-validation#441]
The current demos were probably inspired by some now years-old design from the same guys: http://petelepage.com/downloads/v1-Form-design-crib-sheet1.png

Should put together something new based on the recommendations in there, most of all the validation.

**Comment by Arkni** [comment]
Would you like to use [Twitter Bootstrap](https://github.com/twbs/bootstrap) or another framework (UIKit, Semantic UI, ..) to style the demos  or Just custom CSS (That we have to create ourselves based on these recommendations) ?

**Comment by staabm** [comment]
IMO the demos should contain at least frameworks as possible, so the reader dont need to know anything about 4rd party code.

**Comment by Arkni** [comment]
@jzaefferer @staabm 

I created 2 demos:
* Using Bootstrap: [live demo](https://rawgit.com/Arkni/jquery-validation/demos/demo/bootstrap/index.html)
* Using Semantic UI: [live demo](https://rawgit.com/Arkni/jquery-validation/demos/demo/semantic-ui/index.html)

Your thoughts ?

**Comment by staabm** [comment]
@Arkni thouse look great. Feel free to PR them separatly. Thanks!
