### ISSUE TITLE
Remove lastElement

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/jquery-validation#494]
See https://github.com/jzaefferer/jquery-validation/commit/c41f2f616d4b774859b7abf88f318ae409bff2f2#commitcomment-1765491

**Comment by staabm** [comment]
It seems still be used in the `onkeyup` handler: https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L275

**Comment by jzaefferer** [comment]
Related to #1508, which reintroduced it.. Addressing that should remove the need for `lastElement`.
